FreeRTOS_DNS.c

Description
-----------
Quite recently, we changed the signature of the DNS function `prvParseDNSReply()`:
~~~c
-    _static uint32_t prvParseDNSReply( DNSMessage_t *pxDNSMessageHeader,
+    _static uint32_t prvParseDNSReply( uint8_t * pucUDPPayloadBuffer,
size_t uxBufferLength,
BaseType_t xExpected );
~~~
The function analyses a DNS response. It is called from two different locations. The synchronous lookup is still OK, but the asynchronous lookup passes the whole packet, instead of the UDP payload.
After this PR, it will work again.
Test Steps
-----------
Define `ipconfigDNS_USE_CALLBACKS` in your FreeRTOSIPConfig.h, define a DNS callback function, and use `FreeRTOS_gethostbyname_a()` to lookup a host on the Internet.
Related Issue
-----------
None
By submitting this pull request, I …

Repair asynchronous DNS lookup

---

portable/NetworkInterface/pic32mzef/NetworkInterface_wifi.c

Description
-----------
There is a subtle dependency in +TCP on where 
`portable/NetworkInterface/pic32mzef/NetworkInterface_wifi.c` --> `amazon-freertos::iot_wifi.h`. 
There are upcoming changes to `iot_wifi.h::WIFINetworkParams_t`. This updates dependent +TCP code to use new `iot_wifi.h::WIFINetworkParams_t` structure. 
Test Steps
-----------
Build/Run `aws_demos` for the `pic32mzef` using the, soon to be merged, `dachalco/amazon-freertos` and this version of +TCP. 
Related Issue
-----------
- [amazon-freertos PR#2544](https://github.com/aws/amazon-freertos/pull/2544)
- The upcoming `amazon-freertos` changes to `iot_wifi.h`

WIFINetworkParams_t is changing. Update to conform

---

portable/NetworkInterface/xilinx_ultrascale/NetworkInterface.c
portable/NetworkInterface/xilinx_ultrascale/readme.md
portable/NetworkInterface/xilinx_ultrascale/uncached_memory.c
portable/NetworkInterface/xilinx_ultrascale/uncached_memory.h
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif.h
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_dma.c
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_hw.c
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_hw.h
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_physpeed.c
portable/NetworkInterface/xilinx_ultrascale/x_topology.h

Description
-----------
This PR replaces FreeRTOS [PR #262](https://github.com/FreeRTOS/FreeRTOS/pull/262), which will be closed.
Here is a network interface for Xilinx UltraScale+ 64-bits.
If you want to try the driver, please use the +TCP library from [this branch](https://github.com/htibosch/FreeRTOS/tree/FreeRTOS%2BTCP_64-bits_compatibility/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP).
There is a long FreeRTOS forum post about the development of this driver [here](https://forums.freertos.org/t/freertos-tcp-ip-on-arm-cortexa53/9898/62)
I want to thank Maxim Vechkanov for his contribution and help with FPGA and board issues.
I developed and tested the driver on a FZ3 Card from Myirtech.
I tested it with various protocols, and also iperf3, transferring data in both directions.
Several …

A network driver for Xilinx UltraScale+ 64-bits(v2)

---

FreeRTOS_DNS.c
FreeRTOS_IP.c

Description
-----------
This PR replaces my earlier FreeRTOS [PR #246](https://github.com/FreeRTOS/FreeRTOS/pull/246), which will be closed.
In two functions, it was assumed that the size of a point is 32 bits, or less.
~~~c
NetworkBufferDescriptor_t *pxUDPPayloadBuffer_to_NetworkBuffer( const void * pvBuffer );
NetworkBufferDescriptor_t *pxPacketBuffer_to_NetworkBuffer( const void *pvBuffer );
~~~
With this patch, the functions can also be used on a 64-bit platform.
Also, in FreeRTOS_DNS.c, one function `prvCreateDNSMessage()` was going arthmetic with pointer, like `uxLength = ( size_t ) ( pucLast - pucFirst )`.
I changed this by using indexes in stead of char pointers. No more pointer arithmetic is necessary.
I tested the changes on a Xilinx Ultrascale+, which is 64-bits.
By submitting …

FreeRTOS+TCP compatibility with 64-bit platforms (v2)

---

FreeRTOS_TCP_IP.c

Description
-----------
During one of the revisions of FreeRTOS_TCP_IP.c, probably for MISRA, one line got simplified, but in an incorrect way. As a consequence, the value of `ulHighestSequenceNumber` won't be updated temporarily.
As `ulHighestSequenceNumber` is only read in the FIN-state ( closing state ) of a TCP connection, this won't cause a real problem. 
This PR will undo the change made earlier at line 3197:
~~~c
-    if( ( ulSequenceNumber + ulReceiveLength ) > pxTCPWindow->rx.ulHighestSequenceNumber )
+    if( ( ( int32_t ) ( ulSequenceNumber + ulReceiveLength - pxTCPWindow->rx.ulHighestSequenceNumber ) ) > 0L )
~~~
Test Steps
-----------
It is tricky to replicate the problem. You would have to manipulate the starting sequence number of the peer.
I tested it in a real simulation, …

Corrected the comparison with rx.ulHighestSequenceNumber

---

.github/lexicon.txt
FreeRTOS_DHCP.c
FreeRTOS_DNS.c
FreeRTOS_IP.c
FreeRTOS_Sockets.c
FreeRTOS_UDP_IP.c
include/FreeRTOS_DHCP.h
include/FreeRTOS_IP_Private.h
test/cbmc/proofs/DHCP/DHCPProcess/DHCPProcess_harness.c
tools/tcp_utilities/tcp_netstat.md

Description
-----------
[Andy Bennett](https://github.com/andyjpb) reported in [PR #123](https://github.com/FreeRTOS/FreeRTOS/pull/123) that sometimes the DHCP status machine keeps passing through same sequence of states again and again.
He wrote that it helps when `dhcpINITIAL_TIMER_PERIOD` is given a higher value.
Here is what happened:
While waiting for a DHCP reply, two events happen almost at the same time:
1) A UDP packet comes in with an acknowledgement
2) An internal DHCP timer expires ( after `dhcpINITIAL_TIMER_PERIOD` ticks ).
After event-1 the state goes to `eLeasedAddress`, which lasts until a time-out is reached.
After event-2, cause by a time-out, leasing is finished, and a new request will be sent.
Event-2 should be ignored because a new time-out has already been scheduled. …

Avoid DHCP race

---

test/cbmc/proofs/Makefile.template
test/cbmc/proofs/make_common_makefile.py
test/cbmc/proofs/run-cbmc-proofs.py

This pull request uses the kissat solver (if available) to accelerate CBMC property checking.  (It does not yet accelerate coverage checking.)
Two subsequent commits to this pull request also do some cleanup:  Run CBMC with the --flush flag to flush stdout and remove the use of the phony-clean touch file when building goto binaries.

Run CBMC property checking with kissat if available.

---

.github/lexicon.txt
FreeRTOS_TCP_IP.c

Call closesocket() for a child-socket in case of a TCP protocol error during the SYN phase.
Description
-----------
When an application creates a socket, the application is responsible for it deletion.  When done, it must call `FreeRTOS_closesocket()`.  This is true for sockets created with `FreeRTOS_socket()`, and child-sockets obtained by calling `FreeRTOS_accept()`.  Those two functions hand over the ownership of a socket.
However, a child socket in the TCP states between the first SYN and the second ACK ( SYN, SYN+ACK, ACK ), the socket is owned by the IP-stack.  This is true for any OS and for any IP-stack.
In FreeRTOS+TCP, these sockets have a **limited life-time** in this SYN-stage, by default 30 seconds (`ipconfigTCP_HANG_PROTECTION_TIME`).  This is needed in case the negotiation …

Call closesocket() for a child-socket in case of a TCP protocol error

---

portable/NetworkInterface/DriverSAM/NetworkInterface.c
portable/NetworkInterface/RX/NetworkInterface.c
portable/NetworkInterface/STM32Fxx/NetworkInterface.c
portable/NetworkInterface/esp32/NetworkInterface.c

Description
-----------
When developing an embedded application using TCP/IP, it can be very useful to get insight into the consumptions of resources.  Think of the number of available network buffers, the available heap, or the minimum space in the queue of the IP-task.
A while ago, I added a function `vPrintResourceStats()` to [FreeRTOS_IP.c](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/FreeRTOS_IP.c#L3041).
This PR changes 4 network interfaces to let them call `vPrintResourceStats()`.
Test Steps
-----------
Run a project from an of the platforms ESP32, Renesas' RX, STM32Fxx, or SAM, and look at the logging produced.
Note that `ipconfigHAS_PRINTF` must be defined as `1`, and `FreeRTOS_printf()` must be functional. 
By submitting this pull request, I confirm that you can use, …

Let 4 network interfaces use the function vPrintResourceStats()

---

.github/lexicon.txt
FreeRTOS_DHCP.c
FreeRTOS_IP.c
include/FreeRTOS_DHCP.h

Description
-----------
In FreeRTOS_DHCP.c, a network buffer is obtained in a blocking way. This is no problem because during the DHCP negociation, the device will drop almost all incoming packets. But if it runs out of network buffers, the DHCP process could stall, thus stalling the IP-task.
In this PR, `pxGetNetworkBufferWithDescriptor()` will be called in a polling way ( with a time-out of zero ). When it fails, a new attempt will be done after 250 msec, a time-out defined by this macro:
~~~c
#define dhcpINITIAL_TIMER_PERIOD    ( pdMS_TO_TICKS( 250U ) )
~~~
Test Steps
-----------
I tested it by simulating a shortage of packages, using the following source of randomness:
~~~
static BaseType_t prvDoCreateMessage( void )
{
uint32_t ulValue;
xApplicationGetRandomNumber( &( ulValue ) );
/* …

DHCP network buffers

---

.github/lexicon.txt
.github/workflows/ci.yml
FreeRTOS_ARP.c

Description
-----------
A few changes were made to FreeRTOS_ARP.c:
- Multicast addresses are now recognised and the MAC-address is calculated
- No special code needed for LLMNR any more ( also multicast )
- Do not test for `FreeRTOS_AllEndPointsUp()` incase ipconfigARP_STORES_REMOTE_ADDRESSES = 0
- Added xARPWaitResolution(): can be used by the application to force an ARP look-up
Test Steps
-----------
A module for integration testing is in preparation. That will test all changes here above.

Some changes to ARP /multi

---

.github/workflows/ci.yml
FreeRTOS_Sockets.c

Description
-----------
A minor change: let the compilation of the function `prvSockopt_so_buffer()` depend on the macro `ipconfigUSE_TCP`.

FreeRTOS_Sockets /multi: Make prvSockopt_so_buffer() TCP-only

---

.github/workflows/ci.yml
FreeRTOS_ND.c

Description
-----------
Start using the new function `vSetMultiCastIPv6MacAddress()` to resolve an IPv6 multicast address.
Test Steps
-----------
Run any IPv6 demo along with e.g. router advertisement.
Related Issue
-----------

FreeRTOS_ND: use the new function 'vSetMultiCastIPv6MacAddress()'

---

.github/lexicon.txt
.github/workflows/ci.yml
FreeRTOS_TCP_IP.c

Description
-----------
Applied #94: Corrected the comparison with rx.ulHighestSequenceNumber
Applied #102: Call `closesocket()` for a child-socket in case of a TCP protocol error
Test Steps
-----------
See both PR's for more detailed information.

FreeRTPS_TCP_IP: Applied to commits from the main /single branch

---

FreeRTOS_IP.c
include/FreeRTOS_IP.h

Description
-----------
Added the downward compatibility mode `ipconfigCOMPATIBLE_WITH_SINGLE` which has a global start-up function:
~~~c
BaseType_t FreeRTOS_IPInit( const uint8_t ucIPAddress[ ipIP_ADDRESS_LENGTH_BYTES ],
const uint8_t ucNetMask[ ipIP_ADDRESS_LENGTH_BYTES ],
const uint8_t ucGatewayAddress[ ipIP_ADDRESS_LENGTH_BYTES ],
const uint8_t ucDNSServerAddress[ ipIP_ADDRESS_LENGTH_BYTES ],
const uint8_t ucMACAddressP[ ipMAC_ADDRESS_LENGTH_BYTES ] )
~~~
In this mode, only one interface can be used which will have one end-point. No code changes are needed, except adding the module `FreeRTOS_Routing.c`.
Added functions to resolve multicast addresses, both for IPv4 and IPv6.
I don't know what went wrong with the earlier #110 but it showed loads of differences with the branch …

Updates for FreeRTOS_IP.c /multi version 2.

---

.github/workflows/ci.yml
portable/NetworkInterface/DriverSAM/NetworkInterface.c

Description
-----------
This PR make DriverSAM compatible with /multi and IPv6.
The driver can still be used in backward compatible mode when `ipconfigCOMPATIBLE_WITH_SINGLE` is defined in FreeRTOSIPConfig.h.
Test Steps
-----------
Replace all /single sources with this branch, add FreeRTOS_Routing.c, define `ipconfigCOMPATIBLE_WITH_SINGLE` and run the application.

Network interface /multi /IPv6 for SAM4E/SAME70

---

.github/workflows/ci.yml
portable/NetworkInterface/pic32mzef/NetworkInterface_eth.c

Description
-----------
This PR makes the PIC32 network interface compatible with /multi and IPv6. Only `NetworkInterface_eth.c` is adapted, not the WiFi driver.
The driver can still be used in backward compatible mode when `ipconfigCOMPATIBLE_WITH_SINGLE` is defined in FreeRTOSIPConfig.h.
Test Steps
-----------
Replace all /single sources with this branch, add FreeRTOS_Routing.c, define `ipconfigCOMPATIBLE_WITH_SINGLE` and run the application.

Network interface /multi /IPv6 for PIC32MZEF ETH

---

portable/NetworkInterface/Cyclone_V_SoC/NetworkInterface.c
portable/NetworkInterface/Cyclone_V_SoC/cyclone_dma.c
portable/NetworkInterface/Cyclone_V_SoC/cyclone_dma.h
portable/NetworkInterface/Cyclone_V_SoC/cyclone_emac.c
portable/NetworkInterface/Cyclone_V_SoC/cyclone_emac.h
portable/NetworkInterface/Cyclone_V_SoC/cyclone_phy.c
portable/NetworkInterface/Cyclone_V_SoC/cyclone_phy.h
portable/NetworkInterface/Cyclone_V_SoC/sleep.h

Description
-----------
Recreating PR by (and on behalf of) @htibosch (https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/128) after branch name change.
This PR will add a driver for Cyclone SOC. suitable for /multi /IPv6.
It has been tested on a board called "DE10-NANO CYCLONE V SE SOC KIT", which has only one PHY.
When you have questions about it, please refer to the [FreeRTOS forum](https://forums.freertos.org).

Adding a network driver for Cyclone SOC, suitable for /multi /IPv6

---

portable/NetworkInterface/STM32Fxx/NetworkInterface.c

Description
-----------
The function `prvNetworkInterfaceInput()` in the network interface for STM32Fx has a bug that shows under these circumstances:
1) receive and accept a packet
2) receive a packet that is dropped immediately after 1)
I submitted a comparable PR for the /multi library: #143
It is solved by initialising the local variable `pxNewDescriptor` to NULL in each loop.

STM32Fx: Move local variables to inner loop in prvNetworkInterfaceInput() (/single)

---

FreeRTOS_TCP_WIN.c

Fix the following warning when building for 64 bit:
warning: conversion from ‘long unsigned int’ to ‘uint32_t’ {aka ‘unsigned int’} changes value from ‘18446744073709551615’ to ‘4294967295’ [-Woverflow]
uint32_t ulReturn = ~0UL;
^

TCP_WIN: fix compile warning on x86_64

---

History.txt
test/cbmc/proofs/ARP/ARP_FreeRTOS_ClearARP/ClearARP_harness.c
test/cbmc/proofs/ARP/ARP_FreeRTOS_ClearARP/Makefile.json

Description
-----------
Fix FreeRTOS_ClearARP CBMC proof for IPv6.
Make the proof to be compatible with IPv6 source code. Add in some more checks/asserts etc.
Test Steps
-----------
Related Issue
-----------

Fix FreeRTOS_ClearARP CBMC proof for IPv6

---

test/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/Configurations.json
test/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/OutputARPRequest_harness.c

Description
-----------
Fix the proof for FreeRTOS_OutputARPRequest in IPv6 branch.
Make the proof to be compatible with IPv6 source code. Add in some more checks/asserts etc.
Test Steps
-----------
Related Issue
-----------

Fix the proof for FreeRTOS_OutputARPRequest in IPv6 branch

---

History.txt
test/cbmc/proofs/ARP/ARPGetCacheEntry/ARPGetCacheEntry_harness.c
test/cbmc/proofs/ARP/ARPGetCacheEntry/Configurations.json

Description
-----------
Fix Proof for ARPGetCacheEntry
Test Steps
-----------
Related Issue
-----------

Fix Proof for ARPGetCacheEntry

---

FreeRTOS_ARP.c
History.txt
test/cbmc/proofs/ARP/ARPGetCacheEntryByMac/ARPGetCacheEntryByMac_harness.c
test/cbmc/proofs/ARP/ARPGetCacheEntryByMac/Makefile.json

Description
-----------
Fix Proof for ARPGetCacheEntryByMAC
Test Steps
-----------
Related Issue
-----------

Fix CBMC Proof for ARPGetCacheEntryByMAC

---

.github/lexicon.txt
FreeRTOS_ARP.c
include/FreeRTOS_IP.h
test/unit-test/FreeRTOS_TCP_Unit_test.c
test/unit-test/stubs/FreeRTOS_ARP_stubs.c

Description
-----------
**Note:** the name of my branch is incorrect, it should have been "arp_store_local_addresses_only", in stead of referring to "dhcp".
Three changes to FreeRTOS_ARP.c :
1) When `ipconfigARP_STORES_REMOTE_ADDRESSES` is `0`, ARP doesn't want to store any non-local IP-address in the ARP cache.
We made an exception, during the DHCP phase, when `*ipLOCAL_IP_ADDRESS_POINTER` is still zero, any address would be stored:
~~~c
#if ( ipconfigARP_STORES_REMOTE_ADDRESSES == 0 )
if( ( ( ulIPAddress & xNetworkAddressing.ulNetMask ) == ( ( *ipLOCAL_IP_ADDRESS_POINTER ) & xNetworkAddressing.ulNetMask ) ) ||
( *ipLOCAL_IP_ADDRESS_POINTER == 0UL ) )
{
/* Store the address. */
}
~~~
DHCP doesn't need ARP beecause the client uses the IP broadcast address to find the DHCP server. I would …

FreeRTOS_ARP.c : store local addresses only

---

History.txt
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/Configurations.json
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/OutputARPRequest_harness.c
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc2/Configurations.json
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc2/OutputARPRequest_harness.c

Description
-----------
Fix the ARP_OutputARPRequest_buffer_alloc[1,2] CBMC proofs
Test Steps
-----------
Related Issue
-----------

Fix the ARP_OutputARPRequest_buffer_alloc[1,2] CBMC proofs

---

test/cbmc/proofs/ARP/ulARPRemoveCacheEntryByMac/ulARPRemoveCacheEntryByMac_harness.c

Description
-----------
Fix the ulARPRemoveCacheEntryByMac CBMC proof.
Test Steps
-----------
Related Issue
-----------

Fix ulARPRemoveCacheEntryByMac CBMC proof

---

test/cbmc/proofs/ARP/ARPProcessPacket/ARPProcessPacket_harness.c
test/cbmc/proofs/ARP/ARPProcessPacket/Configurations.json

Description
-----------
Fix the ARPProcessPacket CBMC proof.
Test Steps
-----------
Related Issue
-----------

Fix the CBMC proof of ARPProcessPacket

---

History.txt
test/cbmc/proofs/DNS/DNSHandlePacket/DNShandlePacket_harness.c
test/cbmc/proofs/DNS/DNSHandlePacket/Makefile.json

Description
-----------
Fix CBMC proof of ulDNSHandlePacket function.
Test Steps
-----------
Related Issue
-----------

Fix CBMC proof of ulDNSHandlePacket IPv6

---

test/cbmc/proofs/DNS/DNSclear/DNSclear_harness.c

Description
-----------
Fix CBMC proof of DNSclear function.
Test Steps
-----------
Related Issue
-----------

Fix the CBMC proof of DNSclear IPv6

---

test/cbmc/proofs/DNS/DNSlookup/DNSlookup_harness.c

Description
-----------
Fix CBMC proof of DNSlookup function.
Test Steps
-----------
Related Issue
-----------

Fix CBMC proof of DNSlookup function.

---

FreeRTOS_DHCP.c
History.txt
test/cbmc/proofs/DHCP/DHCPProcessEndPoint/DHCPProcessEndPoint_harness.c
test/cbmc/proofs/ProcessDHCPReplies/Makefile.json
test/cbmc/proofs/ProcessDHCPReplies/ProcessDHCPReplies_harness.c

Description
-----------
Test Steps
-----------
Related Issue
-----------

Fix CBMC proof of ProcessDHCPReplies

---

FreeRTOS_DNS.c
History.txt
test/cbmc/proofs/DNS/DNSgetHostByName_a/DNSgetHostByName_a_harness.c
test/cbmc/proofs/DNS/DNSgetHostByName_a/Makefile.json

Description
-----------
Fix CBMC proof of DNSgetHostByName_a function.
Test Steps
-----------
Related Issue
-----------

Fix the CBMC proof of DNSgetHostByName_a

---

FreeRTOS_DNS.c
FreeRTOS_IP.c
FreeRTOS_TCP_IP.c
FreeRTOS_UDP_IP.c
include/FreeRTOSIPConfigDefaults.h
include/FreeRTOS_IP_Private.h

IP fragmentation tweaks as discussed in https://forums.freertos.org/t/freertos-tcp-do-not-fragment-flag/11616/3
-----------
Moves all IP flag defines in FreeRTOS_IP_Private.h so that they are accessible to all protocols
Adds definitions for the IP fragmentation flags
Modifies the fragmentation check for incoming frames to drop both the first and later fragments.
Sets the "don't fragment" flag for all outgoing IP frames ( ICMP, DNS, UDP, TCP )
Removes ipGET_UDP_PAYLOAD_OFFSET_FOR_FRAGMENT as it appears obsolete. The stack never outputs fragments.
Related Issue
-----------
None

Don't Fragment Flags patch.

---

FreeRTOS_IP.c

On 64 bit systems, FreeRTOS_IPInit() would assert
ipconfigBUFFER_PADDING was equal to 14 to "make sure there
is enough space in pucEthernetBuffer to store a pointer."
This prevents the driver from requesting additional
padding, so make the assert greater than or equal to 14.
Also use the final ipBUFFER_PADDING value instead of
ipconfigBUFFER_PADDING, which is probably what was
intended?

fix IP buffer padding check on 64bit

---

portable/NetworkInterface/pic32mzef/NetworkInterface_eth.c

Update files referencing aws_application_version.h to use iot_application_version.h
Description
-----------
Update references to the aws_application_version.h file due to the configuration rename in the amazon-freertos repository.
Test Steps
-----------
Verify that builds for the pic32mzef platform are successful.

Update files referencing aws_application_version.h to use iot_application_version.h

---

.github/lexicon.txt
FreeRTOS_IP.c
FreeRTOS_Sockets.c
FreeRTOS_Stream_Buffer.c
FreeRTOS_TCP_IP.c
include/FreeRTOS_IP.h
include/FreeRTOS_IP_Private.h
include/FreeRTOS_Sockets.h
include/FreeRTOS_Stream_Buffer.h
test/cbmc/proofs/ARP/ARPAgeCache/Makefile.json
test/cbmc/proofs/ARP/ARPGenerateRequestPacket/Makefile.json
test/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/Configurations.json
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/Configurations.json
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc2/Configurations.json
test/cbmc/proofs/CheckOptions/Makefile.json
test/cbmc/proofs/TCP/prvTCPHandleState/Makefile.json
test/cbmc/proofs/TCP/prvTCPPrepareSend/Makefile.json
test/cbmc/proofs/TCP/prvTCPReturnPacket/Makefile.json
test/cbmc/proofs/TCP/prvTCPReturnPacket/TCPReturnPacket_harness.c
test/cbmc/proofs/UDP/vProcessGeneratedUDPPacket/Makefile.json
test/cbmc/proofs/parsing/ProcessReceivedTCPPacket/Makefile.json
test/unit-test/FreeRTOS_TCP_Unit_test.c
test/unit-test/TCPFilePaths.cmake
test/unit-test/stubs/FreeRTOS_ARP_stubs.c
test/unit-test/unit_test_build.cmake
tools/tcp_utilities/tcp_mem_stats.c

Description
-----------
This PR removes function definitions in header files and puts them in proper source (.c) files.
Doing so required fixing CBMC proofs, unit tests, and build checks. Moreover, adding the function definitions to c files required the doxygen documentation to be updated.
As a result of the above changes, the total changed files have increased from 5->24.
Test Steps
-----------
Related Issue
-----------

Remove function defs from header files

---

FreeRTOS_TCP_IP.c

Description
-----------
When `ipconfigZERO_COPY_TX_DRIVER` is defined, the TCP driver sometimes has to duplicated a network buffer, so that it can be owned by the network interface.
When the duplication fails, the local variable will still be set, unconditionally:
~~~
pxNetworkBuffer = pxDuplicateNetworkBufferWithDescriptor( pxNetworkBuffer, ( size_t ) pxNetworkBuffer->xDataLength );
if( pxNetworkBuffer == NULL )
{
FreeRTOS_debug_printf( ( "prvTCPReturnPacket: duplicate failed\n" ) );
}
xDoRelease = pdTRUE;
~~~
It would be more correct to set it only when the duplication has succeeded:
~~~
pxNetworkBuffer = pxDuplicateNetworkBufferWithDescriptor( pxNetworkBuffer, ( size_t ) pxNetworkBuffer->xDataLength );
if( pxNetworkBuffer != NULL )
{
xDoRelease = pdTRUE;
}
else
{
FreeRTOS_debug_printf( …

Do not release a network buffer if it equals to NULL

---

portable/NetworkInterface/MPS2_AN385/NetworkInterface.c
portable/NetworkInterface/MPS2_AN385/ether_lan9118/smsc9220_eth_drv.c

Circumvent Qemu MPS2 networking bug
Description
-----------
Qemu has a bug in its network driver implementation for MPS2 (lan9118), which the peeked networked buffer size is different than the actual buffer size.
As we are allocating memory after reading the peeked size, there is a chance for a buffer overflow, if the message size peeked is smaller that the actually message size.
We have opened a bug with Qemu to fix the bug, in the meantime, we have circumvented the issue in this patch.
https://bugs.launchpad.net/qemu/+bug/1904954
Test Steps
-----------
Manual testing
```
$ sudo nc -l 7
Password:
TxRx message number 0FGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrs
```
By submitting this pull request, I confirm …

Circumvent Qemu MPS2 networking bug

---

FreeRTOS_IP.c
FreeRTOS_Sockets.c
FreeRTOS_TCP_WIN.c

Fix various warnings like:
/FreeRTOS-Plus-TCP/FreeRTOS_IP.c: In function 'FreeRTOS_strerror_r':
/FreeRTOS-Plus-TCP/FreeRTOS_IP.c:3395:60: error: format '%d' expects argument of type 'int', but argument 4 has type 'long int' [-Werror=format=]
( void ) snprintf( pcBuffer, uxLength, "Errno %d", ( int32_t ) xErrnum );
~^   ~~~~~~~~~~~~~~~~~~~
%ld
This was tested against an ARM a9 platform (zynq).

fix compiler warnings about casting to format string

---

.github/workflows/ci.yml

Added git-secrets check to Github actions
Description
-----------
The added Github action will check and report PR check failure if a credential is committed into the repository.
Test Steps
-----------
Check the github Actions for the test result
Related Issue
-----------

Added git-secrets check to Github actions

---

.github/lexicon.txt
FreeRTOS_IP.c
include/FreeRTOSIPConfigDefaults.h

Description
-----------
This PR allows users to implement custom Ethernet protocols. Without those changes, users have to modify FreeRTOS+TCP code every time they pull the latest changes. An example usage of the proposed changes is implementing LLDP, PPPoE, or any other Ethernet protocol except for the already supported ones like IP or ARP. More details on the discussion that preceded this PR is available [in the forums](https://forums.freertos.org/t/freertos-tcp-custom-ethernet-protocols/11858/14)
Test Steps
-----------
None
Related Issue
-----------
None

User hook function for handling unsupported Ethernet frames

---

FreeRTOS_ARP.c

Description
-----------
The function `xARPWaitResolution()` can send an ARP request and wait for the result. Both the time that it may take, as well as the number of attempts are limited.
The time is limited by a parameters `uxTicksToWait`: the maximum number of clock ticks that the function will last.
The maximum number of attempts is limited by a macro `ipconfigMAX_ARP_RETRANSMISSIONS`, which defaults to 5.
The last limiter did not work, because it omits to decrease the value of `uxSendCount`, which will not be repaired:
~~~c
while( uxSendCount > 0 )
{
FreeRTOS_OutputARPRequest( ulIPAddress );
vTaskDelay( uxSleepTime );
xLookupResult = eARPGetCacheEntry( &( ulIPAddress ), &( xMACAddress ) );
if( ( xTaskCheckForTimeOut( &( xTimeOut ), &( uxTicksToWait ) ) == pdTRUE ) ||
( xLookupResult …

Limit number of attempts to resolve an address in xARPWaitResolution

---

.github/lexicon.txt
FreeRTOS_IP.c

Description
-----------
The function `usGenerateChecksum()` calculates all checksums for all purposes: for the IP-headers ( IPv4 and IPv6 ), and for the protocol headers ( TCP, UDP, and ICMP ).
The current version of [`usGenerateChecksum()`](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/6ae29a62db3342182739999476c7d972d3dcf0e3/FreeRTOS_IP.c#L2820) was developed a long time ago. It was heavily optimised for an AVR32 processor ( UC3A ), which has a few handy instructions that ARM doesn't have.
I created a new version that is a lot **simpler** **and** **faster**. Also it is MISRA compatible. What it does is the following:
1. When the pointer to the buffer is not aligned, the first byte will be stored in `usTerm`, and the bytes in the accumulator will be swapped.
2. Now the pointer is …

IPv6/Multi : A new usGenerateChecksum() that is faster and MISRA compliant

---

FreeRTOS_IP.c
portable/BufferManagement/BufferAllocation_1.c
portable/BufferManagement/BufferAllocation_2.c

Static allocation of tasks and queues, if configSUPPORT_STATIC_ALLOCATION == 1
Description
-----------
Adds the support for static allocation of the following:
- IP-Task
- Network Event Queue
- Network Buffer Semaphore
These will be statically allocated, if configSUPPORT_STATIC_ALLOCATION == 1
A reason for wanting this, could be to move the FreeRTOS heap to a cached memory while still having the stack of the tasks in a faster uncached memory.
Test Steps
-----------
Related Issue
-----------

Static allocation, if configSUPPORT_STATIC_ALLOCATION == 1 (#208)

---

.github/lexicon.txt
FreeRTOS_IP.c
include/FreeRTOS_IP.h

Description
-----------
In response to issue [#549](https://github.com/FreeRTOS/FreeRTOS/issues/549) by @RichardBarry, which responded to a request in the [FreeRTOS forum](https://forums.freertos.org/t/start-with-tcp-ip-task-suspended/12180) by Glen English: a new function that returns the handle to the IP-task.
As simple as this:
~~~c
TaskHandle_t FreeRTOS_GetIPTaskHandle( void )
{
return xIPTaskHandle;
}
~~~

Add a method to obtain the handle of the FreeRTOS+TCP IP task

---

FreeRTOS_Sockets.c

Description
-----------
This fixes the unnecessary zero time-out in FreeRTOS_closesocket and updates the comment as
follow-up of https://forums.freertos.org/t/issues-with-freertos-closesocket/12195
This has no change if this API is called from the IP-task as described above.
Test Steps
-----------
It's actually almost impossible to make the queue overflow in practice.
Nevertheless it is better to wait here, than risk a memory leak.

Use an infinite timeout in FreeRTOS_closesocket when called from a user task

---

portable/NetworkInterface/MPS2_AN385/NetworkInterface.c
portable/NetworkInterface/MPS2_AN385/ether_lan9118/SMM_MPS2.h
portable/NetworkInterface/MPS2_AN385/ether_lan9118/smsc9220_eth_drv.c

Description
-----------
Remove dead code and reformat MPS2_AN385 network driver so it conforms to the FreeRTOS+TCP coding and style guides.
Test Steps
-----------
Tested from Windows, needs to be executed from Linux too.

Reformat MPS2_AN385 network driver

---

.github/lexicon.txt
FreeRTOS_IP.c
FreeRTOS_Sockets.c
include/FreeRTOS_IP_Private.h

Description
-----------
This prevents FreeRTOS_DeleteSocketSet to delete the
SocketSet, while a eSocketCloseEvent is still
queued and the Socket_t refers to a deleted
SocketSet_t for a short time.
Related Issue
-----------
https://forums.freertos.org/t/issues-with-freertos-closesocket/12195

Delete the SocketSet_t in the IP task

---

.github/lexicon.txt
FreeRTOS_IP.c
include/FreeRTOS_IP_Private.h
portable/NetworkInterface/Zynq/NetworkInterface.c

Description
-----------
Now that the ipv6_multi branch mostly complies with MISRA [see PR #220](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/220), it is time to reduce the complexity of the code.
I started with FreeRTOS_IP.c. Most of the work is done in the functions `usGenerateProtocolChecksum()` and `prvProcessIPPacket()`, which had complexity scores of 53 and 32.
~~~
10      88      52   FreeRTOS_IP.c(1951): prvProcessEthernetPacket
11     139      94   FreeRTOS_IP.c(2280): prvAllowIPPacketIPv4
13      86      61   FreeRTOS_IP.c(3221): usGenerateChecksum
20     250     144   FreeRTOS_IP.c(273): prvIPTask
32     202     122   FreeRTOS_IP.c(2433): prvProcessIPPacket
53     399     294   FreeRTOS_IP.c(2796): usGenerateProtocolChecksum
~~~
There is still some work left to do:
~~~
8 …

IPv6/Multi: Reducing the complexity of FreeRTOS_IP.c

---

FreeRTOS_IP.c
FreeRTOS_ND.c

Description
-----------
Some change to ICMP/ping handling:
- Depending on `ipconfigFORCE_IP_DONT_FRAGMENT`, set or clear the fragment field `usFragmentOffset`.
- Depending on `ipconfigDRIVER_INCLUDED_TX_IP_CHECKSUM`, do a complete checksum calculation, or just clear the ICMP protocol checksum.
- Check the return value of `prvChecksumICMPv6Checks()`:
~~~c
-    prvChecksumICMPv6Checks( uxBufferLength, pxSet );
+    xReturn = prvChecksumICMPv6Checks( uxBufferLength, pxSet );
~~~
Test Steps
-----------
I tested while setting:
~~~c
#define ipconfigDRIVER_INCLUDED_RX_IP_CHECKSUM   0
#define ipconfigDRIVER_INCLUDED_TX_IP_CHECKSUM   0
~~~
meaning that the IP-task will calculate all checksums "manually".
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

IPv6/Multi: do the ICMP checksum calculations in the same way as for TCP and UDP.

---

FreeRTOS_Sockets.c

Description
-----------
Much the same as #242 : before a UDP socket is closed, clear its function pointers to event handlers:
~~~c
if( pxSocket->ucProtocol == ( uint8_t ) FREERTOS_IPPROTO_UDP )
{
/* Clear the two UDP handlers. */
pxSocket->u.xUDP.pxHandleReceive = NULL;
pxSocket->u.xUDP.pxHandleSent = NULL;
}
~~~
Also a minor change is taken from #226 : "Use an infinite timeout in FreeRTOS_closesocket when called from a user task".

IPv6/multi: Before closing a UDP socket, clear the UDP handlers for Receive/Send

---

FreeRTOS_Sockets.c

Description
-----------
The function `FreeRTOS_shutdown()` returned `EOPNOTSUPP` when the TCP socket is not connected. It would be more appropriate to return `ENOTCONN`
See also #227 which was a PR for the main branch.

IPv6/multi : let FreeRTOS_shutdown() return a different error code

---

FreeRTOS_IP.c
portable/BufferManagement/BufferAllocation_1.c
portable/BufferManagement/BufferAllocation_2.c

Description
-----------
Quite recently, support for static allocation was added to the main branch.
This PR makes the same changes.
For more information, see #217, thanks to @tajen.
Test Steps
-----------
Define `configSUPPORT_STATIC_ALLOCATION` in `FreeRTOSConfig.h` and run the project.

IPv6/multi: Add support for FreeRTOS static allocation.

---

.github/lexicon.txt
FreeRTOS_TCP_IP.c
FreeRTOS_TCP_WIN.c
include/FreeRTOS_TCP_WIN.h

Description
-----------
See PR #225 : "Before sending a challenge ACK, check the sequence number more properly"
This PR is updating the labs/ipv6_multi branch to have the same logic.

IPv6/multi : Before sending a challenge, check the sequence number

---

.github/lexicon.txt
FreeRTOS_IP.c
include/FreeRTOS_IP.h

Description
-----------
See the earlier #222 for the main branch.
This makes the same change for the ipv6_multi branch: adding a public function that returns the task handle of the IP-task.

IPv6/multi : Add a method to obtain the handle of the IP-task

---

FreeRTOS_IP.c

Swapping the UDP CRC to 0xffff from 0x0000 is expected
behaivor as per RFC 768[1]. Remove the associated debug
message since it is not interesting to the user.
[1]: https://datatracker.ietf.org/doc/html/rfc768

FreeRTOS_IP: remove CRC swap message

---

.github/lexicon.txt
FreeRTOS_IP.c
FreeRTOS_Sockets.c
include/FreeRTOSIPConfigDefaults.h
include/FreeRTOS_IP_Private.h
portable/NetworkInterface/MPS2_AN385/ether_lan9118/smsc9220_eth_drv.c

Description
-----------
@RichardBarry reported a few compiler warnings that may occur when building with arm-none-eabi-gcc with `-Wall -Wextra`.
Here is the list of warnings:
~~~
./../../lib/FreeRTOS/freertos-plus-tcp/tools/tcp_utilities/tcp_mem_stats.c:52:13: note: #pragma message: ipconfigTCP_MEM_STATS_MAX_ALLOCATION undefined?
52 |     #pragma message ("ipconfigTCP_MEM_STATS_MAX_ALLOCATION undefined?")
|             ^~~~~~~
./../../lib/FreeRTOS/freertos-plus-tcp/FreeRTOS_Sockets.c:4497:97: warning: format '%d' expects argument of type 'int', but argument 4 has type 'long int' [-Wformat=]
4497 |                     const int32_t copied_len = snprintf( ucChildText, sizeof( ucChildText ), " %d/%d",
| …

Eliminate a few compiler warnings

---

.github/lexicon.txt
FreeRTOS_IP.c
FreeRTOS_TCP_IP.c
include/FreeRTOS_IP_Private.h
test/cbmc/proofs/TCP/prvTCPHandleState/TCPHandleState_harness.c
test/cbmc/proofs/parsing/ProcessReceivedTCPPacket/ProcessReceivedTCPPacket_harness.c

This avoids problems with calling FreeRTOS_closesocket
from the IP task.
This is an alternative to #229 
-----------

Use vSocketCloseNextTime instead of FreeRTOS_closesocket

---

.github/lexicon.txt
include/FreeRTOSIPConfigDefaults.h
tools/tcp_utilities/tcp_mem_stats.c

Description
-----------
In my previous [PR #260](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/260), I defined a macro in `FreeRTOSIPConfigDefaults.h`:
~~~c
#define ipconfigTCP_MEM_STATS_MAX_ALLOCATION   0
~~~
just to prevent a pragma/message showing up, saying: "`ipconfigTCP_MEM_STATS_MAX_ALLOCATION undefined?`"
This macro defines the length of an array, and so it should never be defined as zero. I removed the define, and added some comments in tcp_mem_stats.c:
~~~c
/* If you don't want to see this pragma message, you can either
* remove it or define 'ipconfigTCP_MEM_STATS_MAX_ALLOCATION' in
* your freeRTOSIPConfig.h. */
~~~
When `ipconfigTCP_MEM_STATS_MAX_ALLOCATION` was zero, I discovered an issue: `vTaskSuspendAll()` would be called without ever calling `xTaskResumeAll()`!
I …

Revising tcp_mem_stats.c

---

.github/lexicon.txt
FreeRTOS_DNS.c
test/cbmc/proofs/DNS/DNSgetHostByName_cancel/DNSgetHostByName_cancel_harness.c
test/cbmc/proofs/DNS/DNSgetHostByName_cancel/Makefile.json

Description
-----------
When `ipconfigDNS_USE_CALLBACKS` is defined, it is possible to do a DNS look-up in an asynchronous way, using one of these functions:
`FreeRTOS_getaddrinfo_a()` is the new IPv4/6 lookup function.
`FreeRTOS_gethostbyname_a()` is the older function that was used for IPv4 only.
This PR makes sure that when the application hook is called, the scheduler will not be suspended.
Only when iterating through the `List_t`, the scheduler will be suspended.
Test Steps
-----------
Do a lookup, and check the scheduler state during the call-back.

IPv6/multi : only call DNS application hooks while scheduler is running

---

.github/lexicon.txt
.github/workflows/ci.yml
FreeRTOS_UDP_IP.c
include/FreeRTOSIPConfigDefaults.h

Description
-----------
In this PR I worked on the complexity of the code in FreeRTOS_UDP_IP.c
It had only 2 functions: send and receive an UDP packet. I have split these functions up into a total of 10 functions.
Here are the new complexity scores for this module:
~~~
Score | ln-ct | nc-lns| file-name(line): proc-name
1      20      16   FreeRTOS_UDP_IP.c(265): prvUDPSendPacket
2      21      18   FreeRTOS_UDP_IP.c(117): prvSetIPHeaderForICMP
2      34      26   FreeRTOS_UDP_IP.c(73): prvLookupIPInCache
3      15      13   FreeRTOS_UDP_IP.c(290): prvFindIPv4Endpoint
3      43      31   FreeRTOS_UDP_IP.c(148): prvSetIPHeaderForUDP
4      50      33   FreeRTOS_UDP_IP.c(205): prvStartLookup
4      52      43   FreeRTOS_UDP_IP.c(509): prvCallUDPApplicationHook
4      70      51 …

IPv6/multi : lowered the complexity of FreeRTOS_UDP_IP.c

---

portable/BufferManagement/BufferAllocation_2.c

The pxGetNetworkBufferWithDescriptor() documentation states:
If xRequestedSizeBytes is zero then the returned network
buffer descriptor will not reference an Ethernet buffer
(the reference is set to NULL).
But this did not match the implementation. 2 bytes were
unconditionally being added to the requested size, and the
returned NetworkBufferDescriptor_t would have a nonzero
pucEthernetBuffer.
Move the code performing length alignment as is into the
branch checking whether size is nonzero. This lets the
caller request a bare NetworkBufferDescriptor_t to eg.
implement zero copy RX.

BufferAllocation_2: respect 0 length buffer request

---

.github/lexicon.txt
FreeRTOS_ARP.c
include/FreeRTOS_ARP.h
test/cbmc/proofs/ARP/ARPProcessPacket/Configurations.json
test/cbmc/proofs/ARP/ARPRefreshCacheEntry/Configurations.json

Description
-----------
In this PR I have split-up several functions in FreeRTOS_ARP.c
The complexity scores are now between 0 and 8, coming from :
~~~
Score | ln-ct | nc-lns| file-name(line): proc-name
15     114      61   FreeRTOS_ARP.c(80): eARPProcessPacket
37     155      94   FreeRTOS_ARP.c(239): vARPRefreshCacheEntry
total nc-lns      400
~~~
These are the new helper functions:
~~~
static eARPLookupResult_t prvCacheLookup( uint32_t ulAddressToLookup,
MACAddress_t * const pxMACAddress,
NetworkEndPoint_t ** ppxEndPoint );
static void vARPProcessPacketRequest( ARPPacket_t * pxARPFrame,
NetworkEndPoint_t * pxTargetEndPoint,
uint32_t ulSenderProtocolAddress );
static void vARPProcessPacketReply( ARPPacket_t * pxARPFrame,
NetworkEndPoint_t * pxTargetEndPoint,
uint32_t …

IPv6/multi : lowered the complexity of FreeRTOS_ARP.c

---

.github/lexicon.txt
FreeRTOS_DHCP.c
include/FreeRTOS_DHCP.h

Description
-----------
Many DHCP servers keep track of what IP-addresses have been leased to which MAC-address.
Some servers however seem to prefer to give randomly chosen IP-addresses. This PR gives the possibility to indicate a **preferred IP-address**, using DHCP option 50 when asking for an offer.
Test Steps
-----------
I tested the PR as follows:
~~~c
/* Tell DHCP that this device likes to receive the address 192.168.2.136. */
uint32_t ulPreferredIPAddress = FreeRTOS_inet_addr_quick( 192, 168, 2, 136 );
vDHCPSetPreferredIPAddress( ulPreferredIPAddress );
FreeRTOS_IPInit( ucIPAddress, ucNetMask, ucGWAddr, ucDNSAddr, ucMACAddr );
~~~
Related Issue
-----------
Users complain that their DHCP server doesn't seem to memorise leases. See [this …

IPv4/DHCP Let the application indicate a preferred IP-address

---

FreeRTOS_TCP_IP.c

Description
-----------
In the function `prvTCPPrepareSend()`, the variable `lDataLen` denotes the number of bytes in the TCP payload. Only when an error occurs, the variable will get the value `-1`.
At [this point](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/01817db1808d43e05b7e60d6dcd5e1b24ef776f5/FreeRTOS_TCP_IP.c#L2194) however, the test of `lDataLen` is not correct:
~~~c
if( ( lDataLen > 0 ) ||
( pxSocket->u.xTCP.bits.bWinChange != pdFALSE_UNSIGNED ) ||
( pxSocket->u.xTCP.bits.bSendKeepAlive != pdFALSE_UNSIGNED ) )
~~~
In this PR I want to test if `lDataLen` is negative.
Test Steps
-----------
One way to test this is define `ipconfigTCP_KEEP_ALIVE`, and make sure the remote peer becomes unreachable. After a while, `lDataLen` will be set to zero:
~~~c
if( …

Test for negative lDataLen in prvTCPPrepareSend()

---

FreeRTOS_IP.c

Description
-----------
This PR is a follow-up to issue #275: FreeRTOS_IPInit always reports failure when STATIC_ALLOCATION=1. Thanks @sefthyvoulos for reporting this.
To solve this, I propose the following simple change:
~~~c
/* Create the task that processes Ethernet and stack events. */
#if ( configSUPPORT_STATIC_ALLOCATION == 1 )
{
static StaticTask_t xIPTaskBuffer;
static StackType_t xIPTaskStack[ ipconfigIP_TASK_STACK_SIZE_WORDS ];
xIPTaskHandle = xTaskCreateStatic( prvIPTask,
"IP-Task",
ipconfigIP_TASK_STACK_SIZE_WORDS,
NULL,
ipconfigIP_TASK_PRIORITY,
xIPTaskStack,
&xIPTaskBuffer );
+        if( xIPTaskHandle != NULL )
+        {
+            xReturn = pdTRUE;
+        }
}
#else /* if ( configSUPPORT_STATIC_ALLOCATION == 1 ) */
~~~
Test Steps
-----------
Call IPInit() and the …

Let FreeRTOS_IPInit() return success when static allocation is enabled.

---

FreeRTOS_TCP_IP.c

Description
-----------
Currently, the TCP driver will send a first FIN, only when it hasn't been sent yet, i.e. only when `bFinSent` is false:
~~~c
-    if( ( pxSocket->u.xTCP.bits.bCloseRequested != pdFALSE_UNSIGNED ) &&
-        ( pxSocket->u.xTCP.bits.bFinSent == pdFALSE_UNSIGNED ) )
+    if( pxSocket->u.xTCP.bits.bCloseRequested != pdFALSE_UNSIGNED )
~~~
When this packets get lost, it make take a long time before the TCP connection will actually be closed, i.e. only after a time-out.
- The peer doesn't know that we want to close the connection.
- while we assume that the peer has received a FIN flag, and will reply with a FIN flag.
I saw this happening with a Xilinx Zynq, which had its PHY forced to a speed of 100 Mbps in stead of 1 Gbps. There was some loss of outgoing packets, …

When FIN can be sent, send it, also a second or a third time

---

FreeRTOS_TCP_IP.c
include/FreeRTOS_IP.h

Description
-----------
In response to a report on the [FreeRTOS forum](https://forums.freertos.org/t/freertos-tcp-corehttp-connection-reset-from-server-side): "FreeRTOS+TCP coreHTTP connection reset from server side".
A FreeRTOS+TCP device sends a SYN, which is answered twice with an identical SYN+ACK.
[Janis Barscausks](https://forums.freertos.org/u/janis.barscausks) wrote that he has no idea why his Apache server on Ubuntu replied with 2 identical SYN+ACK packets.
Both packets received a correct reply: a pure ACK, which is all good.
But as a side-effect, the second packet carrying SYN+ACK got stored (in `xTCP.xPacket.u.ucLastPacket`), along with the SYN flag. When the device sends the first data, it will also send the SYN flag, which is incorrect.
Test Steps
-----------
I tested by …

When storing the last TCP packet, clear the TCP flags.

---

portable/NetworkInterface/board_family/NetworkInterface.c
portable/NetworkInterface/board_family/ReadMe.txt

Description
-----------
The template file for writing a network interface - https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/portable/NetworkInterface/board_family/NetworkInterface.c - requires instructions to prevent unknowing users from using it as a driver, as is.
Here is an example of someone who attempted to do just that https://forums.freertos.org/t/cant-connect-sockets-to-send-data-with-freertos-tcp/13008/30
Related Issue
-----------
https://forums.freertos.org/t/cant-connect-sockets-to-send-data-with-freertos-tcp/13008/30

Add warning to not use the template version of NetworkInterface.c as is

---

.github/lexicon.txt
FreeRTOS_IP.c
FreeRTOS_TCP_IP.c
include/FreeRTOS_IP_Private.h
test/cbmc/proofs/TCP/prvTCPHandleState/TCPHandleState_harness.c
test/cbmc/proofs/parsing/ProcessReceivedTCPPacket/ProcessReceivedTCPPacket_harness.c

Description
-----------
This PR does the same in the IPv6/multi branch as [PR #238](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/238) did for the IPv4 branch.
Background: the function `FreeRTOS_closesocket()` can fail if the queue to the IP-task is full. A normal task can wait for space, but the IP-task would create a dead-lock by waiting for itself.
This PR has a safe alternative for `FreeRTOS_closesocket()` that can only be used by the IP-task.
Test Steps
-----------
I tested this PR by corrupting the TCP flags of an incoming packet during the SYN phase [around here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/6b332d212df0f25336651b66977cda06e37787c1/FreeRTOS_TCP_IP.c#L3006). That leads to an immediate closure of the socket like this:
~~~c
/* In case pxSocket is not yet …

IPv6/Multi: Let IP-task use vSocketCloseNextTime instead of FreeRTOS_closesocket

---

FreeRTOS_TCP_IP.c

Description
-----------
The macro `ipconfigTCP_ACK_EARLIER_PACKET` was added to allow users to determine if they want to acknowledge earlier packets or not in a TCP connection. But, this is not used except in testing - meaning, that the macro is defined as 1.
This PR removes the macro and the corresponding code where the macro value was `0`.
Not sure why did uncrustify decide to modify the `define` s.
Test Steps
-----------
Related Issue
-----------

Remove unused macro

---

FreeRTOS_Sockets.c
FreeRTOS_TCP_IP.c
include/FreeRTOS_IP_Private.h
test/cbmc/proofs/TCP/prvTCPHandleState/TCPHandleState_harness.c

Description
-----------
This PR removes an extra MSS field (`usCurMSS`) in the TCP sockets since it was always identical to another field (`usInitMSS`). Both of these fields are then replaced by a new field (`usMSS`).
Test Steps
-----------
Related Issue
-----------

Remove extra MSS field from TCP sockets

---

FreeRTOS_IP.c

Description
-----------
Since `configSUPPORT_STATIC_ALLOCATION` was introduced, the functions `FreeRTOS_IPInit()` and `FreeRTOS_IPStart` would always return pdFALSE, which means failure.
Just like in PR #277, I want to correct this for the [IPv6/multi](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/labs/ipv6_multi) branch.
~~~c
#if ( configSUPPORT_STATIC_ALLOCATION == 1 )
static StaticTask_t xIPTaskBuffer;
static StackType_t xIPTaskStack[ ipconfigIP_TASK_STACK_SIZE_WORDS ];
xIPTaskHandle = xTaskCreateStatic( prvIPTask,
"IP-Task",
ipconfigIP_TASK_STACK_SIZE_WORDS,
NULL,
ipconfigIP_TASK_PRIORITY,
xIPTaskStack,
&xIPTaskBuffer );
+    if( xIPTaskHandle != NULL )
+    {
+        xReturn = pdTRUE;
+    }
#else /* if ( configSUPPORT_STATIC_ALLOCATION == 1 ) */
xReturn = xTaskCreate( …

IPv6/Multi: Let FreeRTOS_IPStart() return success when static allocation

---

.github/lexicon.txt
FreeRTOS_TCP_WIN.c

Description
-----------
The module FreeRTOS+TCP_WIN.c had 4 functions with a high score on complexity. I cut down their size by moving some code the helper functions:
lTCPWindowRxCheck()  score 66
- prvTCPWindowRx_ExpectedRX()
- prvTCPWindowRx_UnexpectedRX()
lTCPWindowTxAdd()  score 35
- prvTCPWindowTxAdd_FrontSegment()
ulTCPWindowTxGet()  score 43
- pxTCPWindowTx_GetWaitQueue()
- pxTCPWindowTx_GetTXQueue()
prvTCPWindowTxCheckAck()  score 25
- prvTCPWindowTxCheckAck_CalcSRTT()
Test Steps
-----------
I tested by transferring files in both directions while dropping random packets in both directions.

IPv6/Multi: Reduced complexity FreeRTOS_TCP_WIN.c

---

.github/lexicon.txt
FreeRTOS_DHCPv6.c

Description
-----------
This PR want to reduce the complexity of FreeRTOS_DHCPv6.c.
To following 3 functions now call a helper function:
vDHCPv6Process()  score 29
- xDHCPv6Process_PassReplyToEndPoint()
vDHCPv6ProcessEndPoint()  score 62
- xDHCPv6ProcessEndPoint_HandleState()
- vDHCPv6ProcessEndPoint_HandleReply()
- xDHCPv6ProcessEndPoint_HandleAdvertise()
- vDHCPv6ProcessEndPoint_SendDiscover()
prvDHCPv6Analyse()  score 191
- prvDHCPv6_handleOption()
- prvDHCPv6_subOption()
So in two cases, the helper functions call another helper function.
Test Steps
-----------
I tested the changes by having devices starting up with DHCPv6 enabled and analyse the communication with WireShark.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

IPV6/multi: Reduced complexity FreeRTOS_DHCPv6

---

.github/lexicon.txt
FreeRTOS_Sockets.c

Description
-----------
Also FreeRTOS_Sockets had a few "complex" functions. I already presented a PR #236 on this module: the scores were not very high.
This was the Top-6 of complicated functions, three of them are public API's
FreeRTOS_socket()  score 17
- prvInitialiseTCPFields()
FreeRTOS_recvfrom()  score 12
- prvRecvFrom_CopyPacket()
FreeRTOS_sendto()  score 13
- prvSendTo_ActualSend()
pxTCPSocketLookup()  score 23
- pxTCPSocketLookup_IPv6()
lTCPAddRxdata()  score 27
- vTCPAddRxdata_Callback()
- vTCPAddRxdata_Stored
vTCPNetStat()  score 17
- vTCPNetStat_TCPSocket()

IPv6/Multi: Reduced complexity FreeRTOS_Sockets

---

.github/lexicon.txt
FreeRTOS_TCP_IP.c
include/FreeRTOS_IP_Private.h
test/cbmc/proofs/TCP/prvTCPHandleState/TCPHandleState_harness.c
test/cbmc/proofs/parsing/ProcessReceivedTCPPacket/ProcessReceivedTCPPacket_harness.c

Description
-----------
The module FreeRTOS_TCP_IP.c had three "complex" functions, which will be split-up in smaller parts by adding helper functions:
prvTCPReturnPacket()  score **77**
- prvTCPReturn_SwapAddresses()
- prvTCPReturn_SetChecksum()
- prvTCPReturn_SetEndPoint()
- prvTCPReturn_CheckTCPWindow()
- prvTCPReturn_SetSequenceNumber()
prvTCPStatusAgeCheck() score 5
- prvTCPStatusNeedsCheck()
prvTCPPrepareSend()  score **47**
- prvTCPPrepare_HandleClose()
- prvTCPPrepare_KeepAlive()
xProcessReceivedTCPPacket()  score **58**
- prvProcessReceived_RSTPacket()
Test Steps
-----------
The changes have been tested in real-life operations.

IPv6/Multi: Reduced complexity FreeRTOS_TCP_IP

---

FreeRTOS_TCP_IP.c

Description
-----------
The macro `ipconfigTCP_ACK_EARLIER_PACKET` in FreeRTOS_TCP_IP.c was once added as a testing option. By default it is defined as 1, and that seems to work well for everyone. So now it is time to remove it, just like we did in the earlier PR #289. In that PR you will find more information about the macro.
Test Steps
-----------
I passed the regular tests with TCP, such as IPERF.
Related Issue
-----------
This PR doesn't have the intention to solve an issue.

IPv6/Multi: Remove unused macro from FreeRTOS_TCP_IP.c

---

.github/lexicon.txt
FreeRTOS_DNS.c
FreeRTOS_Sockets.c
include/FreeRTOS_DNS.h
test/cbmc/proofs/DNS/DNSHandlePacket/DNShandlePacket_harness.c
test/cbmc/proofs/DNS/DNSgetHostByName/DNSgetHostByName_harness.c
test/cbmc/proofs/DNS/DNSgetHostByName_a/DNSgetHostByName_a_harness.c
test/cbmc/proofs/DNS/DNSlookup/DNSlookup_harness.c
test/cbmc/proofs/DNS/DNSlookup/Makefile.json
test/cbmc/proofs/parsing/ProcessReceivedUDPPacket/ProcessReceivedUDPPacket_harness.c

Description
-----------
In FreeRTOS_DNS.c, I found 3 large and complex functions. Again, I isolated some code in static helper functions:
prvPrepareLookup()  score 57
- prvPrepare_ReadIPAddress()
- prvPrepare_CacheLookup()
prvGetHostByName()  score 71
- prvGetDNSAddress()
prvParseDNSReply()  score **507 (!)**
- prvParseDNS_ReadQuestions()
- prvParseDNS_ReadAnswers()
- prvParseDNS_StoreAnswer()
- prvParseDNS_StoreToCache()
- prvParseDNS_HandleLLMNRRequest()
The last function `prvParseDNSReply()` received 5 helper functions.
The difficulty with DNS is that it contains 3 name service protocols, and also it has a call-back system, that allows for asynchronous look-ups.
Test Steps
-----------
I tested the changes by doing many look-ups, both synchronous, and asynchronous. Also I tested the …

IPv6/multi: Reduced complexity FreeRTOS_DNS.c

---

.github/lexicon.txt
FreeRTOS_DHCP.c
include/FreeRTOS_DHCP.h
test/cbmc/proofs/ProcessDHCPReplies/Makefile.json

Description
-----------
The IPv4 version of DHCP also had a few fairly complex functions. 
vDHCPProcessEndPoint()  score 104
- xHandleWaitingOffer()
- vHandleWaitingAcknowledge()
- xHandleWaitingFirstDiscover()
- prvHandleWaitingeLeasedAddress()
prvProcessDHCPReplies()  score **269**
- vProcessHandleOption()
- xProcessCheckOption()
After the PR, the scores will be about 17. I think it doesn't help clarity if we break them down further into smaller parts.
Test Steps
-----------
I tested the changes by running DHCP.

IPv6/Multi: Reduced complexity FreeRTOS_DHCP

---

FreeRTOS_Sockets.c
FreeRTOS_TCP_IP.c
include/FreeRTOS_IP_Private.h
test/cbmc/proofs/TCP/prvTCPHandleState/TCPHandleState_harness.c

Description
-----------
This PR is a second version of #294. I closed that one because it had conflicts with other PR's.
Just like we did recently in #288, this PR ( based on [IPv6/multi](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/labs/ipv6_multi) ) will replace two fields with a single one:
~~~c
-    uint16_t usCurMSS;        /**< Current Maximum Segment Size */
-    uint16_t usInitMSS;       /**< Initial maximum segment Size */
+    uint16_t usMSS;           /**< The Maximum Segment Size for the current connection. */
~~~
The fields are entirely private to the library, just like all contents of a socket structure.
They can be joined because in fact they always have the same value.
Test Steps
-----------
I tested the changes by running IPERF with a varying value for …

IPv6/Multi: Remove extra MSS field from TCP sockets, version 2

---

FreeRTOS_ARP.c

Description
-----------
As Aniruddha is preparing PR #318: "Send ARP requests for unknown IP address requests", I am testing the ARP behaviour. I found that since PR #254, ARP would still work, except that the table got full with double entries.
Cause: the function `vARPRefreshCacheEntry()` had a **return statement** in the middle of the function, along with a text warning. When I moved this code to a separate function, the meaning of the return changed of course. That is now repaired.
Lesson to learn: let functions always have a single point of exit.
Test Steps
-----------
Call the function `FreeRTOS_PrintARPCache()` to see the entire contents of the ARP caching table.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

IPv6/multi: A small reparation to vARPRefreshCacheEntry()

---

portable/NetworkInterface/STM32Hxx/NetworkInterface.c

Description
-----------
A user on the FreeRTOS forum [Dweb_2](https://forums.freertos.org/u/Dweb_2) reported problems with the STM32Hx driver in [this post](https://forums.freertos.org/t/handling-of-disconnects-by-the-network-stack/13322). As soon as the Link Status drops, the driver would run out of network buffers.
This PR will do two things:
1) `xNetworkInterfaceOutput()` will check if the Link Status is high before sending a packet
2) As soon as the Link Status changes, the driver will do the necessary initialisations.
Test Steps
-----------
- Run the STM32Hx and communicate.
- Unplug the device for e.g. 30 seconds
- Reconnect the device
PS. I do recommend to enable ZERO copy for this driver:
~~~c
#define ipconfigZERO_COPY_RX_DRIVER   1
#define ipconfigZERO_COPY_TX_DRIVER   1
~~~
By …

IPv4: STM32Hx driver: check Link Status before sending data.

---

test/unit-test/README.md

Description
-----------
When I tried to run the unit-tests in my Ubuntu, it showed many errors during compilation and during linking. Then I wondered why unit-testing works well when we submit a PR, so I started looking in [ci.yml](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/56ee41a395f6751793a77c6ce60d61eff0c5eba0/.github/workflows/ci.yml#L11).
When I followed those steps, all worked as expected.
Test Steps
-----------
Copy the suggested bash code to a batch file, and run it from the root directory of the repo.
Or use this script: [run_unit_tests.zip](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/files/7111195/run_unit_tests.zip)

Adapt the readme.MD for unit-testing

---

.github/lexicon.txt
FreeRTOS_RA.c
include/FreeRTOS_DHCPv6.h
test/build-combination/AllEnable/FreeRTOSIPConfig.h
test/build-combination/Common/main.c

Description
-----------
In a recent PR ( #281 ), I moved the type declaration `DHCPOptionSet_t` from the C-file to the header file. I forgot to upload `include/FreeRTOS_DHCPv6.h`.
This didn't trigger an error during the test-build because `ipconfigUSE_DHCPv6` was not enabled. This PR will add 7 more macros that enable features:
~~~c
/* Optimisation that allows more than one
* Rx buffer to be passed to the TCP task
* at a time - requires driver support. */
#define ipconfigUSE_LINKED_RX_MESSAGES           ( 1 )
/* Adds IPv6. */
#define ipconfigUSE_IPv6                         ( 1 )
/* Adds a DHCP client for IPv6. */
#define ipconfigUSE_DHCPv6                       ( 1 )
/* Enables a client for Router Advertisement. */
#define ipconfigUSE_RA                           ( 1 )
/* Enables …

IPv6/multi: update FreeRTOS_DHCPv6.h to include 'DHCPOptionSet_t'.

---

FreeRTOS_ARP.c
include/IPTraceMacroDefaults.h
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c

Description
-----------
This PR make the same change as PR #322 , except that here it is applied to the main IPv4 branch.
The actual change: 
~~~
eFrameProcessingResult_t eARPProcessPacket( ARPPacket_t * const pxARPFrame )
{
+    if( ( pxARPHeader->usHardwareType == ipARP_HARDWARE_TYPE_ETHERNET ) &&
+        ( pxARPHeader->usProtocolType == ipARP_PROTOCOL_TYPE ) &&
+        ( pxARPHeader->ucHardwareAddressLength == ipMAC_ADDRESS_LENGTH_BYTES ) &&
+        ( pxARPHeader->ucProtocolAddressLength == ipIP_ADDRESS_LENGTH_BYTES ) )
+    {
/* Process the ARP packet. */
+    }
+    else
+    {
+        iptraceDROPPED_INVALID_ARP_PACKET( pxARPHeader );
+    }
}
~~~
In toher words: before processing an ARP packet, the type- and length-fields are being checked on their validity.
Test Steps …

IPv4: Add length and type checks in ARP packet processing

---

FreeRTOS_Sockets.c

Description
-----------
This PR does the same as PR #316, it allows that `FreeRTOS_send()` is called with a NULL pointer. It is aimed at the IPv6/multi branch.
Test Steps
-----------
Please see PR #316.

IPv6/multi: Allow FreeRTOS_send being called with a NULL pointer

---

FreeRTOS_IP.c
test/cbmc/proofs/parsing/ProcessIPPacket/Configurations.json

Description
-----------
This PR does the same as the earlier #310, except that this PR is aiming at the IPv4 branch.
Description copied from mentioned PR:
According to RFC 1122 section 3.3.6, link level only broadcast packets should be discarded. This PR adds functionality to check and discard such packets.
Link level only broadcast means that the Ethernet address is set to broadcast (FF:FF:FF:FF:FF:FF) whereas the IP address is not a broadcast address (of type x.x.x.255) - it is a directed address.

IPv4: ignore link-level only broadcast

---

FreeRTOS_Sockets.c

Description
-----------
The TCP function `FreeRTOS_send()` takes a pointer `pvBuffer`, which points to the data to be send.
However, when this pointer is NULL, the idea was to update only the head of the transmission stream buffer, i.e. the **zero-copy method**.
~~~c
size_t uxLength, uxRead;
uint8_t * pucBuffer = FreeRTOS_get_tx_head( xSocket, &( uxLength ) );
if( pucBuffer != NULL )
{
uxRead = read_from_disk( pucBuffer, uxLength );
if( uxRead > 0U )
{
FreeRTOS_send( xSocket, NULL, uxLength, 0 );
}
}
~~~
The above methods used to work well, however after a certain PR, the function would treat NULL as an error.
Test Steps
-----------
The [FTP server](https://github.com/htibosch/freertos_plus_projects/tree/master/plus/Framework/FreeRTOS-Plus-TCP/protocols) that I wrote uses this zero-copy …

Allow FreeRTOS_send being called with a NULL pointer

---

FreeRTOS_IP.c

Description
-----------
This is an old typo, `.ulReloadTime` should have been `.ulRemainingTime`.
~~~c
if( xARPTimer.bActive != pdFALSE_UNSIGNED )
{
if( xARPTimer.ulRemainingTime < xMaximumSleepTime )
{
-        xMaximumSleepTime = xARPTimer.ulReloadTime;
+        xMaximumSleepTime = xARPTimer.ulRemainingTime;
}
}
~~~
The code here above is in `prvCalculateSleepTime()`. The function looks for the timer that has the lowest `.ulRemainingTime`.
As a result of the typo, the ARP checking was sometimes done a bit later than planned.

IPv6/multi: use xARPTimer.ulRemainingTime, not .ulReloadTime

---

FreeRTOS_IP.c

Description
-----------
This PR is similar to # #340, except that this PR is aiming at the main branch, not IPv6/multi.
It repairs an old typo, `.ulReloadTime` should have been `.ulRemainingTime`.
~~~c
if( xARPTimer.bActive != pdFALSE_UNSIGNED )
{
if( xARPTimer.ulRemainingTime < xMaximumSleepTime )
{
-        xMaximumSleepTime = xARPTimer.ulReloadTime;
+        xMaximumSleepTime = xARPTimer.ulRemainingTime;
}
}
~~~

IPv4/single: use xARPTimer.ulRemainingTime, not .ulReloadTime

---

.github/lexicon.txt
FreeRTOS_ARP.c

Description
-----------
When the function `vARPRefreshCacheEntry()` has found a perfect entry, it will return in the middle of the function. This may lead to mistakes and errors. See #319 where it caused an error.
Test Steps
-----------
I tested this PR in the same way as I tested #319, in real hardware.

IPv4: ARP Remove a return statement from the function vARPRefreshCacheEntry()

---

.github/lexicon.txt
FreeRTOS_Sockets.c
include/FreeRTOS_Sockets.h

Description
-----------
It is a copy of #342, except that this PR is aiming at the IPv4 main branch.It adds two functions:
~~~c
/** @brief This funtion converts a 48-bit MAC address to a human readable string. */
void FreeRTOS_EUI48_ntop( const uint8_t * pucSource,
char * pcTarget,
char cTen,
char cSeparator );
/** @brief This funtion converts a human readable string, representing an 48-bit MAC address,
* into a 6-byte address. Valid inputs are e.g. "62:48:5:83:A0:b2" and "0-12-34-fe-dc-ba". */
BaseType_t FreeRTOS_EUI48_pton( const char * pcSource,
uint8_t * pucTarget );
~~~

IPv4/single: Adding EUI48_pton and EUI48_ntop for MAC address conversion

---

portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.c

Description
-----------
The STM32Hxx EMAC has 10 counters that generate an interrupt when they are half-full or full. These interrupts by default.
Test Steps
-----------
With the following instructions, all counters are given a value of almost half-full:
~~~c
ETH->MMCCR &= ~( ETH_MMCCR_CNTPRSTLVL );
ETH->MMCCR |= ETH_MMCCR_CNTPRST;
~~~
Ping the device and one counter ( `ETH->MMCRUPGR` ) will trigger an interrupt that is not reset, unless this PR is applied.
Related Issue
-----------

IPv4/single: disable counter interrupts in the STM32Hxx driver

---

.github/lexicon.txt
FreeRTOS_ARP.c
FreeRTOS_DHCP.c
FreeRTOS_DNS.c
FreeRTOS_IP.c
FreeRTOS_Sockets.c
FreeRTOS_Stream_Buffer.c
FreeRTOS_TCP_IP.c
FreeRTOS_TCP_WIN.c
FreeRTOS_UDP_IP.c
include/FreeRTOSIPConfigDefaults.h
include/FreeRTOS_DNS.h
include/FreeRTOS_IP.h
include/FreeRTOS_IP_Private.h
include/FreeRTOS_Sockets.h
include/FreeRTOS_TCP_WIN.h
portable/NetworkInterface/DriverSAM/NetworkInterface.c
test/cbmc/proofs/CheckOptionsInner/CheckOptionsInner_harness.c
test/cbmc/proofs/Socket/vSocketBind/ALLOW_ETHERNET_DRIVER_FILTERS_PACKETS/vSocketBind_harness.c
test/cbmc/proofs/Socket/vSocketBind/ALLOW_SOCKET_SEND_WITHOUT_BIND/vSocketBind_harness.c
test/cbmc/proofs/Socket/vSocketBind/DONT_ALLOW_SOCKET_SEND_WITHOUT_BIND/vSocketBind_harness.c
test/cbmc/proofs/Socket/vSocketClose/vSocketClose_harness.c
test/cbmc/proofs/TCPWin/vTCPWindowDestroy/vTCPWindowDestroy_harness.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_stubs.c
test/unit-test/FreeRTOS_Stream_Buffer/FreeRTOS_Stream_Buffer_utest.c

I just submitted 9 PR's that make the source code conform the MISRA rules. It was very complex to create these PR's because the sources are strongly interwoven.
For instance, I added a function `FreeRTOS_max_size_t()` in FreeRTOS+IP.c, which is used in several modules.
I just collected all individual PR's and gathered them into one complete branch called: [IPv4_single_MISRA_all_sources](https://github.com/htibosch/FreeRTOS-Plus-TCP/tree/IPv4_single_MISRA_all_sources)
I propose to use the individual PR's for discussion, and this complete PR to merge with the [main branch](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP).
Also it would be impossible to do testes with the individual PR's as none of them has the complete new sources.
By submitting this pull request, I confirm that you can use, …

IPv4/single: keep all sources MISRA compliant

---

portable/NetworkInterface/STM32Fxx/readme.txt

Description
-----------
Recently, in PR #369, some text was added to the readme.txt file of the STM32Fxx driver. The recommendation was OK, but it was not in line with the way in which the STM32 HAL should be configured.
This PR will explain how to use and configure the HAL properly, i.e. by using the HAL configuration file, e.g. `stm32f4xx_hal_conf.h`.
**EDIT** : also I learned that a PR can be put into DRAFT mode, which will prevent to from getting merged prematurely :-)

IPv4/single: Added text to readme.txt for the STM32Fxx driver

---

FreeRTOS_ARP.c
FreeRTOS_IP.c
FreeRTOS_TCP_IP.c
FreeRTOS_UDP_IP.c
include/FreeRTOSIPConfigDefaults.h
test/cbmc/proofs/ARP/ARP_FreeRTOS_OutputARPRequest/OutputARPRequest_harness.c
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/OutputARPRequest_harness.c

Description
-----------
The macro `ipconfigETHERNET_MINIMUM_PACKET_BYTES` determines the minimum size of outgoing packets. When the device is operating on a LAN, it is good to give it a value of 60. Four bytes will later be added as the Ethernet checksum.
Until now, the macro was undefined by default. Therefore, it was not mentioned in the header file `FreeRTOSIPConfigDefaults.h`.
This PR will define the macro as zero, and this change will be made:
~~~c
-    #ifdef ipconfigETHERNET_MINIMUM_PACKET_BYTES
+    #if( ipconfigETHERNET_MINIMUM_PACKET_BYTES > 0 )
~~~
At the same time the macro will be documented on the TCP configuration pages on [freertos.org](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/TCP_IP_Configuration.html)
By submitting this pull request, I confirm that you …

IPv4/single: Assign proper default value to macro

---

portable/NetworkInterface/Common/phyHandling.c

Just a misleading mistype in FreeRTOS_printf xPhyStartAutoNegotiation: phyBMSR_AN_COMPLETE

Mistype in FreeRTOS_printf xPhyStartAutoNegotiation: phyBMSR_AN_COMPLETE

---

FreeRTOS_TCP_WIN.c
include/FreeRTOSIPConfigDefaults.h

Description
-----------
When TCP sends a packet, it will wait some time for an ACK. It will also measure how long it normally takes before a peer responds. That time is called Smoothed Round Trip Time (SRTT).
In FreeRTOS_TCP_WIN.c the value will capped at `winSRTT_CAP_mS`, which had a value of 50 ms. That can be OK when talking to other real-time peers, but a host may often delay sending an ACK for 200 ms.
A developer [nlangenb](https://forums.freertos.org/u/nlangenb) saw unnecessary [resends of packets](https://forums.freertos.org/t/freertos-tcp-retransmission-timer-incorrect). That can be solved by waiting at lease 1000 ms. THis small PR makes that possible.
Actually, a good minimum would be 1000, but as we never want to disrupt existing applications, the default will still be 50 ms.
By …

IPv4/single: TCP minimum time for retransmissions

---

test/cbmc/proofs/run-cbmc-proofs.py

This patch ensures that the prepare script is always run before the cbmc proofs are run.

Always prepare source tree for cbmc proofs

---

include/FreeRTOSIPConfigDefaults.h

Fix comparison of integer expressions of different signedness
Description
-----------
When compiling with `-Werror=sign-compare` flag and with the default config values (`FreeRTOSIPConfigDefaults.h`) the integer comparison of different signedness in [`FreeRTOS_TCP_WIN.c:1874`](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/b6eac0ca7df8c8935cb840fd9642f6533a0da2e6/FreeRTOS_TCP_WIN.c#L1874) leads to an error, because [`winSRTT_CAP_mS`](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/b6eac0ca7df8c8935cb840fd9642f6533a0da2e6/FreeRTOS_TCP_WIN.c#L57) evaluates to [`50U`](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/b6eac0ca7df8c8935cb840fd9642f6533a0da2e6/include/FreeRTOSIPConfigDefaults.h#L383).
This PR removes the unsigned literal.
Test Steps
-----------
Compile with …

Fix comparison of integer expressions of different signedness

---

FreeRTOS_Sockets.c

Fix FreeRTOS_closesocket when callbacks are enabled and TCP is disabled
Changed pxSocket definition boolean logic from && to || otherwise pxSocket is undefined when clearing the UDP handlers.

Fix FreeRTOS_closesocket when callbacks are enabled and TCP is disabled

---

.github/lexicon.txt
include/FreeRTOSIPConfigDefaults.h

Description
-----------
Added many inline comments to the header file 'FreeRTOSIPConfigDefaults.h'
More complete documentation can be found on [freertos.org](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/TCP_IP_Configuration.html), which will be updated soon.
I left the definitions exactly as they were, not changing any value. I did reorder some items, to keep similar macros together as a group: ARP, ICMP, DHCP, DNS etc.

IPv4/single: added comments to FreeRTOSIPConfigDefaults.h

---

.github/lexicon.txt
FreeRTOS_IP.c
FreeRTOS_Sockets.c
FreeRTOS_TCP_IP.c
FreeRTOS_TCP_WIN.c
include/FreeRTOS_Sockets.h
include/FreeRTOS_TCP_WIN.h

Description
-----------
When using UDP, it is possible to receive data without first copying it. In that case it will return a pointer to a network buffer.
This is the way it works:
~~~c
struct freertos_sockaddr xAddress;
socklen_t uxAddrLen = sizeof xAddress;
uint8_t *pucBuffer = NULL;
BaseType_t xLength = FreeRTOS_recvfrom( xSocket, &( pucBuffer ), 0, FREERTOS_ZERO_COPY, &( xAddress ), &( uxAddrLen ) );
if( xLength > 0 )
{
/* Use the contents of 'pucBuffer'. */
/* Release the network buffer that contains 'pucBuffer'. */
FreeRTOS_ReleaseUDPPayloadBuffer( pucBuffer );
}
~~~
For TCP sockets, it is possible to peek into the circular reception buffer without copying it. When done, the pointer in the reception buffer must be advanced to mark the data as "read".
Recently, a user Matt Boytim on …

IPv4/single: TCP handles partial segments.

---

portable/NetworkInterface/xilinx_ultrascale/uncached_memory.c
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_dma.c

Description
-----------
Previously the Port only worked for the A53 in 64-bit mode. With these changes the stack is also working for the Cortex R5 as long as the nicUSE_UNCACHED_MEMORY option is off.
With nicUSE_UNCACHED_MEMORY enabled the R5 runs into an exception.
ARP and ping work. I tested a lot of UDP steaming and everything seems to work fine. I did not test TCP.
Test Steps
-----------
Related Issue
-----------

Extend the Zynq Ultrascale port for the Cortex R5

---

.github/workflows/ci.yml
.github/workflows/uncrustify.yml
test/unit-test/catch_assert.h

Description
-----------
Uncrustify was trying to parse catch_assert.h as a CPP file wherein `try` and `catch` are [keywords](https://en.cppreference.com/w/cpp/language/try_catch).
This PR updates the variable names and also updates the file `ci.yml` to not ignore `catch_assert.h` anymore.
Test Steps
-----------
Related Issue
-----------

Update variable in catch_assert file to allow uncrustify-ing

---

.github/workflows/ci.yml
test/unit-test/catch_assert.h

Description
-----------
See PR https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/419 for the change in main branch.
Uncrustify was trying to parse catch_assert.h as a CPP file wherein `try` and `catch` are [keywords](https://en.cppreference.com/w/cpp/language/try_catch).
This PR updates the variable names and also updates the file `ci.yml` to not ignore `catch_assert.h` anymore.
Test Steps
-----------
Related Issue
-----------

[Testing]: Update variable in catch_assert file to allow uncrustify-ing

---

portable/NetworkInterface/xilinx_ultrascale/NetworkInterface.c
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif.h
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_dma.c
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_physpeed.c

Make the Ultrascale port more versatile.
Description
-----------
The first commit replaces calls of the Xilinx function xil_printf() with the generic FreeRTOS_printf(). This is exactly how prints are done in the Zynq7000 port. This allows the developer to implement an arbitrary debug output independent of Xilinx drivers.
The second commit detects if the requested MTU requires Jumbo Frames and enables Jumbo Frame support if necessary. The use of large MTU's (and thus Jumbo Frames) can significantly reduce the CPU load as well as reduce the number of packets lost.
Test Steps
-----------
The Jumbo Frames worked fine using UDP up to a packet size of 7KB. However, for bigger packets it did not work.
I still think that it is worth merging because using Jumbo frames allowed me to double my …

Make Ultrascale port more generic and add Jumbo Frame support

---

FreeRTOS_Sockets.c

Make WAKEUP_CALLBACK and SET_SEMAPHORE accessible when TCP is disabled
These options were not available to UDP in setsockopt when TCP is disabled. UDP should call wakeup callback after a bind event.

Make WAKEUP_CALLBACK and SET_SEMAPHORE accessible when TCP is disabled

---

FreeRTOS_UDP_IP.c
test/unit-test/FreeRTOS_UDP_IP/FreeRTOS_UDP_IP_utest.c

Description
-----------
This PR addresses [issue 414](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/414) raised by @RuStrannik.
In his projects he calls `FreeRTOS_IPInit()` with zero's for all of the IP-addresses and netmask. That worked fine, until PR #338 was submitted: "Send ARP packets for unknown IP addresses". That PR made sure that the IP-addresses of incoming packets are verified by looking it up using ARP.
With the current PR, the ARP verification will be only be done after DHCP has set a proper IP-address and netmask.
Test Steps
-----------
Set `ipconfigUSE_DHCP` to 1 in your FreeRTOSIPConfig.h
Initialise the IP-stack as show in the issue:
~~~c
const uint8_t addr[4] = { 0, 0, 0, 0 };
FreeRTOS_IPInit(addr, addr, addr, addr, ucMacAddress);
~~~
Now boot the device with or …

No ARP verification during DHCP phase

---

.github/lexicon.txt
FreeRTOS_Sockets.c
include/FreeRTOS_Sockets.h

Description
-----------
In the Berkeley Socket API, a protocol argument of 0 indicates to the socket layer that it should pick a sensible default protocol. 
I simply added a check to `FreeRTOS_socket()` that catches an `xProtocol` of zero and sets it to an appropriate value based off the `xType` argument. Nothing fancy.
Test Steps
-----------
Call `FreeRTOS_socket(FREERTOS_AF_INET, FREERTOS_SOCK_DGRAM, 0)`. It will return `FREERTOS_INVALID_SOCKET`, whereas the equivalent Berkeley socket call would succeed.

Handle zero protocol argument in FreeRTOS_socket()

---

portable/NetworkInterface/xilinx_ultrascale/NetworkInterface.c
portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_physpeed.c

Description
-----------
This PR changes the NetworkInterface.c for Xilinx UltraScale.
The initialisation is now divided in several stages:
~~~c
typedef enum xEMAC_STATE
{
xEMAC_Init,      /* Initialise the EMAC. */
xEMAC_SetupPHY,  /* Detect and initialise the PHY. May be called repeatedly. */
xEMAC_WaitPHY,   /* Wait for the PHY to report a Link Status and a speed. */
xEMAC_Ready,     /* The EMAC is initialised and the Link Status is high. */
xEMAC_Fatal      /* A fatal error has occurred. */
} EMACState_t;
~~~
When the LAN is connected, it will only be called once and pass all states up to `xEMAC_Ready`.
When the LAN is disconnected, it will stay in `xEMAC_SetupPHY` until the speed is known and the Link Status goes high.
Test Steps
-----------
Start the DUT with a LAN, and then start it …

Check the result of Phy_Setup_US before continuing

---

include/FreeRTOSIPConfigDefaults.h

Description
-----------
A summary of the changes:
~~~diff
-#if ( ipconfigUSE_DHCPv6 != 0 )
+#if ( ipconfigUSE_IPv6 != 0 )
#define ipconfigTCP_MSS    ( ipconfigNETWORK_MTU - ( ipSIZE_OF_IPv6_HEADER + ipSIZE_OF_TCP_HEADER ) )
#else
#define ipconfigTCP_MSS    ( ipconfigNETWORK_MTU - ( ipSIZE_OF_IPv4_HEADER + ipSIZE_OF_TCP_HEADER ) )
#endif
~~~
In other words: I corrected a copy/paste error.
When MTU equals 1500, the maximum MSS for IPv6 is 1440 bytes. For IPv4, that would be 1460 bytes.
Test Steps
-----------
Make a TCP v6 connection with a device on the LAN and look at the MSS value.
Related Issue
-----------
Depending on the configuration, the received TCP packets could become larger than the defined MTU value.
When the peer device has the same MTU, or in case `ipconfigUSE_DHCPv6` was …

Let 'ipconfigTCP_MSS' depend on the macro 'ipconfigUSE_IPv6'

---

portable/NetworkInterface/Common/phyHandling.c
portable/NetworkInterface/include/phyHandling.h

Description
-----------
Support the [KSZ8795](https://www.microchip.com/en-us/product/KSZ8795) switch in the phyHandling driver.
Driver's MIIM interface phyAddress for the 4 ports starts at 0x1 instead of 0x0. 
Test Steps
-----------
Connected to the MIIM interface of a KSZ8795 switch.
Related Issue
-----------
N/A

Support the KSZ8795 phy in the phyHandling driver.

---

portable/Compiler/CCS/pack_struct_end.h
portable/Compiler/CCS/pack_struct_start.h
portable/NetworkInterface/TM4C/TM4C-README.md

Supress spurious warnings from the CCS compiler
Description
-----------
Fixes warnings when building with CCS:
`error #1916-D: definition at end of file not followed by a semicolon or a declarator`
Test Steps
-----------
Compile a project with this fix, and the warning should go away
Related Issue
-----------
N/A

Suppress spurious warnings from the CCS compiler

---

FreeRTOS_Sockets.c
FreeRTOS_TCP_IP.c

Description
-----------
Prevents this warning from the TI CCS compiler:
warning #190-D: enumerated type mixed with another type
I haven't seen this warning from other compilers, but it seems like a good idea regardless to signal that this conversion is OK and expected. Explicit casts are already being used for the opposite conversion.
This and #444 should be sufficient to compile the library without warnings with TI's compiler, with one exception which I will create an issue for because I don't know the library well enough to resolve it
Test Steps
-----------
None
Related Issue
-----------
N/A

Make conversions from uint8 to eIPTCPState_t explicit

---

FreeRTOS_DNS.c
FreeRTOS_DNS_Cache.c

Description
-----------
This PR updates the FreeRTOS_DNS_Cache.c file to ignore all the functions from compiling when DNS caching is disabled.
Test Steps
-----------
Related Issue
-----------

Update functions covered by #ifs

---

portable/NetworkInterface/STM32Fxx/NetworkInterface.c

Description
-----------
In a recent PR #442, I changed `prvMACAddressConfig()` to only allow multicast addresses:
~~~diff
static void prvMACAddressConfig( ETH_HandleTypeDef * heth,
uint32_t ulIndex,
uint8_t * Addr )
{
/* Check the multicast bit. */
+    if( ( Addr[ 0 ] & 1U ) == 0U )
+    {
/* Calculate the selected MAC address high register. */
ulTempReg = 0x80000000ul | ( ( uint32_t ) Addr[ 5 ] << 8 ) | ( uint32_t ) Addr[ 4 ];
...
+    }
}
~~~
The test was incorrect, a multicast address can be recognised when the lowest bit of the first byte is a `1`.
But as the function of `prvMACAddressConfig()` is to add any type of Ethernet address, I think it is better to leave out the multicast test.
Test Steps
-----------
Apply PR #442, and enabled LLMNR.
Related Issue
-----------
The DUT won't …

IPv4/Single: STM32 remove multicast test

---

portable/NetworkInterface/STM32Fxx/NetworkInterface.c

Description
-----------
When using IPv6, many multicast addresses will be used. Therefore, I added this code:
~~~c
#if ( ipconfigMULTI_INTERFACE != 0 ) && ( ipconfigUSE_IPv6 != 0 )
/* IPv6 needs several multicast addresses.
* Disable filtering multicast until a better method is implemented.
*/
macinit.MulticastFramesFilter = ETH_MULTICASTFRAMESFILTER_NONE;
#else
macinit.MulticastFramesFilter = ETH_MULTICASTFRAMESFILTER_PERFECT;
#endif
~~~
which allows the reception of any multicast address. Because of this setting, it did not become clear that `prvMACAddressConfig()` in NetworkInterface.c has a wrong test:
~~~c
static void prvMACAddressConfig( ETH_HandleTypeDef * heth,
uint32_t ulIndex,
uint8_t * Addr )
{
/* Check the multicast bit. */
if( ( Addr[ 0 ] & 1U ) == 0U )
{
/* Calculate the …

IPv6/Multi: STM32 remove multicast test

---

portable/NetworkInterface/STM32Fxx/NetworkInterface.c

Description
-----------
In response to [issue 457](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/457): "In STM32Fxx ethernet driver - race condition in RX check"
In the STM32Fxx network interface, a global volatile variable `ulISREvents` was used to pass events from the network ISR to the EMAC task.
Thank you @pavel-a for bringing this to our attention. I knew it had to be revised... when there is time. Today I took the time for it:
I changed the code and tested it on an STM32F765.

IPv4/Single : STM32Fxx use task notify in a proper way

---

portable/NetworkInterface/STM32Fxx/NetworkInterface.c

Description
-----------
This is the IPv6/Multi version of PR #458.
In response to [issue 457](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/457): "In STM32Fxx ethernet driver - race condition in RX check"
In the STM32Fxx network interface, a global volatile variable `ulISREvents` was used to pass events from the network ISR to the EMAC task.
Thank you @pavel-a for bringing this to our attention.
I changed the code and tested it on an STM32F765, also with IPv6 sockets.

IPv6/Multi : STM32Fxx use task notify in a proper way

---

include/FreeRTOSIPConfigDefaults.h

Description
-----------
As pointed out by @holden-zenith in https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/456, there is some reordering required in FreeRTOSIPConfigDefaults.h to allow the code to compile even in absence of user provided definitions.
This PR modifies the file to that extent.
Test Steps
-----------
Related Issue
-----------

IPv6/multi: Update FreeRTOSIPConfigDefaults.h

---

include/FreeRTOSIPConfigDefaults.h

Description
-----------
As pointed out by @holden-zenith in https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/456, there is some reordering required in FreeRTOSIPConfigDefaults.h to allow the code to compile even in absence of user provided definitions.
This PR modifies the file to that extent.
Test Steps
-----------
Related Issue
-----------

IPv4/single: Update FreeRTOSIPConfigDefaults.h

---

.github/workflows/ci.yml
source/FreeRTOS_DNS.c
source/include/FreeRTOS_DNS_Globals.h
test/Coverity/CMakeLists.txt
test/build-combination/CMakeLists.txt
test/build-combination/Common/main.c
test/build-combination/DefaultConf/FreeRTOSIPConfig.h

Description
-----------
This PR add the following:
- A coverage check to ensure that the unit-test coverage never drops below 100%
- A build combination test which works with the default configuration provided in `FreeRTOSIPConfigDefaults.h`. This should catch any errors related to new configuration macros.
Test Steps
-----------
Related Issue
-----------

Add coverage check and default build combo test

---

source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c

Description
-----------
This PR was originally created by @htibosch. I am rebasing his PR and closing the original one: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/465
This PR is in response to [an issue](https://forums.freertos.org/t/freertos-tcp-with-no-phy/14533/6) reported on the FreeRTOS forum.
The function `HAL_ETH_Init()` checks if the PHY hardware is OK. The result of the function was not checked, which may result in a crash.
[Dweb_2](https://forums.freertos.org/u/Dweb_2), thank you for reporting this.
Test Steps
-----------
It is difficult to reproduce without changing the hardware.

IPv4/single: STM32H7xx driver check result of HAL_ETH_Init

---

.github/lexicon.txt
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Timers.c
source/include/FreeRTOS_IP_Timers.h
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP_Timers/FreeRTOS_IP_Timers_utest.c

Description
-----------
The timer `xTCPTimer` is a timer that tells when the TCP engine must become active by calling `xTCPTimerCheck()`. In some occasions, the timer is forced to expire, for instance when `recv()` was called and created enough space in the reception stream: a WIN update shall be sent immediately.
However, after a certain commit to the branch `IntegrationTesting1`, the TCP timer was set as **enabled**, instead of **expired**.
This PR makes the following change:
~~~diff
-void vIPSetTCPTimerEnableState( BaseType_t xEnableState );
+void vIPSetTCPTimerExpiredState( BaseType_t xEnableState );
~~~
and
~~~diff
+        xTCPTimer.bActive = pdTRUE_UNSIGNED;
if( xEnableState != pdFALSE )
{
-            xTCPTimer.bActive = pdTRUE_UNSIGNED;
+            xTCPTimer.bExpired = …

Let the TCP timer becomes expired in stead of active

---

tools/coverity_misra.config

Misra: global disable Rule 3.1
Description
-----------
Misra: global disable Rule 3.1 
embedding // inside of /* */ comments as we post links inside some comment blocks

Misra: global disable Rule 3.1

---

tools/coverity_misra.config

misra supress rule 2.5
Description
-----------
misra supress rule 2.5
as some macros are coming from FreeRTOS
and some macros are there as an implementation for the protocols
and some are still there for backward compatibility
Test Steps
-----------
Related Issue
-----------

misra supress rule 2.5

---

source/FreeRTOS_IP_Utils.c

MISRA: Supress misra rule 21.6
Description
-----------
Suppress MISRA rule 21.6 as the use or snprintf is for logging purposes only

MISRA: Supress  rule 21.6

---

source/include/FreeRTOSIPConfigDefaults.h
source/include/IPTraceMacroDefaults.h
test/Coverity/ConfigFiles/FreeRTOSIPConfig.h
tools/coverity_misra.config

Misra: suppress rule 5.4
Description
-----------
Misra: suppress rule 5.4: identifiers should be unique up to the 30th character
but changing that might cause some backward incompatibility

Misra: suppress rule 5.4

---

source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_TCP_IP.c
source/portable/BufferManagement/BufferAllocation_2.c

MISRA: fix rule 8.9 violations
Description
-----------
variables should be defined inside functions if used only in those functions

MISRA: fix rule 8.9 violations

---

tools/coverity_misra.config

Misra: suppress misra 2.3 and 2.4
Description
-----------
Misra: suppress misra 2.3 and 2.4
we define structures to be conforming to FreeRTOS such as
```
typedef struct struct_name
{
int a;
} struct_name_2;
```
which allows the use to use either one, and leaves the other one as not defined.

Misra: suppress misra 2.3 and 2.4

---

source/FreeRTOS_IP.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_Reception.c
source/FreeRTOS_TCP_State_Handling.c
source/FreeRTOS_TCP_Transmission.c
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_TCP_State_Handling.h
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_UDP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c
test/unit-test/FreeRTOS_Sockets_DiffConfig/FreeRTOS_Sockets_DiffConfig_privates_utest.c
test/unit-test/FreeRTOS_Sockets_DiffConfig1/FreeRTOS_Sockets_DiffConfig1_privates_utest.c
test/unit-test/FreeRTOS_TCP_IP/FreeRTOS_TCP_IP_utest.c
test/unit-test/FreeRTOS_TCP_IP_DiffConfig/FreeRTOS_TCP_IP_DiffConfig_utest.c
test/unit-test/FreeRTOS_TCP_Reception/FreeRTOS_TCP_Reception_utest.c
test/unit-test/FreeRTOS_TCP_State_Handling/FreeRTOS_TCP_State_Handling_utest.c
test/unit-test/FreeRTOS_TCP_Transmission/FreeRTOS_TCP_Transmission_utest.c

MISRA: suppress rule 10.5
Description
-----------
MISRA: suppress rule 10.5, no valid path to convert integer into an enum
Test Steps
-----------
Related Issue
-----------

MISRA: suppress rule 10.5

---

source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_Sockets.c
source/include/FreeRTOS_IP_Private.h
tools/tcp_utilities/tcp_dump_packets.c

remove macro cast and replace with direct cast
Description
-----------
remove macro cast and replace with direct cast
the code casts using macros ipPOINTER_CAST( type, pointer) we deprecated this style in favor of the traditional direct casting method : (type) pointer

Code: remove macro cast and replace with direct cast

---

source/FreeRTOS_IP_Utils.c
source/FreeRTOS_TCP_State_Handling.c
test/Coverity/ConfigFiles/FreeRTOSConfig.h

Description
-----------
Test Steps
-----------
Related Issue
-----------

Fixing MISRA violation 4.6, 10.4

---

.github/lexicon.txt
source/FreeRTOS_DNS_Cache.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_Stream_Buffer.c
test/Coverity/ConfigFiles/pack_struct_end.h

Fixing MISRA violation 17.7, 1.2 and 8.9
Description
-----------
Test Steps
-----------
Related Issue
-----------

MISRA violation fix 17.7, 1.2, 8.9

---

MISRA.md
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/include/FreeRTOSIPConfigDefaults.h
source/portable/BufferManagement/BufferAllocation_2.c
test/Coverity/CMakeLists.txt
test/Coverity/ConfigFiles/FreeRTOSIPConfig.h
tools/coverity_misra.config

Fix Remaining Misra violations
Description
-----------
Fix Remaining and new misra violations
Test Steps
-----------
Misra checker + unit tests

Misra fix or suppress remaining violations

---

source/FreeRTOS_IP_Utils.c
source/portable/NetworkInterface/libslirp/MBuffNetifBackendLibslirp.c
source/portable/NetworkInterface/libslirp/MBuffNetworkInterface.c
tools/tcp_utilities/tcp_netstat.c

Add libslirp NetworkInterface implementation
Description
-----------
Libslirp is used by qemu to provide userspace NAT networking. This serves as a replacement for the current libpcap / winpcap NetworkInterface but does not require elevated privileges or selecting a particular interface to bind to.
In this implementation, incoming connections are not supported. This can be extended in the future by calling the libslirp port forward api calls during socket bind() and close() operations.
Test Steps
-----------
Tested with libslirp git revision 38638382c8f3dc2523468f0c54014f4fdf0aa38f on MacOS / AppleClang and Windows/MSVC (with glib from vcpkg).

Add libslirp NetworkInterface implementation

---

test/Coverity/ConfigFiles/FreeRTOSIPConfig.h
test/build-combination/AllDisable/FreeRTOSIPConfig.h
test/build-combination/AllEnable/FreeRTOSIPConfig.h
test/cbmc/patches/FreeRTOSIPConfig.h
test/unit-test/ConfigFiles/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_ARP_DataLenLessThanMinPacket/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_Utils_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_Sockets_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_Sockets_DiffConfig1/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_TCP_IP_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_TCP_Transmission/FreeRTOS_TCP_Transmission_utest.c
test/unit-test/FreeRTOS_TCP_Utils/FreeRTOS_TCP_Utils_utest.c
test/unit-test/FreeRTOS_Tiny_TCP/FreeRTOSIPConfig.h

Remove references to 1200 byte MTU
Description
-----------
Setting an MTU below 1500 bytes is very likely to cause interoperability issues with devices that have a different MTU in the same broadcast domain. To reduce confusion, this PR removes definitions of ipconfigNETWORK_MTU that are not 1500 bytes.

Remove references to 1200 byte MTU

---

source/portable/NetworkInterface/WinPCap/NetworkInterface.c
source/portable/NetworkInterface/libslirp/MBuffNetworkInterface.c
source/portable/NetworkInterface/linux/NetworkInterface.c

Implement BufferAllocation1 support for simulators
Description
-----------
Add a vNetworkInterfaceAllocateRAMToBuffers callback for the linux pcap and WinPCap NetworkInterface implementations.
Test Steps
-----------
Build posix and windows simulators with the BufferAllocation1 scheme selected.
Related Issue
-----------
#552 

Implement BufferAllocation1 support for simulators

---

test/build-combination/CMakeLists.txt
test/build-combination/Common/FreeRTOSConfig.h
test/build-combination/Common/main.c
test/build-combination/Common/winbase.h
test/build-combination/Common/windows.h
test/build-combination/README.md

Description
-----------
The build combination test was failing on Mac as we were compiling Windows port which uses some assembly instructions were not available on Mac. It also failed on Windows most likely because it was never built on Windows. 
This PR changes the build to use POSIX port on Mac and Linux and Windows port on Windows platform. It also removes stubs which are not needed anymore. 
Test Steps
-----------
Test Command - 
```
cmake -S test/build-combination -B test/build-combination/build/  -DTEST_CONFIGURATION=ENABLE_ALL
```

Fix Mac and Windows compilation error

---

source/portable/NetworkInterface/libslirp/MBuffNetifBackendLibslirp.c

NetifSlirp: Fix compatibility with libslirp v4.6.x
Description
-----------
Ubuntu 22.04 ships with libslirp 4.6.1 via packages libslirp0 and libslirp-dev. Libslirp v4.6.x has a slightly different configuration struct. The PR adjusts the implementation in MBuffNetifBackendLibslirp.c to support libslirp 4.6.x.
Test Steps
-----------
Build FreeRTOS Posix sim TCP Echo Demo with BufferAllocation1 and BufferAllocation2. Test each binary against a TCP echo server.

NetifSlirp: Fix compatibility with libslirp v4.6.x

---

source/portable/NetworkInterface/libslirp/MBuffNetifBackendLibslirp.c

NetifSlirp: Fix compiler warnings and errors
Description
-----------
Fix some compiler warnings / errors on msvc. 
In particular, windows does not define an ssize_t type, so ensure we can use the slirp_ssize_t type defined by the latest revision of libslirp.
Test Steps
-----------
Built on latest gcc, clang, and msvc for x86.

NetifSlirp: Fix compiler warnings and errors

---

.github/lexicon.txt
source/FreeRTOS_IP_Timers.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_State_Handling.c
source/include/FreeRTOS_IP_Private.h
test/cbmc/proofs/parsing/ProcessReceivedTCPPacket/ProcessReceivedTCPPacket_harness.c
test/unit-test/FreeRTOS_IP_Timers/FreeRTOS_IP_Timers_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
test/unit-test/FreeRTOS_TCP_IP/FreeRTOS_TCP_IP_utest.c
test/unit-test/FreeRTOS_TCP_IP_DiffConfig/FreeRTOS_TCP_IP_DiffConfig_utest.c

Description
-----------
A TCP connection can be established in either two ways: accept() and connect().
When using connect(), the socket is created and owned by the application.
When using accept(), the new socket is created and temporarily owned by the IP-task, and in the comments it is called an "orphaned socket". Once the connection is established, the function accept() will pass the ownership to the application.
The stack has a mechanism that checks sockets for inactivity: `ipconfigTCP_HANG_PROTECTION`. After `ipconfigTCP_HANG_PROTECTION_TIME` seconds of inactivity an orphaned socket will be closed.
There were a few reasons to create this PR:
1) When a protocol error occurs during a `FreeRTOS_connect()`, the API should stop waiting and return `-pdFREERTOS_ERRNO_ENOTCONN` to the …

IPv4/single: connect() should return immediately after a protocol error and other things

---

History.txt
README.md
manifest.yml
source/include/FreeRTOS_IP.h

Description
-----------
Test Steps
-----------
Related Issue
-----------

Update mainline to reflect changes after the release.

---

source/portable/NetworkInterface/DriverSAM/NetworkInterface.c
source/portable/NetworkInterface/DriverSAM/gmac_SAM.c
source/portable/NetworkInterface/DriverSAM/gmac_SAM.h

Description
-----------
A user on the FreeRTOS forum, [@Maty](https://forums.freertos.org/u/maty) reported that on a SAME70 the transmission stops after a while.
The post can be [found here](https://forums.freertos.org/t/freertos-10-1-1-http-server-on-sam4e-xplained-stops-after-sending-one-file/7678/5).
We both found a solution to this problem, but Maty's solution looks more efficient.
The CPU seems faster than the peripheral. When it enqueues all TX descriptors, it may happen that the peripheral forgets to fire an interrupt.
In this solution, the driver will use all descriptors but one, at the same time. See also [my post](https://forums.freertos.org/t/freertos-10-1-1-http-server-on-sam4e-xplained-stops-after-sending-one-file/7678/22) a detailed description.
We are both still running …

IPv4/single SAME70 emac race condition

---

.github/lexicon.txt
source/FreeRTOS_Sockets.c
source/include/FreeRTOSIPConfigDefaults.h
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_Sockets.h
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c

Description
-----------
In [issue #540](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/543), [Jabob Carver](https://github.com/karver8) is asking for the possibility to assign a unique ID to each socket.
We found that a good idea and this PR adds it, depending on the new macro `ipconfigUSE_SetSocketID`.
In many applications, sockets are embedded in an object, a class. The "SetSocketID" can be a pointer to the instance of that class.
These will be the new functions:
~~~c
BaseType_t xSocketSetSocketID( const Socket_t xSocket, void * pvSocketID );
void * pvSocketGetSocketID( const ConstSocket_t xSocket );
~~~
Test Steps
-----------
~~~c
/* Read the current value of the SocketID. */
void * id1 = pvSocketGetSocketID( xSocket );
/* Set value of the SocketID. */
int rc = …

IPv4/Single: Add a SocketID to a socket

---

source/FreeRTOS_ARP.c
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_State_Handling.c
source/FreeRTOS_TCP_Transmission.c
source/FreeRTOS_TCP_Utils.c
source/FreeRTOS_UDP_IP.c
source/include/FreeRTOSIPConfigDefaults.h
source/include/FreeRTOS_IP.h
source/include/FreeRTOS_IP_Common.h
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_IPv4.h
source/include/FreeRTOS_IPv4_Private.h
source/include/FreeRTOS_IPv6.h
source/include/FreeRTOS_IPv6_Private.h
test/unit-test/CMakeLists.txt
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP_Utils/FreeRTOS_IP_Utils_utest.c
test/unit-test/FreeRTOS_UDP_IP/FreeRTOS_UDP_IP_utest.c

Description
-----------
- Split FreeRTOS_IP header files to IPv4 and IPv6 specific header files and add IPv6 specific structures.
> FreeRTOS_IPv4.h
> FreeRTOS_IPv4_Private.h
> FreeRTOS_IPv6.h
> FreeRTOS_IPv6_Private.h
> FreeRTOS_IP_Common.h
- Added header files based on ipconfigUSE_IPV4 and ipconfigUSE_IPV6 to ensure backward compatibility.
- Created a common IP address structure to handle both IPv4 and IPv6 address : 
IP_Address_t xIPAddress;      /**< Source or destination IP address, depending on usage scenario. */
Test Steps
-----------
As of now compilation test is being done. *
```
```
Related Issue
-----------
As unit tests will be done after …

Add IPv6 specific header files.

---

source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_ICMP.c
source/FreeRTOS_IP.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_Reception.c
source/FreeRTOS_TCP_State_Handling.c
source/FreeRTOS_TCP_Transmission.c
source/FreeRTOS_UDP_IP.c
source/include/FreeRTOS_IP.h
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_IPv4.h
source/include/FreeRTOS_IPv4_Private.h
source/include/FreeRTOS_IPv6_Private.h
source/include/FreeRTOS_TCP_IP.h

Description
-----------
- Add common Header size function for IPv6 and IPv4
- Fix rule 1.1, 10.3, 20.9 and suppress rule 20.5
Test Steps
-----------
As of now compilation test is being done.
```
```
Related Issue
-----------
As unit tests will be done after merging other changes as well. It might break some test cases as of now which will be fixed in upcoming PRs.

Add Header size functions for IPv6 and IPv4 

---

source/portable/NetworkInterface/DriverSAM/NetworkInterface.c
source/portable/NetworkInterface/DriverSAM/gmac_SAM.c
source/portable/NetworkInterface/DriverSAM/gmac_SAM.h

Description
-----------
In the [DriverSAM](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/main/source/portable/NetworkInterface/DriverSAM) driver, the macro `GMAC_FRAME_LENTGH_MAX` is the maximum supported frame length, 1536 bytes. That is the maximum number of bytes in an Ethernet packet.
The macro `NETWORK_BUFFER_SIZE` was supposed to define size of a network buffer, which should be 1536 bytes **plus** a `ipBUFFER_PADDING` (10) hidden bytes .
This PR makes sure that the statically allocated buffers in `ucNetworkPackets[]` are large enough to accommodate the largest possible incoming packet.
To summarize this PR:
~~~diff
-#define NETWORK_BUFFER_SIZE    ( 1536 )
+#define NETWORK_BUFFER_SIZE    ( 1536+16 )
~~~
`ipBUFFER_PADDING` is rounded up to 16 to get a nice alignment.
By …

IPv4/single: SAME70 EMAC buffer sizes

---

source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/portable/NetworkInterface/Zynq/x_emacpsif_physpeed.c

Description
-----------
Eliminate some printf() related warning messages by changing specifiers and applying appropriate casts.  
Test Steps
-----------
Build the source code with GCC Xilinx ARM compiler version 11.2 to generate said warnings.  
Related Issue
-----------
N/A

Eliminate some warnings

---

MISRA.md
source/FreeRTOS_DNS_Callback.c
source/FreeRTOS_Sockets.c

Description
-----------
Ref: https://forums.freertos.org/t/freertos-plus-tcp-with-static-memory-allocation/14815
FreeRTOS+TCP must use dynamic memory allocation as it stands now. To that end, a justification has to be added to the MISRA.md file in the repository clarifying the use of dynamic memory in the code.
This PR adds the justification and the code comments for suppressing Coverity warnings regarding the same.
Test Steps
-----------
Related Issue
-----------

Add justification for use of dynamic memory

---

source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_dma.c

Description
-----------
While integrating the FTP-server from the [Demo Ip Protocols](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Demo/Common/Demo_IP_Protocols) to an application for the Cortex-R5 processor of the Xilinx Zynq UltraScale MPSoC, I noticed that the FTP-server was not working reliably when Jumbo Frames were being used. However this was not the case when Jumbo Frames were deactivated in my Network adapter, as this would function as expected.
After some investigation and enabling the `FreeRTOS_printf`-messages, I was getting the error message:
```
xCheckSizeFields: location 4
```
There I checked the said location and observed, that `uxBufferLength` was not having the expected value of the IP-packet, that was sent by the FTP-client.
```c
/* Check if the complete …
```

Fix Network-interface of the Xilinx UltraScale port

---

source/portable/NetworkInterface/WinPCap/NetworkInterface.c

Description
-----------
Fixed an issue where a Windows thread used to receive from WinPCap inadvertently called vTaskSuspendAll/xTaskResumeAll (added to uxStreamBufferAdd by https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/517) when adding to the circular buffer used to pass received data from WinPCap to a FreeRTOS task. This would cause WinSim to crash (very intermittently) in the case that the pcap callback suspends the scheduler while a Task running in WinSim is at point where it needs the scheduler to be in a running state (e.g. calling xQueueReceive, vTaskDelay, etc.).
Test Steps
-----------
Ran all WinSim demos from FreeRTOS/FreeRTOS.
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Fix Windows thread calling vTaskSuspendAll / xTaskResumeAll.

---

source/FreeRTOS_BitConfig.c
source/FreeRTOS_DHCP.c
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Timers.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_IPv4.c
source/FreeRTOS_IPv6.c
source/FreeRTOS_ND.c
source/FreeRTOS_Routing.c
source/include/FreeRTOSIPConfigDefaults.h
source/include/FreeRTOS_ARP.h
source/include/FreeRTOS_IP.h
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_IP_Utils.h
source/include/FreeRTOS_IPv4.h
source/include/FreeRTOS_IPv6.h

Description
-----------
Added end point changes for IP Init and all IP related functions.
Added 
- FreeRTOS_IPv4.c 
- FreeRTOS_IPv6.c
Updated :
-  source/include/FreeRTOS_IP.h
-  source/include/FreeRTOS_IPv4.h 
-  source/include/FreeRTOS_IPv6.h
Related Issue
-----------
As unit tests will be done after merging other changes as well. It might break some test cases as of now which will be fixed in upcoming PRs.

Add IPv6 data path and endpoint changes to FreeRTOS_IP.c

---

source/FreeRTOS_Sockets.c
source/include/FreeRTOS_DHCPv6.h
source/include/FreeRTOS_IPv4_Private.h
source/include/FreeRTOS_IPv6_Private.h
test/unit-test/CMakeLists.txt
test/unit-test/ConfigFiles/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_UDP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c
test/unit-test/FreeRTOS_Sockets/ut.cmake

Build fix for unit tests for sockets - ipv4
Description
-----------
Updated the cmake files and unit test files to make it buildable with the latest IPv6 changes
Test Steps
-----------
Builds successfully
Related Issue
-----------
NA

Build fix for unit tests for sockets - ipv4

---

source/FreeRTOS_Sockets.c

Update function documentation for FreeRTOS_select API
Description
-----------
The documentation for return value of FreeRTOS_select API has been updated to fix the previous incorrect documentation. 
Test Steps
-----------
No additional tests performed as there is no code changes.
Related Issue
-----------
[FreeRTOS_select incorrect return value documentation](https://forums.freertos.org/t/freertos-plus-tcp-freertos-select-incorrect-return-value-documentation/16333)
Thanks [Igor_Petrov](https://forums.freertos.org/u/Igor_Petrov) for reporting this discrepancy.

Updated comments for FreeRTOS_select return value

---

test/unit-test/FreeRTOS_ICMP/FreeRTOS_ICMP_utest.c

Build fix for unit tests for ICMP - ipv4
Description
-----------
Updated the cmake files and unit test files to make it buildable with the latest IPv6 changes
Test Steps
-----------
Builds successfully
Related Issue
-----------
NA

ICMP unit test build fix

---

source/FreeRTOS_UDP_IP.c
source/FreeRTOS_UDP_IPv4.c
source/FreeRTOS_UDP_IPv6.c
source/include/FreeRTOS_IP.h

UDP protocol support for IPv6
Description
-----------
UDP protocol support for IPv6
The UDP functionality is split into 2 files FreeRTOS_IPV4.c and FreeRTOS_IPV6.c to support both IPv4 and IPv6.
Test Steps
-----------
Related Issue
-----------

UDP protocol support for IPv6

---

source/include/FreeRTOS_IPv4_Private.h
source/include/NetworkInterface.h
source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c
source/portable/NetworkInterface/WinPCap/NetworkInterface.c
test/Coverity/Portable.c
test/unit-test/ConfigFiles/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c

Added changes in WinPCap Port for IPV4 Endpoint changes
Network Interface changes for WinPCap Port 
Description
-----------
Added Endpoint changes and Network Interface structure changes
Test Steps
-----------
Related Issue
-----------

Update Portable Folder for End Point changes

---

source/FreeRTOS_ARP.c
source/FreeRTOS_DHCP.c
source/FreeRTOS_DNS.c
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_Transmission.c
source/FreeRTOS_TCP_Transmission_IPV4.c
source/FreeRTOS_TCP_Transmission_IPV6.c
source/FreeRTOS_TCP_Utils_IPV6.c
source/include/FreeRTOS_IP.h
source/include/FreeRTOS_IPv6.h
source/include/FreeRTOS_TCP_State_Handling.h
source/include/FreeRTOS_TCP_Transmission.h

As ipconfigCOMPATIBLE_WITH_SINGLE is never enabled and used partially, removing the rest of the instances of the same.
Ran uncrustify.
Test Steps
-----------
```
```

Remove use of ipconfigCOMPATIBLE_WITH_SINGLE

---

test/unit-test/README.md

Description
-----------
This PR fixes outdated instructions in the script used to run the unit tests inside the readme file of the unit-test folder. 
Test Steps
-----------
Related Issue
-----------
Outdated instructions to build and run the unit tests in the readme file of unit-tests folder.

Fixed outdated readme instructions/script to build and run unit tests

---

source/FreeRTOS_ICMP.c
source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_dma.c
source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_hw.c
source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_physpeed.c

Description
-----------
While building the FreeRTOS-Plus-TCP library for the Xilinx UltraScale SoC, I came across some open warnings that would be triggered in particular cases.
Check the commit messages for more info about the warnings.
Test Steps
-----------
Compiler used to generate the warning in this PR:
```
arm-xilinx-eabi-gcc.exe (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
``` 
Compiler options:
```
1: -pedantic -Wall -Wextra -O0
2: -pedantic -Wall -Wextra -O2
```
Related Issue
-----------
None
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Minor warning fixes

---

source/FreeRTOS_UDP_IP.c
source/FreeRTOS_UDP_IPv4.c
test/unit-test/FreeRTOS_UDP_IP/FreeRTOS_UDP_IP_stubs.c
test/unit-test/FreeRTOS_UDP_IP/FreeRTOS_UDP_IP_utest.c
test/unit-test/FreeRTOS_UDP_IP/list_macros.h
test/unit-test/FreeRTOS_UDP_IP/ut.cmake
test/unit-test/TCPFilePaths.cmake

Fixes UDP IP failing unit tests cases wrt IPv6 changes
Description
-----------
This PR fixes the failing test cases for the UDP IP unit tests.
Source file changes:
* source/FreeRTOS_UDP_IP.c:
Removed return value variable for function calls that doesn’t return anything 
Added return value for the functions that returns value.
Test Steps
-----------
```
```
Related Issue
-----------
Failing test cases

Fix udp ip failing unit test cases

---

test/unit-test/FreeRTOS_TCP_Utils/FreeRTOS_TCP_Utils_utest.c
test/unit-test/FreeRTOS_TCP_Utils/TCP_Utils_list_macros.h
test/unit-test/FreeRTOS_TCP_Utils/ut.cmake
test/unit-test/TCPFilePaths.cmake

Description
-----------
This PR fixes the TCP Utils unit test cases that were failing after the IPv6 related source code changes.
Test Steps
-----------
```
```
Related Issue
-----------
Failing TCP Utils test cases.

Fixed failing test cases for TCP utils unit tests

---

test/unit-test/FreeRTOS_TCP_Reception/FreeRTOS_TCP_Reception_utest.c

Description
-----------
This PR fixes the TCP Reception unit test cases that were failing after the IPv6 related source code changes.
Test Steps
-----------
```
```
Related Issue
-----------
Failing TCP Reception test cases.

Fixed failing unit test cases for tcp reception

---

test/unit-test/FreeRTOS_TCP_State_Handling/FreeRTOS_TCP_State_Handling_utest.c
test/unit-test/FreeRTOS_TCP_State_Handling/TCP_State_Handling_list_macros.h
test/unit-test/FreeRTOS_TCP_State_Handling/ut.cmake
test/unit-test/TCPFilePaths.cmake

Description
-----------
This PR fixes the TCP State handling unit test cases that were failing after the IPv6 related source ocde changes.
Test Steps
-----------
```
```
Related Issue
-----------
Failing TCP State handling test cases.

Fixed failing unit test cases for TCP state handling

---

source/FreeRTOS_IPv6_Sockets.c
source/FreeRTOS_Sockets.c
source/include/FreeRTOS_IPv6_Sockets.h
source/include/FreeRTOS_Sockets.h
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_UDP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c
test/unit-test/FreeRTOS_Sockets/ut.cmake
test/unit-test/TCPFilePaths.cmake

Fix unit test cases for FreeRTOS_Sockets_TCP_API_utest
Run uncrustify
Test Steps
-----------
```
cmake -S test/unit-test -B test/unit-test/build/
```

Fix unit test cases for FreeRTOS_Sockets_TCP_API_utest

---

test/cbmc/proofs/Makefile.template

Prior to this commit, CBMC would emit logging information in plain text format, which does not contain information required for the CBMC VSCode debugger. This commit makes CBMC use XML instead of plain text.

Use CBMC XML output to enable VSCode debugger

---

source/FreeRTOS_UDP_IP.c
test/unit-test/CMakeLists.txt
test/unit-test/ConfigFiles/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_stubs.c
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c
test/unit-test/FreeRTOS_ARP_DataLenLessThanMinPacket/ARP_DataLenLessThanMinPacket_list_macros.h
test/unit-test/FreeRTOS_ARP_DataLenLessThanMinPacket/FreeRTOS_ARP_DataLenLessThanMinPacket_stubs.c
test/unit-test/FreeRTOS_ARP_DataLenLessThanMinPacket/FreeRTOS_ARP_DataLenLessThanMinPacket_utest.c
test/unit-test/FreeRTOS_TCP_Transmission/FreeRTOS_TCP_Transmission_utest.c
test/unit-test/FreeRTOS_TCP_Transmission/TCP_Transmission_list_macros.h
test/unit-test/FreeRTOS_TCP_Utils/FreeRTOS_TCP_Utils_utest.c
test/unit-test/FreeRTOS_TCP_WIN/FreeRTOS_TCP_WIN_stubs.c
test/unit-test/FreeRTOS_Tiny_TCP/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_Tiny_TCP/FreeRTOS_Tiny_TCP_stubs.c
test/unit-test/FreeRTOS_UDP_IP/FreeRTOS_UDP_IP_utest.c
test/unit-test/FreeRTOS_UDP_IP/list_macros.h
test/unit-test/FreeRTOS_UDP_IP/ut.cmake

Description
-----------
This PR fixes unit test build issues and test failures for ARP, TCP and UDP unit tests which were failing after the latest IPv6 integration changes.
Test Steps
-----------
```
```
Related Issue
-----------
ARP, TCP, UDP unit test cases were failing due to the changes in the source code as part of the IPv6 integration

Fix unit test build issues and test failures for ARP, TCP, UDP

---

source/FreeRTOS_Routing.c
source/FreeRTOS_TCP_IP_IPV4.c
source/FreeRTOS_TCP_IP_IPV6.c
source/FreeRTOS_TCP_Reception.c
source/FreeRTOS_TCP_State_Handling.c
source/FreeRTOS_TCP_State_Handling_IPV4.c
source/FreeRTOS_TCP_State_Handling_IPV6.c
source/FreeRTOS_TCP_Transmission.c
source/FreeRTOS_TCP_Transmission_IPV4.c
source/FreeRTOS_TCP_Transmission_IPV6.c
source/FreeRTOS_TCP_Utils_IPV4.c
source/FreeRTOS_TCP_Utils_IPV6.c
source/include/FreeRTOS_Routing.h
source/include/FreeRTOS_TCP_IP.h

Description
-----------
● FreeRTOS_TCP_Transmission_IPV4.c
Solved several problems in `prvTCPReturnPacket_IPV()`.
TCP_Transmission_IPV4.c: Remove some code that handles IV6
TCP_Transmission_IPV6.c: Remove some code that handles IV4
Without this cleaning up, I found it very difficult to compare both modules and get them working.
● When using TCPv6, the IP-headers become bigger, so the space for the (TCP or UDP) payload becomes smaller. The difference is 20 bytes.
● `uxIPHeaderSizePacket()` should be called in stead of `xIPHeaderSize()`. The latter would return a const value of 20.
● A new function `xIPv6_GetIPType()` which checks an IPv6 address, resulting in one of these types:
~~~
eIPv6_Global
eIPv6_LinkLocal
eIPv6_SiteLocal
eIPv6_Multicast
eIPv6_Unknown
~~~
This makes IPv6 routing a lot …

Changes after testing TCP IPv4 and IPv6

---

source/FreeRTOS_Routing.c

Clear the IPv6 flag when filling endpoint.
Test Steps
-----------
```
```

Update bIPv6 flag

---

source/FreeRTOS_DNS_Callback.c
source/FreeRTOS_DNS_Parser.c
test/unit-test/FreeRTOS_DNS/FreeRTOS_DNS_utest.c
test/unit-test/FreeRTOS_DNS_Networking/FreeRTOS_DNS_Networking_utest.c
test/unit-test/FreeRTOS_DNS_Parser/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_DNS_Parser/FreeRTOS_DNS_Parser_utest.c

Description
-----------
This PR fixes unit test build issues and test failures for DNS unit tests which were failing after the latest IPv6 integration changes.
`source/FreeRTOS_DNS_Parser.c`:
1. `vReturnEthernetFrame` is called twice during `DNS_TreatNBNS`:
a. Once inside `prepareReplyDNSMessage`
b. And inside `DNS_TreatNBNS`
Test Steps
-----------
```
```
Related Issue
-----------
DNS unit test cases were failing due to the changes in the source code as part of the IPv6 integration

Fix unit test build issues and test failures for DNS

---

source/FreeRTOS_Sockets.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_UDP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c

Description
-----------
This PR fixes unit test build issues and test failures for Sockets unit tests which were failing after the latest IPv6 integration changes.
Test Steps
-----------
```
```
Related Issue
-----------
Sockets unit test cases were failing due to the changes in the source code as part of the IPv6 integration

Fix unit test build issues and test failures for Sockets

---

test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_stubs.c
test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_utest.c
test/unit-test/FreeRTOS_DHCP/ut.cmake

Description
-----------
This PR fixes unit test build issues and test failures for DHCP unit tests which were failing after the latest IPv6 integration changes.
Test Steps
-----------
```
```
Related Issue
-----------
DHCP unit test cases were failing due to the changes in the source code as part of the IPv6 integration

Fix unit test build issues and test failures for DHCP

---

source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_physpeed.c

Description
-----------
The issue here is that, the FreeRTOS IP-task would block all other tasks during PHY-link speed negotiations, as it was using busy waiting. However this is not really ideal. A much more suitable function for such a task would be `vTaskDelay`.
Test Steps
-----------
This PR was tested within our application with real hardware and the behaviour of the IP-task was as expected, meaning it would no longer block the other the tasks of the application during link speed negotiations. 
Related Issue
-----------
NA

Use vTaskDelay for sleep in the network-interface of xilinx_ultrascale

---

source/FreeRTOS_TCP_IP.c

Description
-----------
When the a TCP connection is in the SYN phase, it can happen that the socket will get closed twice.
This patch makes sure that the socket is either owned by the IP-task, or by the application.

Make sure that a socket in the SYN phase doesn't get closed twice

---

source/FreeRTOS_DHCP.c
source/FreeRTOS_DNS.c
source/FreeRTOS_DNS_Cache.c
source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_Transmission.c
source/FreeRTOS_TCP_Transmission_IPV4.c
source/FreeRTOS_TCP_Transmission_IPV6.c

Here is a summary of the changes in this PR:
-----------
FreeRTOS_TCP_Transmission_IPV6.c
● In prvTCPReturnPacket_IPV6: use 'TCPPacket_IPv6_t' in stead of 'TCPPacket_t'
● When it has a socket, copy address from socket
● When it has no socket, swap the destination and source IP-addresses
● In prvTCPPrepareConnect_IPV6(): use `TCPPacket_IPv6_t` and `IPHeader_IPv6_t` in stead of the IPv4 variants.
FreeRTOS_TCP_Transmission_IPV4.c
● When it has a socket, copy address from socket
● When it has no socket, swap the destination and source IP-addresses
FreeRTOS_TCP_Transmission.c
● Let prvTCPSendSpecialPacketHelper() return 'xReturn' in stead of const 'pdFAIL'
FreeRTOS_TCP_IP.c
● In xProcessReceivedTCPPacket() : no need to set `xResult` if it will be overwritten unconditionally. …

A few changes after testing Xueli's branch, mostly TCP_Transmission

---

source/FreeRTOS_TCP_IP.c
source/include/FreeRTOS_IP_Private.h
test/unit-test/FreeRTOS_TCP_IP/FreeRTOS_TCP_IP_utest.c
test/unit-test/FreeRTOS_TCP_IP_DiffConfig/FreeRTOS_TCP_IP_DiffConfig_utest.c

Description
-----------
If during the SYN phase, a sockets goes to the `eCLOSED` state, it must be closed/released. But at that moment, it may happen that the application does a successful call to `FreeRTOS_accept()`, and gets the ownership of the socket.
The IP-task in a meanwhile is planning to close the socket as well. See the function [`vSocketCloseNextTime()`](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/a9f7c9a317c37499de17014216c550a559bc505c/source/FreeRTOS_TCP_IP.c#L122)
Here is the proposed change:
~~~diff
if( ( eTCPState == eCLOSED ) ||
( eTCPState == eCLOSE_WAIT ) )
{
/* Socket goes to status eCLOSED because of a RST.
* When nobody owns the socket yet, delete it. */
+        vTaskSuspendAll();
{
if( ( pxSocket->u.xTCP.bits.bPassQueued != pdFALSE_UNSIGNED ) ||
( …

Make sure that a TCP socket is closed only once

---

source/FreeRTOS_BitConfig.c

The sizes of array variables in C must be known at compile time. Here sizeof result is a constant. However, if we assign it to a constant variable it is still a variable to C.
Hence updating the array size parameter.

Fix compilation error in FreeRTOS_BitConfig.h

---

source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_IP.c
source/FreeRTOS_UDP_IP.c
source/include/FreeRTOS_IP.h
source/portable/NetworkInterface/MPS2_AN385/NetworkInterface.c
source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c
source/portable/NetworkInterface/Zynq/NetworkInterface.c
source/portable/NetworkInterface/Zynq/uncached_memory.c
source/portable/NetworkInterface/Zynq/x_emacpsif.h
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c
test/unit-test/FreeRTOS_ARP_DataLenLessThanMinPacket/FreeRTOS_ARP_DataLenLessThanMinPacket_stubs.c
test/unit-test/FreeRTOS_ARP_DataLenLessThanMinPacket/FreeRTOS_ARP_DataLenLessThanMinPacket_utest.c
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP/IP_list_macros.h
test/unit-test/FreeRTOS_IP_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig/FreeRTOS_IP_DiffConfig_utest.c
test/unit-test/FreeRTOS_IP_DiffConfig1/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig1/FreeRTOS_IP_DiffConfig1_utest.c
test/unit-test/FreeRTOS_IP_DiffConfig1/IP_DiffConfig1_list_macros.h
test/unit-test/FreeRTOS_IP_DiffConfig2/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig2/FreeRTOS_IP_DiffConfig2_utest.c
test/unit-test/FreeRTOS_IP_Utils_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_TCP_Reception/FreeRTOS_TCP_Reception_utest.c
test/unit-test/FreeRTOS_TCP_State_Handling/FreeRTOS_TCP_State_Handling_utest.c
test/unit-test/FreeRTOS_TCP_Transmission/FreeRTOS_TCP_Transmission_utest.c

Change in UDP process flow to drop packet for invalid IPv4 payload length
Description
-----------
Change in prvProcessUDPPacket function, add condition for Release buffer
Checking the frame type only for IPv4, since the same check will give unwanted results for IPv6
Test Steps
-----------
Code is building with the changes
Related Issue
-----------

Change in UDP process flow to drop packet for invalid IPv4 payload length

---

.github/workflows/ci.yml
source/FreeRTOS_DNS.c
source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_IP.c
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c
test/unit-test/FreeRTOS_DNS/FreeRTOS_DNS_utest.c
test/unit-test/FreeRTOS_IP_DiffConfig/FreeRTOS_IP_DiffConfig_stubs.c
test/unit-test/FreeRTOS_IP_DiffConfig1/FreeRTOS_IP_DiffConfig1_utest.c
test/unit-test/FreeRTOS_TCP_IP/FreeRTOS_TCP_IP_utest.c
test/unit-test/FreeRTOS_TCP_IP_DiffConfig/FreeRTOS_TCP_IP_DiffConfig_utest.c
test/unit-test/FreeRTOS_TCP_Transmission/FreeRTOS_TCP_Transmission_utest.c

This PR fixes all the build issues and test failures so far for the [FreeRTOS:dev/IPv6_integration](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/dev/IPv6_integration) branch. This validates all the IPv4 unit tests.
Test Steps
-----------
```
```

Fix unit tests and build issues

---

source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c
source/portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.c
source/portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.h

Remove Dup function HAL_ETH_SetMDIOClockRange.
Description
-----------
HAL_ETH_SetMDIOClockRange and ETH_MAC_MDIO_ClkConfig are doing same thing to configure MDIO CSR Clock range. Remove HAL_ETH_SetMDIOClockRange to for efficiency.
Test Steps
-----------
Related Issue
-----------
#540 

Remove Dup function HAL_ETH_SetMDIOClockRange.

---

source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c
source/portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.c
source/portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.h

Remove Dup function HAL_ETH_SetMDIOClockRange.
Description
-----------
Patch from #711 to IPv6 branch. 
HAL_ETH_SetMDIOClockRange and ETH_MAC_MDIO_ClkConfig are doing same thing to configure MDIO CSR Clock range. Remove HAL_ETH_SetMDIOClockRange to for efficiency.
Test Steps
-----------
Related Issue
-----------
#540 

[IPv6 branch] Remove Dup function HAL_ETH_SetMDIOClockRange.

---

source/FreeRTOS_IPv4.c

Remove left over IPv6 code from IPv4 UDP flow.
Description
-----------
Remove some left over IPv6 code and packet parsing logic from IPv4 UDP flow
Test Steps
-----------
Related Issue
-----------

Remove left over IPv6 checks from IPv4 Flow

---

source/FreeRTOS_IP.c

Fix to drop loopback ip packets for UDP
Description
-----------
Fix to drop packets received with loopback ip-address for UDP
Test Steps
-----------
Build and unit test
Related Issue
-----------

Fix to Drop loopback ip packets for UDP

---

source/FreeRTOS_TCP_Transmission.c
test/unit-test/FreeRTOS_TCP_Transmission/FreeRTOS_TCP_Transmission_utest.c

Description
-----------
[@t123yh](https://github.com/t123yh) reported in [issue #700](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/700) that when a device responds with a RST packet to a SYN request, the ACK number is not increased by 1. A SYN packet has a symbolical length of 1 data byte and should be acknowledged.
That is a very useful change, before the TCP client would reach a time-out, as show here:
~~~
Connecting to 192.168.2.15 ...
TCP connection timeout
~~~
After this change, the client sees a valid ACK in the RST reply, and it can report an error:
~~~
Connecting to 192.168.2.15 ...
TCP connection error :10061
~~~
10061 : No connection could be made because the target machine actively refused it
@t123yh, thank you for reporting this bug.
I will make sure that the change …

Main/TCP4 : ACK number in TCP RESET reply to SYN packet

---

source/FreeRTOS_ARP.c

These changes handles if there is a clash with another device for the same IP address.
Description
-----------
When there is another device which has the same IP address as the IP address
of this device, a defensive ARP request should be sent out. However, according to
RFC 5227 section 1.1, there must be a minimum interval of 10 seconds between
consecutive defensive ARP packets. 

Add changes to IP-clash detection in ARP

---

source/FreeRTOS_ARP.c

Initialise pxSourceEndPoint in ARP clash detection case.
Test Steps
-----------
```
```

Initialise pxSourceEndPoint in ARP

---

CMakeLists.txt

Fixed CMake to point to the right FreeRTOS kernel and branch.
Description
-----------
CMake now points to https://github.com/FreeRTOS/FreeRTOS-Kernel instead of https://github.com/phelter/FreeRTOS-Kernel.git
Test Steps
-----------
1. cmake -S . -B build -DFREERTOS_PLUS_TCP_TEST_CONFIGURATION=DEFAULT_CONF
2. Navigate to /build/_deps/freertos_kernel-src folder created after CMake step. Confirm that kernel points to the right remote.
3. cmake --build build --target clean
4. cmake --build build --target freertos_plus_tcp_build_test
Checklist:
----------
Related Issue
-----------

CMake: Fix GIT_REPOSITORY and GIT_TAG

---

source/FreeRTOS_ND.c

Fix for assert in vNDAgeCache function
Description
-----------
Add a condition so that NDageCache functions just returns gracefully when invoked for IPv4 cases.
Test Steps
-----------
Related Issue
-----------

 Fix for assert in vNDAgeCache function

---

tools/tcp_utilities/include/tcp_netstat.h
tools/tcp_utilities/tcp_netstat.c

Description
-----------
As demos in main branch is using xOutput and PR738 changed it which is causing demos build failure.
Change XOutput back to xOutput.
Checklist:
----------

Update MetricsType output counter variable

---

source/FreeRTOS_IP.c
source/include/FreeRTOS_IP.h
source/portable/NetworkInterface/DriverSAM/NetworkInterface.c
source/portable/NetworkInterface/MPS2_AN385/NetworkInterface.c
source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c
source/portable/NetworkInterface/WinPCap/NetworkInterface.c
source/portable/NetworkInterface/Zynq/NetworkInterface.c
source/portable/NetworkInterface/esp32/NetworkInterface.c
source/portable/NetworkInterface/pic32mzef/NetworkInterface_eth.c
test/build-combination/Common/main.c

Description
-----------
Add backward compatibility with IPv4 single endpoint branch by adding following changes:
- Update the backward compatibility flag for IPv4 only build to ipconfigIPv4_BACKWARD_COMPATIBLE.
- Add pxFillInterfaceDescriptor for all portable layer network interface for backward compatibility.
- Rename FreeRTOS_IPStart to FreeRTOS_IPInit_Multi
Test Steps
-----------
Demo Run on Jenkins.
Checklist:
----------
Related Issue
-----------

Update portable layer for backward compatibility

---

source/FreeRTOS_IPv6_Sockets.c

Fix IPv6 source address from FreeRTOS_recvfrom.
Description
-----------
In IPv6 protocol test, the address of machine is wrong on device side.
The reason is code reset the IPv4 address but it's union structure with IPv6 address.
Test Steps
-----------
Run protocol test case calibration/calibration/000 with traffic source udp.v6.
Checklist:
----------
Related Issue
-----------

Fix IPv6 source address from FreeRTOS_recvfrom.

---

source/FreeRTOS_Routing.c

Description
-----------
Keeping xIPv6_GetIPType()  and pcEndpointName() out of the compatibility flag disabled check to fix build issues from the +TCP library.

More compatibility changes

---

source/FreeRTOS_ARP.c
source/FreeRTOS_IP.c
source/include/FreeRTOS_IP_Private.h
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c

Allow use of loopback addresses in IP stack (127.0.0.0/8)
Description
-----------
The use of loopback addresses (defined as IP range 127.0.0.0/8) can be useful for development, testing, and even general use.
Currently the FreeRTOS IP stack filters out these addresses. This PR modifies the filtering such that:
* the IP filter will allow addresses in the loopback range
* ARP will return cache hit if the destination address is in loopback range
* Checking if ARP resolution is required will return false if destination address is in loopback range
Test Steps
-----------
Unit tests added to IP and ARP
Checklist:
----------
Related Issue
-----------
N/A

Allow use of loopback addresses in IP stack (127.0.0.0/8)

---

source/FreeRTOS_Routing.c

Description
-----------
Uses the previous ipconfigCOMPATIBLE_WITH_SINGLE macro instead of ipconfigIPv4_BACKWARD_COMPATIBLE in routing APIs

Use ipconfigCOMPATIBLE_WITH_SINGLE in routing

---

.github/workflows/release-candidate.yml

Description
-----------
This is a minimal subset of release automation which only creates a tag and verifies it.
Test Steps
-----------
Test on my fork. Here is successful run - https://github.com/aggarg/FreeRTOS-Plus-TCP/actions/runs/4372075057/jobs/7648583084

Add release candidate automation

---

source/include/FreeRTOSIPConfigDefaults.h

Description
-----------
This PR makes it mandatory to enable ipconfigUSE_IPv4 and ipconfigUSE_IPv6 flags to be enabled for build to progress, as separation for both IPv4 and IPv6 is work in progress.
Test Steps
-----------
Unit tests  are validated.
Checklist:
----------
Related Issue
-----------
Issue #771 

Enable both ipconfigUSE_IPv6 ipconfigUSE_IPv4 while building

---

source/FreeRTOS_DNS_Parser.c

Description
-----------
Fix MISRA issues : 
MISRA C-2012 Rule 2.2 -  variable was declared but never referenced
MISRA C-2012 Directive 4.6 - Using basic numerical type "int" rather than a typedef that includes size and signedness information.
Test Steps
-----------
Run Coverity.
Checklist:
----------

Fix 2.2 and 4.6 MISRA violation

---

source/include/FreeRTOSIPConfigDefaults.h
source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c

Description
-----------
This PR fixes build issues with the network interface file of the STM32F4 port. 
Also, moves the default configuration for `ipconfigUSE_DHCPv6` outside of `ipconfigUSE_TCP` enabled check.
Test Steps
-----------
Unit tests and hardware test on STM32F4.
Checklist:
----------
Related Issue
-----------
Issue #767 
Issue #770 

Fix build issue with network interface of STM32F4

---

source/FreeRTOS_DHCPv6.c
test/build-combination/Common/main.c

Description
-----------
Fix compilation issue for ipconfigIPv4_BACKWARD_COMPATIBLE and ipconfigUSE_DHCPv6.
Test Steps
-----------
```
'cmake -S test/build-combination -B test/build-combination/build/ -DTEST_CONFIGURATION=ENABLE_ALL'
'make -C test/build-combination/build/'
```
Checklist:
----------

Fix compilation when ipconfigIPv4_BACKWARD_COMPATIBLE is enabled

---

source/include/FreeRTOS_IP.h
test/CMakeLists.txt
test/unit-test/CMakeLists.txt

Description
-----------
Remove add_subdirectory( cbmc ) call
CBMC proofs cannot currently be run using CMake.
Checklist:
----------
Related Issue
-----------
fixes #753 

cmake: Remove add_subdirectory( cbmc ) call

---

CMakeLists.txt
source/CMakeLists.txt
source/FreeRTOS_IP.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_UDP_IP.c
source/portable/BufferManagement/BufferAllocation_2.c
test/build-combination/Common/FreeRTOSConfig.h

Description
-----------
Corrects warnings with current GCC flags
for GCC 7.5.0. The only suppressed warning pertains to function to object pointer conversion which is
required and common for socket callbacks.
Test Steps
-----------
Performed all three variations of the `build-check` builds on an 18.04 ubuntu machine
Checklist:
----------
Will need to sync with library owners. I'm not familiar with running additional tests.
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/558

Correct GCC warnings

---

.github/lexicon.txt
CMakeLists.txt
source/CMakeLists.txt
source/FreeRTOS_ARP.c
source/FreeRTOS_DHCP.c
source/FreeRTOS_DNS.c
source/FreeRTOS_DNS_Cache.c
source/FreeRTOS_DNS_Networking.c
source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_ICMP.c
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Timers.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_Stream_Buffer.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_Reception.c
source/FreeRTOS_TCP_State_Handling.c
source/FreeRTOS_TCP_Transmission.c
source/FreeRTOS_TCP_Utils.c
source/FreeRTOS_TCP_WIN.c
source/FreeRTOS_Tiny_TCP.c
source/FreeRTOS_UDP_IP.c
source/include/FreeRTOS_DHCP.h
source/include/FreeRTOS_IP_Private.h
test/build-combination/Common/FreeRTOSConfig.h
test/unit-test/FreeRTOS_IP_Utils/FreeRTOS_IP_Utils_utest.c

Description
-----------
Fixes `-Wall`, `-Wextra` and `-Weverything` warnings. Fixes the majority of `-Wpedantic` warnings as well, however a few couldn't be corrected AND pedantic isn't officially supported in this library.
Heavily inspired by @phelter and his changes found [here](https://github.com/phelter/FreeRTOS-Plus-TCP/tree/feature/fixing-clang-gnu-compiler-warnings)
Test Steps
-----------
* Ran build checks locally on my Ubunto 18.04 instance with GCC 7.5.0.
Checklist:
----------
- [ x ] I have tested my changes. No regression in existing tests.
- [ x ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Second point is non-applicable.
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/558
By submitting this pull …

Fix Clang warnings

---

source/FreeRTOS_Sockets.c
source/FreeRTOS_UDP_IPv6.c

Discard UDPv6 with zero checksum.
Description
-----------
Refer to [RFC2460 - section 8.1](https://www.rfc-editor.org/rfc/rfc2460#section-8.1), the UDPv6 packets containing a zero checksum must be discarded:
```
Unlike IPv4, when UDP packets are originated by an IPv6 node,
the UDP checksum is not optional.  That is, whenever
originating a UDP packet, an IPv6 node must compute a UDP
checksum over the packet and the pseudo-header, and, if that
computation yields a result of zero, it must be changed to hex
FFFF for placement in the UDP header.  IPv6 receivers must
discard UDP packets containing a zero checksum, and should log
the error.
```
Test Steps
-----------
Run protocol test case UDP/checksum/004 with traffic source udp.v6.
Checklist:
----------
Related Issue
-----------
By submitting …

Discard UDPv6 with zero checksum.

---

.github/workflows/ci.yml
.github/workflows/uncrustify.yml

Description
-----------
This PR updates the docker version to use ubuntu:18.04 to run uncrustify commands.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Uncrustify jobs failing to start/cancelled.

Uncrustify version issue fix

---

.github/lexicon.txt
.github/workflows/ci.yml
.github/workflows/uncrustify.yml
source/FreeRTOS_IPv6.c

Description
-----------
This PR updates the verification of order of extension headers appearing in the IPv6 header as per RFC 2460 section [4.1](https://www.rfc-editor.org/rfc/rfc2460#section-4.1)  Extension Header Order:
>  IPv6 nodes must accept and attempt to process extension headers in
any order and occurring any number of times in the same packet,
except for the Hop-by-Hop Options header which is restricted to
appear immediately after an IPv6 header only.
Test Steps
-----------
Protocol tests
Checklist:
----------

[IPv6] Verify options order in IPv6 Extension Headers

---

.github/workflows/uncrustify.yml
source/FreeRTOS_ARP.c

Description
-----------
This PR updates the uncrustify bot run yml file to use the latest syntax instead of the deprecated set-output command and uses latest git.
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Checklist:
----------

Removing deprecated set-output command from uncrustify bot run yml

---

source/FreeRTOS_IPv6.c
source/FreeRTOS_ND.c
source/FreeRTOS_Sockets.c
source/include/FreeRTOS_IPv6.h

[IPv6] Check unspecified/loopback/multicast reserved/matching addresses in prvAllowIPPacketIPv6.
Description
-----------
From [RFC 4291](https://www.rfc-editor.org/rfc/rfc4291.html), some IPv6 addresses are reserved and shouldn't be used. Drop packets when the address met below conditions:
1. Source or destination address have unspecified address (All 0s).
2. Check endpoint's IP address with packet's destination.
3. Allow loopback packets from this node itself only.
4. Check if multicase address isn't valid. (Refer to [sec 2.7](https://www.rfc-editor.org/rfc/rfc4291.html#section-2.7) in RFC4291)
5. Fix coverity warnings.
Test Steps
-----------
Run protocol tests UDP/Others/003, UDP/Others/004, IPv6/datagram/010~017, 019.
Checklist:
----------
Related Issue
-----------
By submitting this …

[IPv6] Check unspecified/loopback/multicast reserved/matching addresses in prvAllowIPPacketIPv6.

---

test/Coverity/ConfigFiles/FreeRTOSConfig.h
test/build-combination/Common/FreeRTOSConfig.h
test/cbmc/patches/FreeRTOSConfig.h
test/unit-test/ConfigFiles/FreeRTOSConfig.h
test/unit-test/FreeRTOS_ICMP_wo_assert/FreeRTOSConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig/FreeRTOSConfig.h
test/unit-test/FreeRTOS_IP_Utils_DiffConfig/FreeRTOSConfig.h
test/unit-test/FreeRTOS_Sockets_DiffConfig/FreeRTOSConfig.h
test/unit-test/FreeRTOS_Sockets_DiffConfig1/FreeRTOSConfig.h
test/unit-test/FreeRTOS_TCP_IP_DiffConfig/FreeRTOSConfig.h

Description
-----------
The coroutines are disabled in the FreeRTOS config files used for building the unit tests and other tools.
Test Steps
-----------
Build the unit tests.
Checklist:
----------
Related Issue
-----------
Error message in the unit test build.

Remove coroutine warnings from the unit test build logs

---

source/FreeRTOS_BitConfig.c
source/FreeRTOS_DHCPv6.c
source/FreeRTOS_Routing.c
source/include/FreeRTOS_BitConfig.h
source/include/FreeRTOS_DHCP.h

[IPv6] Check client DUID in prvDHCPv6_handleOption.
Description
-----------
Refer to RFC3315 - sec 15.3, we need to discard packets with following conditions:
- the message does not include a Server Identifier option.
- the message does not include a Client Identifier option.
- the contents of the Client Identifier option does not match the client's DUID.
- the "transaction-id" field value does not match the value the client used in its Solicit message.
Test Steps
-----------
Run test case DHCPv6/005.
Checklist:
----------
Related Issue
-----------

[IPv6] Check client DUID in prvDHCPv6_handleOption.

---

.github/lexicon.txt
source/FreeRTOS_DHCPv6.c
source/include/FreeRTOS_DHCPv6.h
test/Coverity/Portable.c

[IPv6] Check option length in DHCPv6.
Description
-----------
- Refer to RFC3315 - sec 22.4, the length of IA_NA should never less than 12.
- Refer to RFC3315 - sec 22.5, the length of IA_TA should never less than 4.
- Refer to RFC3315 - sec 22.6, the length of IA_Addr should never less than 24.
- Refer to RFC3315 - sec 22.8, the length of Preference should never less than 1.
- Refer to RFC3315 - sec 22.13, the length of Status Code should never less than 12.
- Refer to RFC3633 - sec 9, the length of IA_PD should never less than 12.
- Refer to RFC3633 - sec 10, the length of IA_Prefix should never less than 25.
- Check if option length in IA_NA option is valid by checking if its length >= 4 (for option code ID and length).
Test Steps
-----------
Run protocol test case DHCPC 007~010. …

[IPv6] Check option length in DHCPv6.

---

source/FreeRTOS_DHCPv6.c

[IPv6] added client DUID check back.
Description
-----------
After merging, some parts of DUID check is gone. Add them back.
Test Steps
-----------
Run test case IPv6/DHCPC/005~006.
Checklist:
----------
Related Issue
-----------

[IPv6] added client DUID check back.

---

source/FreeRTOS_IPv6.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP_IPV4.c

Description
-----------
Add changes for Coverity error of 10.8, 8.13 and 8.9.
Test Steps
-----------
```
cmake -S . -B build -DFREERTOS_PLUS_TCP_TEST_CONFIGURATION=ENABLE_ALL
cmake --build build --target freertos_plus_tcp_build_test
```
Checklist:
----------
Related Issue
-----------

Fix 10.8, 8.13 and 8.9 MISRA violation

---

source/FreeRTOS_IPv6.c

Description
-----------
This PR suppresses the MISRA Rule 8.9 [An object should be defined at block scope if its identifier only appears in a single function] during the Coverity scan. 
Test Steps
-----------
Coverity run
Checklist:
----------
Related Issue
-----------

Supress MISRA single use warning for FreeRTOS_in6addr_loopback

---

source/FreeRTOS_ND.c

[IPv6] Fill in endpoint address for neighbor solicitation.
Description
-----------
We use FE80::1 as source address in NS message. Replace it with endpoint's address.
Test Steps
-----------
- Run [IPv6 demo](https://github.com/FreeRTOS/FreeRTOS/tree/devIPv6/FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_IPv6_Demo/IPv6_Multi_WinSim_demo).
- Pass protocol test.
Checklist:
----------
Related Issue
-----------

[IPv6] Fill in endpoint address for neighbor solicitation.

---

tools/tcp_utilities/plus_tcp_demo_cli.c

Description
-----------
Some compilers do not support __attribute__( ( weak ) ) for a weak function declaration. Hence updating the weak function declaration.
Test Steps
-----------
IPv6 Demo Compilation.
Checklist:
----------
Related Issue
-----------

Update IPv6 Demo compilation issue

---

source/FreeRTOS_ARP.c

Description
-----------
In FreeRTOS_ARP.c, when an IPv6 address is looked up, a new network buffer is created, so it can be passed to `vNDSendNeighbourSolicitation()`. Mentioned function wants to have the ownership of the buffer.
The code looked all right, except that the wrong buffer was passed:
~~~diff
if( pxTempBuffer != NULL )
{
pxTempBuffer->pxEndPoint = pxNetworkBuffer->pxEndPoint;
pxTempBuffer->pxInterface = pxNetworkBuffer->pxInterface;
-        vNDSendNeighbourSolicitation( pxNetworkBuffer, pxIPAddress );
+        vNDSendNeighbourSolicitation( pxTempBuffer, pxIPAddress );
}
~~~
Test Steps
-----------
The problem can be triggered when receiving a TCP or an UDP packet from a link/local address.
I described the above change already in bigger PRs, but they never got merged. …

dev/int: pass correct networkbuffer to vNDSendNeighbourSolicitation

---

.github/lexicon.txt
source/FreeRTOS_IPv6.c
test/unit-test/CMakeLists.txt
test/unit-test/FreeRTOS_IPv6/FreeRTOSConfig.h
test/unit-test/FreeRTOS_IPv6/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IPv6/FreeRTOS_IPv6_list_macros.h
test/unit-test/FreeRTOS_IPv6/FreeRTOS_IPv6_stubs.c
test/unit-test/FreeRTOS_IPv6/FreeRTOS_IPv6_utest.c
test/unit-test/FreeRTOS_IPv6/ut.cmake
test/unit-test/FreeRTOS_IPv6_Driver_Check_Checksum/FreeRTOSConfig.h
test/unit-test/FreeRTOS_IPv6_Driver_Check_Checksum/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IPv6_Driver_Check_Checksum/FreeRTOS_IPv6_Driver_Check_Checksum_list_macros.h
test/unit-test/FreeRTOS_IPv6_Driver_Check_Checksum/FreeRTOS_IPv6_Driver_Check_Checksum_utest.c
test/unit-test/FreeRTOS_IPv6_Driver_Check_Checksum/ut.cmake
test/unit-test/TCPFilePaths.cmake

[IPv6] Add Unit Test for FreeRTOS_IPv6.
Description
-----------
As the FreeRTOS_IPv6 was added for merging IPv4 and IPv6, this change adds the Unit test case for this new file along with 100% coverage.
Test Steps
-----------
Unit Test
```
```
Coverage Test
```
```
Checklist:
----------
Related Issue
-----------

[IPv6] Add Unit Test for FreeRTOS_IPv6.

---

.github/lexicon.txt
source/FreeRTOS_UDP_IPv6.c
test/unit-test/CMakeLists.txt
test/unit-test/FreeRTOS_UDP_IPv6/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_UDP_IPv6/FreeRTOS_UDP_IPv6_list_macros.h
test/unit-test/FreeRTOS_UDP_IPv6/FreeRTOS_UDP_IPv6_stubs.c
test/unit-test/FreeRTOS_UDP_IPv6/FreeRTOS_UDP_IPv6_utest.c
test/unit-test/FreeRTOS_UDP_IPv6/ut.cmake
test/unit-test/TCPFilePaths.cmake

[IPv6] Add Unit Test for FreeRTOS_UDP_IPv6.
Description
-----------
Separate FreeRTOS_UDP_IPv6.c unit test cases and add test cases to reach 100% coverage.
Test Steps
-----------
Unit Test
```
```
Coverage Test
```
```
Checklist:
----------
Related Issue
-----------

[IPv6] Add Unit Test for FreeRTOS_UDP_IPv6.

---

test/unit-test/FreeRTOS_TCP_Reception/FreeRTOS_TCP_Reception_utest.c

Description
-----------
Add coverage for FreeRTOS_TCP_Reception
Test Steps
-----------
Unit Test
```
```
Coverage Test
```
```
Checklist:
----------
Related Issue
-----------

Add coverage for FreeRTOS_TCP_Reception

---

source/FreeRTOS_TCP_Utils_IPV6.c
test/unit-test/CMakeLists.txt
test/unit-test/FreeRTOS_TCP_Utils_IPV6/FreeRTOS_TCP_Utils_IPV6_utest.c
test/unit-test/FreeRTOS_TCP_Utils_IPV6/ut.cmake
test/unit-test/FreeRTOS_TCP_Utils_IPV6_ConfigLowTCPMSS/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_TCP_Utils_IPV6_ConfigLowTCPMSS/FreeRTOS_TCP_Utils_IPV6_ConfigLowTCPMSS_utest.c
test/unit-test/FreeRTOS_TCP_Utils_IPV6_ConfigLowTCPMSS/ut.cmake
test/unit-test/TCPFilePaths.cmake

[IPv6] Add Unit Test for FreeRTOS_TCP_Utils_IPV6.
Description
-----------
Add unit test cases to reach 100% coverage for FreeRTOS_TCP_Utils_IPV6.c.
Test Steps
-----------
Unit Test
```
```
Coverage Test
```
```
Checklist:
----------
Related Issue
-----------

[IPv6] Add Unit Test for FreeRTOS_TCP_Utils_IPV6

---

test/unit-test/FreeRTOS_TCP_Transmission_IPV6/FreeRTOS_TCP_Transmission_IPV6_stubs.c
test/unit-test/FreeRTOS_TCP_Transmission_IPV6/FreeRTOS_TCP_Transmission_IPV6_utest.c

Description
-----------
Update TCP_Transmission_IPV6 unit test to use correct ethernet buffer
Test Steps
-----------
Unit Test
```
```
Coverage Test
```
```
Checklist:
----------
Related Issue
-----------

Update TCP_Transmission_IPV6 unit test

---

source/include/FreeRTOS_IP_Private.h

Description
-----------
long long and unsigned long long aka uint64_t are not part of the C90 standard, hence updating its usage.
uint64_t ullAlignmentWord is updated to uint32_t ullAlignmentWord - to make the packet 32-bit aligned.
uint64_t ullTCPAlignment - Is removed as it is no longer needed.
Test Steps
-----------
Compilation.
Checklist:
----------
Related Issue
-----------

Update usage of uint64_t according to C90 standard

---

source/portable/Compiler/CCS/pack_struct_end.h
source/portable/Compiler/CCS/pack_struct_start.h

Fix issue in the CCS compiler pragma to pack structs.
Description
-----------
`#pragma pack(1)` would make it so that all structs inserted after `pack_struct_start.h` was included for the TI arm compiler would be packed leading to potential unaligned memory access error. 
Refer: https://www.ti.com/lit/ug/spnu151w/spnu151w.pdf SECTION 5.11.23
Checklist:
----------

fix: CCS compiler pragma for packing structs was incorrect

---

test/cbmc/proofs/TCP/prvTCPHandleState/Makefile.json

[IPv6] Add CBMC test for prvCheckRxData and prvStoreRxData together with prvTCPHandleState.
Description
-----------
- Add CBMC test for prvCheckRxData and prvStoreRxData together with prvTCPHandleState. 
Test Steps
-----------
```
cd test/cbmc/proof/
python3 prepare.py
cd test_case
make
```
Checklist:
----------
Related Issue
-----------

[IPv6] Add CBMC test for prvCheckRxData and prvStoreRxData together with prvTCPHandleState.

---

.github/lexicon.txt
test/cbmc/proofs/ICMP/ProcessICMPEchoRequest/Makefile.json
test/cbmc/proofs/ICMP/ProcessICMPEchoRequest/ProcessICMPEchoRequest_harness.c
test/cbmc/proofs/ICMP/ProcessICMPPacket/Makefile.json
test/cbmc/proofs/ICMP/ProcessICMPPacket/ProcessICMPPacket_harness.c

Description
-----------
This PR adds CBMC proofs for the following ICMP functions:
- ProcessICMPPacket
- prvProcessICMPEchoReply
- prvProcessICMPEchoRequest
Test Steps
-----------
Ran CBMC on the proofs
Checklist:
----------
Related Issue
-----------

Add CBMC proof for ICMP functions

---

.github/lexicon.txt
test/cbmc/proofs/IP/ConsiderFrameForProcessing/ConsiderFrameForProcessing_harness.c
test/cbmc/proofs/IP/ConsiderFrameForProcessing/Makefile.json
test/cbmc/proofs/IP/HandleEthernetPacket/HandleEthernetPacket_harness.c
test/cbmc/proofs/IP/HandleEthernetPacket/Makefile.json
test/cbmc/proofs/IP/ProcessEthernetPacket/Makefile.json
test/cbmc/proofs/IP/ProcessEthernetPacket/ProcessEthernetPacket_harness.c

Description
-----------
This PR adds CBMC proof to:
- `ProcessEthernetPacket()` 
- `ConsiderFrameForProcessing()`
- `prvHandleEthernetPacket()`
Test Steps
-----------
```
cd test/cbmc/proof/
python3 prepare.py
cd <test_case>
make
```
Checklist:
----------
Related Issue
-----------

Adding CBMC proof for IP

---

source/FreeRTOS_RA.c
test/cbmc/proofs/RA/vReceiveRA/Makefile.json
test/cbmc/proofs/RA/vReceiveRA/ReceiveRA_harness.c
test/cbmc/proofs/RA/vReceiveRA_ReadReply/Makefile.json
test/cbmc/proofs/RA/vReceiveRA_ReadReply/ReceiveRA_ReadReply_harness.c
test/unit-test/FreeRTOS_RA/FreeRTOS_RA_utest.c

Description
-----------
Add CBMC proof for following functions : 
vReceiveRA_ReadReply
vReceiveRA
Also validates : 
FreeRTOS_FirstEndPoint
FreeRTOS_NextEndPoint
vRAProcess
xRAProcess_HandleOtherStates - Partially
xRAProcess_HandleWaitStates - Partially
Test Steps
-----------
```
python prepare.py
make
```
Checklist:
----------
Related Issue
-----------

Add CBMC proof for IPv6 FreeRTOS_RA functions

---

test/cbmc/proofs/Routing/MatchingEndpoint/Makefile.json
test/cbmc/proofs/Routing/MatchingEndpoint/MatchingEndpoint_harness.c

Description
-----------
Add CBMC proof for following functions :
FreeRTOS_MatchingEndpoint
pxEasyFit
Also validates :
xIPv6_GetIPType
FreeRTOS_FirstEndPoint
FreeRTOS_NextEndPoint
Test Steps
-----------
```
python prepare.py
make
```
Checklist:
----------
Related Issue
-----------

Add CBMC proof for IPv6 FreeRTOS_Routing functions

---

test/cbmc/proofs/xRecv_Update_IPv4/Makefile.json
test/cbmc/proofs/xRecv_Update_IPv4/xRecv_Update_IPv4_harness.c

[IPv6] Add CBMC test for xRecv_Update_IPv4.
Description
-----------
- Add CBMC test cases for the function xRecv_Update_IPv4.
Test Steps
-----------
```
cd test/cbmc/proof/
python3 prepare.py
cd test_case
make
```
Checklist:
----------
Related Issue
-----------

[IPv6] Add CBMC test for xRecv_Update_IPv4

---

test/cbmc/proofs/TCP/prvSendData/Makefile.json
test/cbmc/proofs/TCP/prvSendData/SendData_harness.c

Description
-----------
Add CBMC proof for prvSendData.
This also proofs the following sub-function :
prvTCPReturnPacket
Test Steps
-----------
```
cd test/cbmc/proof/
python3 prepare.py
cd test_case
make
```
Checklist:
----------
Related Issue
-----------

Add CBMC proof for prvSendData

---

source/FreeRTOS_ND.c
source/FreeRTOS_TCP_Transmission.c
source/FreeRTOS_TCP_WIN.c

Description
-----------
This change fixes warnings which appear on disabling the macro ipconfigUSE_TCP_WIN
This PR is a fix for the [customer reported issue](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/930)
Test Steps
-----------
Run the [Echo Posix Demo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_Echo_Posix) with warnings enabled , the demo runs successfully without these warnings
Checklist:
----------
Related Issue
-----------

Fix warnings on disable USETCP_WIN macro

---

source/portable/NetworkInterface/DriverSAM/NetworkInterface.c

Description
-----------
This PR reverts back the [solicited node multicast MAC](https://en.wikipedia.org/wiki/Solicited-node_multicast_address) address generation for each endpoint in DriverSAM port, which was previously updated as IPv6 multicast MAC address.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

DriverSAM: revert solicited-node multicast MAC address generation

---

source/FreeRTOS_IPv6.c

[IPv6] Revert PR#927 "Allow buffer length to be greater than IP packet in IPv6"
Description
-----------
Revert #927 because we're failing one critical test case in protocol tester.
Test Steps
-----------
Run test case IPv6/Datagram/009
Checklist:
----------
Related Issue
-----------

[IPv6] Revert "Allow buffer length to be greater than IP packet in IPv6"

---

.github/lexicon.txt
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_IPv6.c
source/FreeRTOS_IPv6_Utils.c
source/FreeRTOS_ND.c
source/FreeRTOS_RA.c
source/include/FreeRTOS_IPv6_Utils.h
test/cbmc/proofs/IPUtils/usGenerateProtocolChecksum_IPv6/Makefile.json
test/cbmc/proofs/IPUtils/usGenerateProtocolChecksum_IPv6/usGenerateProtocolChecksum_IPv6_harness.c
test/cbmc/proofs/parsing/ProcessIPPacket_IPv6/eHandleIPv6ExtensionHeaders/Makefile.json
test/cbmc/proofs/prvChecksumIPv6Checks/Makefile.json
test/unit-test/FreeRTOS_IPv6/FreeRTOS_IPv6_utest.c
test/unit-test/FreeRTOS_IPv6/ut.cmake
test/unit-test/FreeRTOS_IPv6_Utils/FreeRTOS_IPv6_Utils_stubs.c
test/unit-test/FreeRTOS_IPv6_Utils/FreeRTOS_IPv6_Utils_utest.c
test/unit-test/FreeRTOS_IPv6_Utils/ut.cmake
test/unit-test/FreeRTOS_ND/FreeRTOS_ND_utest.c

[IPv6] Fix checksum calculation of IPv6 with extension headers- RFC 2460 section 4.1
Description
-----------
With this change, FreeRTOS-Plus-TCP supports to calculate checksum for IPv6 packets with IPv6 extension headers.
Test Steps
-----------
Pass IPv6 TCP/UDP/ICMP checksum test cases with this change.
Checklist:
----------
Related Issue
-----------

[IPv6] Fix checksum calculation of IPv6 with extension headers.

---

source/portable/NetworkInterface/linux/NetworkInterface.c

Description
-----------
This PR adds port specific version of pxFillInterfaceDescriptor (enabled only on `( ipconfigIPv4_BACKWARD_COMPATIBLE == 1 )`) to the Linux pcap port. 
Test Steps
-----------
Tested with posix +TCP echo demo with `( ipconfigIPv4_BACKWARD_COMPATIBLE == 1 )` and `( ipconfigIPv4_BACKWARD_COMPATIBLE == 0 )`
Checklist:
----------
Related Issue
-----------

Linux port update to have port specific version of pxFillInterfaceDescriptor

---

source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c

Description
-----------
This PR fixes the build for STM32H port
Test Steps
-----------
Tested with HW demo.
Checklist:
----------
Related Issue
-----------

Fix for STM32H port - IPv6 MAC filter and build 

---

source/FreeRTOS_UDP_IPv6.c

I just ran into what appears to be a simple oversight.. maybe someone forgot to copy/paste the mDNS code from v4 to v6
Until this code was added in, my xApplicationDNSQueryHook_Multi() was not getting called at all for IPv6 packets.
Please verify as this was a quick and dirty fix on my end and I may be missing something.

Fixes mDNS over IPv6.

---

source/include/FreeRTOSIPConfigDefaults.h

Remove duplicate configurations
Description
-----------
- Remove duplicate configurations in FreeRTOSIPConfigDefault.h
- ipconfigIP_TASK_PRIORITY
- ipconfigIP_TASK_STACK_SIZE_WORDS
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Remove duplicate configurations

---

source/include/FreeRTOS_ARP.h
source/include/FreeRTOS_DHCP.h
source/include/FreeRTOS_DHCPv6.h
source/include/FreeRTOS_DNS.h
source/include/FreeRTOS_DNS_Callback.h
source/include/FreeRTOS_ICMP.h
source/include/FreeRTOS_IP.h
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_IP_Timers.h
source/include/FreeRTOS_IP_Utils.h
source/include/FreeRTOS_IPv4.h
source/include/FreeRTOS_IPv4_Private.h
source/include/FreeRTOS_IPv4_Sockets.h
source/include/FreeRTOS_IPv4_Utils.h
source/include/FreeRTOS_IPv6.h
source/include/FreeRTOS_IPv6_Private.h
source/include/FreeRTOS_IPv6_Sockets.h
source/include/FreeRTOS_IPv6_Utils.h
source/include/FreeRTOS_ND.h
source/include/FreeRTOS_Routing.h
source/include/FreeRTOS_Sockets.h
source/include/FreeRTOS_UDP_IP.h
source/portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.h
source/portable/NetworkInterface/Zynq/x_emacpsif.h
source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif.h
test/unit-test/ConfigFiles/portmacro.h
tools/tcp_utilities/include/date_and_time.h

Description
-----------
* C++ supports function overloading so while generating object code – it changes names by adding information about arguments and C does not support function overloading.
* So, when we link a C code in C++, we have to make sure that name of a symbol is not changed.
* If a header is missing the extern-C we might have 2 definitions of the same function - one for extern-C style and one for native Cpp mangled name.
Hence updated the use of extern C block post all the header includes.
Test Steps
-----------
Build check.
Checklist:
----------
Related Issue
----------
Reported in [Issue 959](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/959)
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …

Fix use of extern C block

---

CMakeLists.txt
source/FreeRTOS_ARP.c
source/FreeRTOS_BitConfig.c
source/FreeRTOS_DHCP.c
source/FreeRTOS_DHCPv6.c
source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_IPv4.c
source/FreeRTOS_IPv4_Utils.c
source/FreeRTOS_IPv6.c
source/FreeRTOS_IPv6_Sockets.c
source/FreeRTOS_IPv6_Utils.c
source/FreeRTOS_Routing.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_Reception.c
source/FreeRTOS_TCP_Utils_IPV6.c
source/FreeRTOS_TCP_WIN.c
source/portable/NetworkInterface/Common/phyHandling.c
source/portable/NetworkInterface/linux/NetworkInterface.c
test/build-combination/Common/main.c

Description
-----------
Add -Wconversion flag in CMakeLists.txt and fix warnings generated by this flag.
Test Steps
-----------
Built FreeRTOS-Plus-TCP locally.
Description
-----------
Add -Wconversion flag in CMakeLists.txt and fix warnings generated by this flag.
Test Steps
-----------
Compile and build project with -Wconversion enabled.
Checklist:
----------

Add and fix -Wconversion errors

---

source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/include/FreeRTOS_IPv4_Private.h
source/include/FreeRTOS_IPv6_Private.h

Description
-----------
This is the same PR as #946 I have squashed all commits and improved a comment or two. In my original PR, @kstribrnAmzn made some indentation changes. I've decided not to carry these because they were affecting code I have not touched and I'm trying to keep this PR as clean as possible.

Improves the calculation of the offset at which we store the IP version value

---

source/FreeRTOS_DNS_Callback.c
source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_ICMP.c
source/FreeRTOS_TCP_Transmission_IPV4.c
source/FreeRTOS_UDP_IPv4.c
source/include/FreeRTOS_DNS_Callback.h
test/build-combination/AllEnable/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv4/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv4_IPv6/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv4_TCP/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv6/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv6_TCP/FreeRTOSIPConfig.h
test/build-combination/Header_Self_Contain/FreeRTOSIPConfig.h
tools/tcp_utilities/plus_tcp_demo_cli.c

Description
-----------
This PR updates the call to `xDNSDoCallback` with correct arguments, as `xDNSDoCallback` takes `struct freertos_addrinfo *` as argument instead of `uin32_t` IPv4 address.
Test Steps
-----------
Tested with DNS callback enabled.
Checklist:
----------
- ~[ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.~ NA
Related Issue
-----------

DNS callback to use new xDNSDoCallback API

---

source/FreeRTOS_DHCPv6.c
test/unit-test/FreeRTOS_DHCPv6/FreeRTOS_DHCPv6_utest.c

Create IPv6 socket for DHCPv6 flow.
Description
-----------
When ipconfigUSE_IPv4 is set to 0, FREERTOS_AF_INET is not allowed to used in FreeRTOS_Socket.
Change it to FREERTOS_AF_INET6 as we're running DHCPv6.
Test Steps
-----------
Run protocol tester IPv6/DHCPC.
Checklist:
----------
Related Issue
-----------

Create IPv6 socket for DHCPv6 flow

---

source/FreeRTOS_ARP.c
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c

Description
-----------
This PR updates the Gratuitous ARP processing with more checks including verification of the packet for target hardware address and the subnet of the protocol address.
Test Steps
-----------
Jenkins and HW demo run.
Checklist:
----------
Related Issue
-----------

Gratuituous ARP fixes 

---

source/portable/NetworkInterface/libslirp/MBuffNetworkInterface.c

Update function names in libslirp interface.
Description
-----------
The function names in `source/portable/NetworkInterface/libslirp/MBuffNetworkInterface.c` is not aligned with other interfaces. Update the function name in this file.
Test Steps
-----------
Execute [FreeRTOS_Plus_TCP_Echo_Posix](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_Echo_Posix) in FreeRTOS repo.
Checklist:
----------
Related Issue
-----------

Update function names in libslirp interface.

---

source/portable/NetworkInterface/LPC17xx/README.md
source/portable/NetworkInterface/LPC18xx/README.md
source/portable/NetworkInterface/LPC54018/README.md
source/portable/NetworkInterface/M487/README.md
source/portable/NetworkInterface/SH2A/README.md
source/portable/NetworkInterface/TM4C/README.md
source/portable/NetworkInterface/ThirdParty/MSP432/README.md
source/portable/NetworkInterface/esp32/README.md
source/portable/NetworkInterface/mw300_rd/README.md
source/portable/NetworkInterface/pic32mzef/README.md

Description
-----------
Add readme for the ports which we have not validated with IPv6/Multi Interface support.
Test Steps
-----------
Checklist:
----------
- [NA] I have tested my changes. No regression in existing tests.
- [NA] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------

Add README for ports

---

source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_IPv4.c
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_IP_Utils.h
source/include/FreeRTOS_IPv4.h

Fix MISRA violations Rule 1.1 for forward declaration
Description
-----------
Some violations are found because of forward declaration.
Resolved by changing typedef by declaring the type only.
Update all functions who using these type in changed header files.
Test Steps
-----------
- Coverity violations of Rule 1.1 are solved.
- All build checks are passed
Checklist:
----------
Related Issue
-----------

Fix MISRA violations Rule 1.1 for forward declaration

---

source/FreeRTOS_DHCP.c
source/FreeRTOS_IP.c
source/include/FreeRTOS_DHCP.h
source/include/FreeRTOS_IP_Private.h

This PR removes the xNetworkAddressing and  xDefaultAddressing structs as they appear to be obsolete.
I can also extend this PR by removing any use of NetworkAddressingParameters_t from the unit-tests. I'm not very comfortable with modifying unit-tests, but this seems like a simple change.
Let me know if you think it's a good idea or if I should leave the unit-tests alone.
Checklist:
----------
Related Issue
-----------
none

Cleanup of some obsolete config structs

---

source/FreeRTOS_Sockets.c
source/include/FreeRTOS_Sockets.h
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c

Description
-----------
This PR updates the `FreeRTOS_get_tx_head()` to create the TCP transmit stream if it wasn't created for the passed socket already. If a previous attempt to create the stream failed then `pxSocket->u.xTCP.bits.bMallocError` should be `pdTRUE`, in that case another attempt won't be made.
Test Steps
-----------
Tested with hardware demo (with TCP zero copy).
Checklist:
----------
Related Issue
-----------

Update FreeRTOS_get_tx_head to create TX stream if not created already

---

source/portable/NetworkInterface/TM4C/NetworkInterface.c

Use GCC-compatible alignment specifier in TM4C NetworkInterface.c
Description
-----------
Replace the CCS-only pragma with GCC attribute. Fixing this along with issue #1206 will make this file build without warnings on the ARM GNU toolchain.
The CCS compiler does support this attribute and the manual states that DATA_ALIGN pragma is equivalent to the aligned attribute. https://www.ti.com/lit/ug/spnu151w/spnu151w.pdf?ts=1695011722091
Test Steps
-----------
- Compile an application without the change, save the binary somewhere
- Compile with this change, but with an extra newline after the declaration to ensure `__LINE__` has the same value in each `configASSERT` statement
Check that the two binaries are identical.
Checklist:
----------
Related Issue
-----------
N/A
By submitting this pull …

Use GCC-compatible alignment specifier in TM4C NetworkInterface.c

---

source/portable/NetworkInterface/loopback/loopbackNetworkInterface.c

Description
-----------
In the earlier IPv4-only library, there has been a loopback functionality. It needed adaptation to the network interface: outgoing packets for 127.0.0.0 would be passed back to the IP-task.
The current implementation will add a new Loopback interface. It will make sure that all "outgoing" packets will be bounced back to the IP-task. The interface will get two endpoint: one for IPv4 and one for IPv6.
Test Steps
-----------
I created a demo that starts at most 4 tasks: UDPv4, UDPv6, TCPv4, and TCPv6. Each task opens two sockets that will connect and exchanges data packets.
Checklist:
----------
Related Issue
-----------
As for now, the driver needs the changes from [PR #1020](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/1020).
By submitting this pull request, I …

The new loopback network interface

---

source/portable/NetworkInterface/TM4C/NetworkInterface.c

Description
-----------
PR for bug in https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/1026
Have not tested, just made a PR with the fix suggested in the issue.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/1026

Fix uninitialized variable in TM4C NetworkInterface.c

---

source/include/FreeRTOS_Sockets.h
source/portable/NetworkInterface/WinPCap/NetworkInterface.c
source/portable/NetworkInterface/linux/NetworkInterface.c

Description
-----------
I would like to change the following code found in two network interfaces:
~~~diff
-    ulNetMask = ( configNET_MASK3 << 24UL ) | ( configNET_MASK2 << 16UL ) | ( configNET_MASK1 << 8L ) | configNET_MASK0;
+    ulNetMask = FreeRTOS_inet_addr_quick( configNET_MASK0, configNET_MASK1, configNET_MASK2, configNET_MASK3 );
~~~
Note that `FreeRTOS_inet_addr_quick()` will look at the endianness before shifting. The current expressions do not.
Also I'd like to propose some change to the macro `FreeRTOS_inet_addr_quick()`:
~~~diff
#define FreeRTOS_inet_addr_quick( ucOctet0, ucOctet1, ucOctet2, ucOctet3 )     \
-    ( ( ( ( uint32_t ) ( ucOctet3 ) ) << 24UL ) |                                  \
-      ( ( ( uint32_t ) ( ucOctet2 ) ) << 16UL ) | …

Make use of FreeRTOS_inet_addr_quick() when applicable

---

source/include/FreeRTOS_IPv4_Sockets.h
source/include/FreeRTOS_Sockets.h

Description
-----------
This PR updates the sockets header file with declarations for ntop/pton IPv4/v6 API declarations.
Test Steps
-----------
Build combination checks
Checklist:
----------
Related Issue
-----------
Implicit declaration warnings if `FreeRTOS_IPv4_Sockets.h` is not included specificaly.

Update sockets header to include ntop/pton IPv4/v6 API declarations

---

source/FreeRTOS_ARP.c
source/FreeRTOS_IP.c
source/FreeRTOS_IPv4.c
source/FreeRTOS_IPv6.c
source/FreeRTOS_ND.c
source/FreeRTOS_Routing.c
source/include/FreeRTOS_IPv4.h
source/include/FreeRTOS_IPv6.h
source/include/FreeRTOS_Routing.h
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP/ut.cmake
test/unit-test/FreeRTOS_IPv4/FreeRTOS_IPv4_utest.c
test/unit-test/FreeRTOS_IPv4_DiffConfig/FreeRTOS_IPv4_DiffConfig_utest.c
test/unit-test/FreeRTOS_IPv6/FreeRTOS_IPv6_utest.c
test/unit-test/FreeRTOS_IPv6/ut.cmake
test/unit-test/FreeRTOS_IPv6_ConfigDriverCheckChecksum/FreeRTOS_IPv6_ConfigDriverCheckChecksum_stubs.c
test/unit-test/FreeRTOS_IPv6_ConfigDriverCheckChecksum/FreeRTOS_IPv6_ConfigDriverCheckChecksum_utest.c
test/unit-test/FreeRTOS_ND/FreeRTOS_ND_utest.c
test/unit-test/FreeRTOS_Routing/FreeRTOS_Routing_utest.c

This PR prepares the IP-stack to use loopback addresses `127.0.0.0` and `::1`.
The issue was raised on the FreeRTOS forum [here](https://forums.freertos.org/t/freertos-tcp4-0-0-init-and-loopback-problems/18034) by [ozanagma](https://forums.freertos.org/u/ozanagma).
Description
-----------
● Routing.c :
It now recognises a new IP type for loopback: "eIPv6_Loopback"
Removed a minor bug in `FreeRTOS_AddNetworkInterface()`, and also `FreeRTOS_AddEndPoint()`.
When adding the following interfaces:
~~~
FreeRTOS_AddNetworkInterface( &iface_a );
FreeRTOS_AddNetworkInterface( &iface_b );
FreeRTOS_AddNetworkInterface( &iface_a );
FreeRTOS_AddNetworkInterface( &iface_c );
~~~
In the above example, "iface_b" will become an orphan because of this piece of code:
~~~
if( pxInterface != NULL )
{ …

Preparing library to use loopback device

---

test/build-combination/CMakeLists.txt

Fix build combination test caused by kernel change.
Description
-----------
After kernel [commit](https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/9f4a0e308b311e9fa7ae112a74a27b62a2bbb138), users must choose the heap_*.c file explicitly. Add heap file in CI build test.
Test Steps
-----------
- Execute build-combination test locally.
Checklist:
----------
Related Issue
-----------

Fix build combination test caused by kernel change

---

source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c

Description
-----------
This PR handles an issue reported on [the forum](https://forums.freertos.org/t/freertos-tcp-with-no-phy/14533/10) by [Dweb_2](https://forums.freertos.org/u/Dweb_2).
I looked up the history of [STM32Hxx/NetworkInterface.c](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c) to see where an important change accidentally got "reverted".
May 12, 2022:
I prepared [PR #465](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/465) called "IPv4/single: STM32H7xx driver check result of HAL_ETH_Init" 
After a while I closed it because there was no time to review and merge it.
Jun 8, 2022:
Aniruddha created a new [PR #479](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/479) with the same title, which got …

STM32H7xx driver check result of HAL_ETH_Init v3

---

source/portable/NetworkInterface/DriverSAM/NetworkInterface.c

Description
-----------
In prvSAM_NetworkInterfaceOutput(), the code takes the xTXDescriptorSemaphore counting semaphore every time it needs a TX descriptor.
Upon successful execution of gmac_dev_write(), the ownership of the TX descriptor will eventually get returned back to the network  driver and prvEMACHandlerTask will give back the xTXDescriptorSemaphore counting semaphore. 
If however gmac_dev_write() returns and error, there will be no EMAC_IF_TX_EVENT sent to prvEMACHandlerTask and the counting semaphore will not be given back. 
Every time this happens, one less descriptor can be used until eventually, the counting semaphore can no longer be taken and the system stops being able to send packets. 
Test Steps
-----------
This is difficult to simulate because gmac_dev_write() usually …

SAME70 driver xTXDescriptorSemaphore issue

---

source/FreeRTOS_ND.c

Description
-----------
Imagine the following scenario:
1. The ND cache becomes full.
2. pxARPWaitingNetworkBuffer is NULL as is normally the case.
3. Our DUT ( device under test ) receives a TCP connection from an unknown IPv6 host.
4. DUT parses the SYN packet, but since it needs ND resolution and the source IP is not found in the ND cache, pxARPWaitingNetworkBuffer is pointed to the new SYN packet and the DUT sends out a Neighbor Solicitation packet.
5. The unknown host responds with a Neighbor Advertisement.
6. DUT receives the Neighbor Advertisement packet, but it cannot store the information from it in the ND cache because the DN cache is full.
7. DUT also notices that the incoming Neighbor Advertisement packet matches the SYN packet that is waiting in pxARPWaitingNetworkBuffer and …

Changes the ND cache full behavior when the Neighbor Discovery cache fills up.

---

source/FreeRTOS_Sockets.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c

Description
-----------
Thanks to a forum user [zugo83](https://forums.freertos.org/u/zugo83) in [a post in the FreeRTOS Forum](https://forums.freertos.org/t/freertos-tcp-v4-0-0-performance-degradation/18476), we saw that the function `FreeRTOS_send()` would last longer than necessary.
The proposed change is as follows:
~~~diff
xBytesLeft -= xByteCount;
xBytesSent += xByteCount;
-    if( ( xBytesLeft == 0 ) && ( pvBuffer == NULL ) )
+    if( ( xBytesLeft == 0 ) || ( pvBuffer == NULL ) )
{
/* pvBuffer can be NULL in case TCP zero-copy transmissions are used. */
break;
}
~~~
This must have been a type that happened when we merged the trees IPv4 with IPv6/multi.
Test Steps
-----------
Try send loads of data before and after this change.
Checklist:
----------
By submitting this pull request, …

Wrong test in function prvTCPSendLoop()

---

source/FreeRTOS_DNS.c

Description
-----------
If the source string is longer than the destination, strncpy will truncate last characters from source string **including** the null character, resulting in destination string not null terminated. This PR fixes this issue.
I'm not sure such long strings (longer than maximum hostname length) can be even passed to this function but at least it gets rid of an annoying gcc warning.
Checklist:
----------

Fix issue with strncpy truncating null character from source string

---

source/FreeRTOS_ARP.c

Replace ipconfigHAS_PRINTF by FreeRTOS_debug_printf in the ipARP_REPLY debug print
Description
-----------
The comment in the "#endif" directive states that it belongs to "ipconfigHAS_DEBUG_PRINTF". I'm changing the "#if" directive conditional expression to "ipconfigHAS_DEBUG_PRINTF". And besides that, it is quite annoying to have "ipARP_REPLY from c0a8026dip to c0a8026dip end-point c0a80272ip" all the time int the serial console.
Test Steps
-----------
It is just print replacement.
The existing comment states that " /* Some extra logging while still testing. */". In order to have that extra logging, let us must enable the ipconfigHAS_DEBUG_PRINTF flag.
Checklist:
----------
Not applicable
Related Issue
-----------
Not applicable
By submitting this pull request, I confirm that you can …

Replace ipconfigHAS_PRINTF by FreeRTOS_debug_printf in the ipARP_REPLY debug print

---

source/portable/NetworkInterface/Common/phyHandling.c

Description
-----------
* fix `variable 'ulPHYLinkStatus' is uninitialized when used here [-Werror,-Wuninitialized]` on Clang 17
* fix incorrect operation (`|=` instead of `&`) in `printf`, which leads to the always `high` output
Checklist:
----------
----------

phyHandling: fix compilation with Clang, fix incorrect log output

---

source/FreeRTOS_IP_Utils.c
source/include/FreeRTOS_IP.h

Description
-----------
While looking at old un-merged PRs I saw [PR #547](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/547): "Set ipBUFFER_PADDING to 14 bytes by default on 64 bit targets".
Mentioned PR had the following description:
If `ipconfigBUFFER_PADDING` is not defined in FreeRTOSIPConfig.h, builds for 64 bit targets fail. Add a default value of 14 bytes `( 12U + ipconfigPACKET_FILLER_SIZE )` for `ipBUFFER_PADDING` to satisfy the alignment check in FreeRTOS_IP_Utils.c.
The change in FreeRTOS_IP.h:
~~~diff
/* Use setting from FreeRTOS if defined and non-zero */
#if defined( ipconfigBUFFER_PADDING ) && ( ipconfigBUFFER_PADDING != 0 )
#define ipBUFFER_PADDING    ipconfigBUFFER_PADDING
+    #elif ( UINTPTR_MAX > 0xFFFFFFFF )
+        #define ipBUFFER_PADDING    ( 12U + …

Set ipBUFFER_PADDING to 14 bytes by default on 64 bit targets v2

---

source/FreeRTOS_Sockets.c
source/FreeRTOS_UDP_IPv4.c
source/FreeRTOS_UDP_IPv6.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_UDP_API_utest.c

Description
-----------
Recently, there was a [request in #1058](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/1058): "Please document how the synchronisation works".
This was about the socket's `List_t` that stores UDP packets, called `xWaitingPacketsList`.
I showed that the addition and removal of packets is protected by a critical section, and/or a suspended scheduler.
Non protected access is only seen when `listCURRENT_LIST_LENGTH()` is called. That is OK because a variable of type `UBaseType_t` is read.
These are the proposed changes:
In FreeRTOS_UDP_IPv4.c and in FreeRTOS_UDP_IPv6.c :
~~~diff
vTaskSuspendAll();
{
-    taskENTER_CRITICAL();
-    {
/* Add the network packet to the list of packets to be
* processed by the socket. */
vListInsertEnd( &( …

Avoid critical sections where possible

---

source/FreeRTOS_TCP_WIN.c
source/include/FreeRTOSIPConfigDefaults.h
test/cbmc/proofs/CheckOptionsInner/Makefile.json

Description
-----------
 It is only called from FreeRTOS_TCP_WIN.c, and is no longer used.
Also remove unwanted MISRA issue.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Remove unused FreeRTOS_flush_logging

---

CMakeLists.txt
source/CMakeLists.txt
source/include/FreeRTOS_IPv4.h
source/include/FreeRTOS_IPv4_Private.h
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP/ut.cmake
test/unit-test/FreeRTOS_IPv4_DiffConfig/ut.cmake
test/unit-test/FreeRTOS_IPv4_DiffConfig1/ut.cmake

Description
-----------
This PR does the following
- fixes `empty declaration of 'enum' type does not redeclare tag` error in the `FreeRTOS_IPv4.h` file.
- adds `-Wpedantic` to the GCC compilation flags
- adds `-Wno-pedantic` for `FreeRTOS_Sockets.c` file in case you are using GCC to suppress warning
The main reason is that `FreeRTOS_IPv4.h` is a public header and in case an application uses `-Wpedantic -Werror` to compile, it will not be able to use FreeRTOS-Plus-TCP.
Checklist:
----------
----------

Fix compilation with -Wpedantic on GCC

---

source/FreeRTOS_IPv4.c
source/include/FreeRTOS_IPv6_Private.h
test/unit-test/FreeRTOS_IPv4/FreeRTOS_IPv4_utest.c
test/unit-test/FreeRTOS_IPv4_DiffConfig/FreeRTOS_IPv4_DiffConfig_utest.c

Description
-----------
This PR updatest the loop back checks (`xBadIPv4Loopback()`) to discard bad loopback packets that originates outside of the network. 
Also fixes the build when the ipconfigUSE_RA is disabled with IPv6.
Test Steps
-----------
Ran protocol tests.
Checklist:
----------
Related Issue
-----------

Update loopback checks to discard bad loopback packets originating outside of the network

---

test/build-combination/Common/main.c

Description
-----------
This PR updates the function definition of `vApplicationGetIdleTaskMemory` and `vApplicationGetTimerTaskMemory` to match with latest kernel main.
Test Steps
-----------
Build tests.
Checklist:
----------
Related Issue
-----------

Fix CI build checks with latest kernel

---

test/cbmc/proofs/TCP/prvTCPReturnPacket/TCPReturnPacket_harness.c

Description
-----------
This PR updates the CBMC proof for prvTCPReturnPacket by adding the stub for `eARPGetCacheEntry`. `
Test Steps
-----------
Ran the impacted proof.
Checklist:
----------
Related Issue
-----------

Fix CBMC proof for prvTCPReturnPacket

---

CMakeLists.txt
source/FreeRTOS_DHCP.c
source/FreeRTOS_DHCPv6.c
source/FreeRTOS_DNS.c
source/FreeRTOS_IP.c
source/FreeRTOS_IP_Utils.c
source/FreeRTOS_IPv4_Utils.c
source/FreeRTOS_IPv6_Utils.c
source/FreeRTOS_ND.c
source/FreeRTOS_RA.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_IP_IPv6.c
source/FreeRTOS_TCP_State_Handling_IPv6.c
source/FreeRTOS_TCP_Transmission_IPv4.c
source/FreeRTOS_TCP_Transmission_IPv6.c
source/FreeRTOS_TCP_Utils_IPv6.c
source/FreeRTOS_UDP_IP.c
source/FreeRTOS_UDP_IPv4.c

Description
-----------
This PR updates the codebase to remove declarations after statements that are non compliant as per the C90 standard.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Fix declarations after statements

---

test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c

Description
-----------
This PR fixes few ARP unit tests which were accessing packet memory outside of allocated bounds.
Here the packet size is ensured to be ipconfigETHERNET_MINIMUM_PACKET_BYTES, to make sure that the ethernet buffer passed should be having size >= ipconfigETHERNET_MINIMUM_PACKET_BYTES. 
As in normal scenario, the remaining size more than the ARP packet size would be filled by the IP stack.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Repair ARP unit tests

---

source/FreeRTOS_Routing.c
source/include/FreeRTOSIPConfigDefaults.h
test/unit-test/ConfigFiles/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_DHCPv6/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_DNS/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_DNS_ConfigNoCallback/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig1/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig2/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_DiffConfig3/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_Utils/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IP_Utils_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IPv4_DiffConfig/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IPv4_DiffConfig1/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IPv6/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_IPv6_ConfigDriverCheckChecksum/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_Routing_ConfigV4Only/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_Tiny_TCP/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_UDP_IPv4/FreeRTOSIPConfig.h
test/unit-test/FreeRTOS_UDP_IPv6/FreeRTOSIPConfig.h
tools/tcp_utilities/NTPDemo.c
tools/tcp_utilities/http_client_test.c
tools/tcp_utilities/include/plus_tcp_demo_cli.h
tools/tcp_utilities/plus_tcp_demo_cli.c

Removes ipconfigMULTI_INTERFACE, which is only referenced in the tcp_utilities and one place in the [Demos](https://github.com/FreeRTOS/FreeRTOS/blob/000c005ceed37605a3c146459acdf605ec90919e/FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_IPv6_Demo/common/NTP/NTPDemo.c#L553). If you guys disagree then no problem but it seems to me it's not worth it to further maintain compatibility between the tcp_utilities and an older version of +TCP. If somebody has a single interface version of +TCP then they'll have the old tcp_utilities that work with it as well. I can make a PR to remove that usage from the Demos if this gets approved.
Edit: I also just realized that's the purpose of ipconfigCOMPATIBLE_WITH_SINGLE anyways

Remove ipconfigMULTI_INTERFACE

---

source/FreeRTOS_IP.c
source/FreeRTOS_IP_Timers.c
source/include/FreeRTOS_IP.h
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP_Timers/FreeRTOS_IP_Timers_stubs.c
test/unit-test/FreeRTOS_IP_Timers/FreeRTOS_IP_Timers_utest.c

xProcessedTCPMessage appears to have been there for a very long time but isn't used anywhere. Looks like it has been replaced by [xCheckTCPSockets](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/88e14753788d37b86ed5cb638656b36f8a5ee897/source/FreeRTOS_IP_Timers.c#L289)

Remove xProcessedTCPMessage

---

source/include/FreeRTOS_Routing.h

Description
-----------
This PR is aimed at fixing the issue [reported in forum](https://forums.freertos.org/t/latest-main-branch-of-tcp-has-compilation-error-after-last-commit/19632). 
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Fix header include in FreeRTOS_Routing

---

source/FreeRTOS_IP.c
source/portable/NetworkInterface/DriverSAM/NetworkInterface.c
source/portable/NetworkInterface/MPS2_AN385/NetworkInterface.c
source/portable/NetworkInterface/MPS3_AN552/NetworkInterface.c
source/portable/NetworkInterface/MPS4_CS315/NetworkInterface.c
source/portable/NetworkInterface/NXP1060/NetworkInterface.c
source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
source/portable/NetworkInterface/STM32Hxx/NetworkInterface.c
source/portable/NetworkInterface/WinPCap/NetworkInterface.c
source/portable/NetworkInterface/Zynq/NetworkInterface.c
source/portable/NetworkInterface/esp32/NetworkInterface.c
source/portable/NetworkInterface/loopback/loopbackNetworkInterface.c
source/portable/NetworkInterface/pic32mzef/NetworkInterface_eth.c

Description
-----------
This PR fixes the inconsistent use of `ipconfigCOMPATIBLE_WITH_SINGLE` & `ipconfigIPv4_BACKWARD_COMPATIBLE`in the portable layer files as reported in #1133. Thanks @HTRamsey for reporting this issue.
Use Case : 
- **ipconfigCOMPATIBLE_WITH_SINGLE**  - to be used when there is a single endpoint to make the library more optimal 
-  **ipconfigIPv4_BACKWARD_COMPATIBLE**  - to be used when the library has to be built with IPv4 v3.0.0 backward compatible mode
Test Steps
-----------
Build checks.
Checklist:
----------
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …

Fix inconsistent use of ipconfigCOMPATIBLE_WITH_SINGLE & ipconfigIPv4_BACKWARD_COMPATIBLE

---

source/FreeRTOS_TCP_Transmission_IPv4.c
source/FreeRTOS_TCP_Transmission_IPv6.c

Description
-----------
The first commit moves the initialization of pxIPHeader. This fixes a possible nullpointer dereference.
~The second commit reduces the scope of pxIPHeader and other local variables.~ Dropped.
Test Steps
-----------
I am using this CMake hack to compile my project with clang-tidy:
```
if(CMAKE_C_COMPILER_ID MATCHES "Clang")
set(tidy_checks
-clang-analyzer-security.insecureAPI.*
-clang-analyzer-deadcode.DeadStores
)
string(JOIN "," tidy_checks_str ${tidy_checks})
set(CMAKE_C_CLANG_TIDY
clang-tidy
--use-color
--checks=${tidy_checks_str}
--warnings-as-errors=*,${tidy_checks_str}
)
endif()
```
Checklist:
----------
Related Issue
-----------
#1136
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

Tcp transmission: Fix nullptr dereference

---

source/portable/NetworkInterface/ATSAME5x/NetworkInterface.c

Description
-----------
The `ipCAST_CONST_PTR_TO_CONST_TYPE_PTR()` macro was removed by a4124602cc584fa0658448c229f48a459a84fbb1 but was still used in the ATSAME5x network interface which resulted in a compilation errors. This PR replaces the uses of the macro with direct casts (https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/491#pullrequestreview-1014438538).
Test Steps
-----------
The compilation errors were encountered in a project that is using the ATSAME5x network interface. The compilation errors have been resolved by the changes made in this PR.
The instructions from https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/test/build-combination/README.md#unix-linux-and-mac have also been executed and no errors were encountered.
Checklist:
----------
Related Issue
----------- …

Fix use of removed macro in ATSAME5x network interface

---

source/FreeRTOS_DNS.c
source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_IP.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_WIN.c
source/include/FreeRTOS_IP.h
source/include/FreeRTOS_IPv4.h
source/portable/CMakeLists.txt
source/portable/NetworkInterface/LPC17xx/CMakeLists.txt
source/portable/NetworkInterface/LPC18xx/CMakeLists.txt
source/portable/NetworkInterface/LPC54018/CMakeLists.txt
source/portable/NetworkInterface/LPC54018/NetworkInterface.c
source/portable/NetworkInterface/RX/CMakeLists.txt
source/portable/NetworkInterface/RX/NetworkInterface.c
source/portable/NetworkInterface/SH2A/CMakeLists.txt
source/portable/NetworkInterface/STM32Fxx/CMakeLists.txt
source/portable/NetworkInterface/esp32/CMakeLists.txt
source/portable/NetworkInterface/libslirp/CMakeLists.txt
source/portable/NetworkInterface/pic32mzef/CMakeLists.txt
test/cbmc/stubs/freertos_api.c
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c
tools/CMakeLists.txt

Remove TODO words if there is nothing to do.
Description
-----------
Remove TODO words if there is nothing to do.
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------

Remove TODO words if there is nothing to do.

---

.github/CONTRIBUTING.md
README.md

Update text and link to change primary branch from master to main
Description
-----------
Found to markdown files (README.md and CONTRIBUTING.md) that still assumes the default/primary branch as antiquated master terminology vs main.
Test Steps
-----------
Verified CMake example change correctly fetches content from main branch.  Also, verified link to https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/main/LICENSE.md correctly shows license file without the warning about moving to default branch.
Checklist:
----------
Related Issue
-----------

Update text and link to change primary branch from master to main

---

source/FreeRTOS_Sockets.c
source/include/FreeRTOSIPConfigDefaults.h

Description
-----------
This change replaces the GCC-specific fix for -pedantic in FreeRTOS_Sockets.c with a configurable solution. The change has no functional impact.
Test Steps
-----------
Compiles with GCC, -pedantic, and -Werror
Checklist:
----------
Related Issue
-----------
(none)
#	source/FreeRTOS_Sockets.c
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Enabling user control of compiler analysis for non ISO statements

---

.github/workflows/ci.yml
CMakeLists.txt
source/CMakeLists.txt
test/CMakeLists.txt
test/build-combination/CMakeLists.txt
test/build-combination/README.md

Description
-----------
As [originally discussed in the FreeRTOS Forums](https://forums.freertos.org/t/freertos-plus-tcp-compilation-issues/19825), projects that consume FreeRTOS-Plus-TCP are forced to use the compilation options configured by `test/build-combination/CMakeLists.txt` when compiling `freertos_plus_tcp` which can cause compilation issues. This PR avoids compilation issues in consumer projects by making processing of `test/build-combination/CMakeLists.txt` optional:
1. Added `FREERTOS_PLUS_TCP_BUILD_BUILD_TEST` option to control whether `test/build-combination/CMakeLists.txt` is processed. Updated `.github/workflows/ci.yml` `build-checks` job and `test/build-combination/README.md` to reflect the addition of this new option.
2. Moved `FREERTOS_PLUS_TCP_TEST_CONFIGURATION` …

Avoid compilation issues in consumer projects

---

source/CMakeLists.txt
source/FreeRTOS_Sockets.c
test/build-combination/AllDisable/FreeRTOSIPConfig.h
test/build-combination/AllEnable/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv4/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv4_IPv6/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv4_TCP/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv6/FreeRTOSIPConfig.h
test/build-combination/Enable_IPv6_TCP/FreeRTOSIPConfig.h
test/build-combination/Header_Self_Contain/FreeRTOSIPConfig.h

Description
-----------
This PR removes `-Wno-pedantic` build requirement for FreeRTOS_Sockets.c. And updates the CI build checks to use GCC specific compiler pragma injection macros to disable warnings in specific lines.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Remove -Wno-pedantic build requirement for FreeRTOS_Sockets.c

---

source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_State_Handling.c
test/cbmc/proofs/TCP/prvTCPHandleState/Makefile.json
test/cbmc/proofs/TCP/prvTCPHandleState/TCPHandleState_harness.c
test/cbmc/proofs/TCP/prvTCPPrepareSend/Makefile.json
test/cbmc/proofs/TCP/prvTCPPrepareSend/TCPPrepareSend_harness.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c
test/unit-test/FreeRTOS_TCP_IP/FreeRTOS_TCP_IP_utest.c
test/unit-test/FreeRTOS_TCP_IP/TCP_IP_list_macros.h
test/unit-test/FreeRTOS_TCP_State_Handling/FreeRTOS_TCP_State_Handling_utest.c

Description
-----------
This PR fixes issue #1110, were freed socket memory was being reused in certain circumstances.
Refer #1110 for detailed information.
Thanks @htibosch for this fix.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Fix freed memory being reused

---

History.txt
docs/doxygen/config.doxyfile
manifest.yml

Description
-----------
This PR updates the version info for v4.1.1 release.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

[v4.1.1] Update version info 

---

source/FreeRTOS_DNS_Parser.c
source/FreeRTOS_RA.c
source/FreeRTOS_Sockets.c
source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_State_Handling_IPv4.c
source/FreeRTOS_TCP_State_Handling_IPv6.c

Description
-----------
This PR fixes MISRA 2012 violations.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Fix MISRA 2012 violations

---

CMakeLists.txt
README.md

Description
------------
My project has an existing FreeRTOS Kernel and I attempted to include this project via CMake's `FetchContent` function as suggested by the Readme. In this process I stumbled over two minor details:
- Copy-paste error in the readme, suggesting to set defines for the FAT build instead of the TCP library
- No functionality to prevent the TCP library to pull in its own copy of the kernel, as other libraries have
Test Steps
-----------
- Set up a project with bare-bones FreeRTOS
- Consume this library via CMake's `FetchContent` as suggested by the readme
Checklist:
----------
- [~] I have tested my changes. No regression in existing tests.
-> I have obviously tested that this solution fixes *my* problem, but I'm unsure how I can test it against regressions in the …

Allow FetchContent usage in external projects

---

.github/workflows/release.yml
source/include/FreeRTOS_IP.h

Description
-----------
* Update version number V4.2.999 in header file to indicate main branch development builds version
* Remove unused FREERTOS_PLUS_TCP_VERSION macro
* Update release.yml to use version_number when in create zip steps
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------

Update version number macro in header file

---

source/portable/NetworkInterface/RX/NetworkInterface.c
test/unit-test/FreeRTOS_TCP_Reception/FreeRTOS_TCP_Reception_utest.c

Define `pxFillInterfaceDescriptor` in RX network interface code
Description
-----------
- We had an issue where `pxFillInterfaceDescriptor` is undefined in the NetworkInterface.c of RX vendor.
- This pull request defines `pxFillInterfaceDescriptor` function.
Test Steps
-----------
- Verified internet connection can be established via Ethernet. and PubSub over MQTT works as expected.
Related Issue
-----------
https://forums.freertos.org/t/pxfillinterfacedescriptor-is-undefined-in-rx-networkinterface-c/21263/2

Updated RX portable layer for backward compatibility

---

source/FreeRTOS_Stream_Buffer.c
test/unit-test/FreeRTOS_Stream_Buffer/FreeRTOS_Stream_Buffer_utest.c

To optimize performance, consider replacing the potentially costly `vTaskSuspendAll`/`xTaskResumeAll` locking mechanism with the more efficient `taskENTER_CRITICAL`/`taskEXIT_CRITICAL` pair.
While `taskENTER_CRITICAL` disables interrupts, the protected code section is relatively short and time-bound, making it a suitable candidate. This is especially advantageous given the high-frequency usage of `uxStreamBufferAdd()`.

Optimize uxStreamBufferAdd() locking mechanism

---

source/FreeRTOS_ARP.c
source/FreeRTOS_DNS_Callback.c
source/portable/NetworkInterface/loopback/loopbackNetworkInterface.c
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c
test/unit-test/FreeRTOS_DNS_Callback/FreeRTOS_DNS_Callback_utest.c

Description
-----------
This PR updates the `eARPGetCacheEntry` to handle loopback addresses correctly and assign the loopback endpoint's MAC address as the lookup MAC address. 
Update the loopback interface to refresh the ARP/ND caches correctly and drop packets that cannot find a matching endpoint that can handle the packet.
We thank @htibosch for this fix.
Also thanks to @rickou and [@grap](https://forums.freertos.org/u/grap/summary) for reporting this issue in #1179 and in the [FreeRTOS forum.](https://forums.freertos.org/t/freertos-tcp-how-to-use-loopback-interface-on-stm32h723-board/21370)
Test Steps
-----------
Loopback test on TCP socket with STM32H7 NUCLEO.
Checklist:
----------
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, …

Fix ARP failure with loopback addresses

---

source/portable/NetworkInterface/ATSAM4E/NetworkInterface.c
source/portable/NetworkInterface/ATSAM4E/gmac.c
source/portable/NetworkInterface/DriverSAM/NetworkInterface.c
source/portable/NetworkInterface/DriverSAM/gmac_SAM.h

Description
-----------
This PR fixes missing parameters error in ATSAM4E. 
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
#1190 

Fix missing parameters error in ATSAM4E

---

source/FreeRTOS_IPv4.c
source/FreeRTOS_Routing.c
source/portable/NetworkInterface/RX/NetworkInterface.c
source/portable/NetworkInterface/RX/ether_callback.c
test/unit-test/FreeRTOS_IPv4/FreeRTOS_IPv4_utest.c
test/unit-test/FreeRTOS_Routing/FreeRTOS_Routing_utest.c

Description
-----------
I am experiencing an issue when obtaining IP through DHCP, here is what happens:
- the MCU is on the network doing its thing, then it gets reset;
- the MCU issues a DHCP discover;
- the DHCP server already has a lease for the MCU’s MAC address, it tries to ping the lease before offering it;
- an ICMP ping request is issued with destination MAC of the MCU (ARP request is skipped as the host already has a fresh ARP entry for that MAC address);
- the MCU replies to that ICMP ping request!
- the DHCP server deems that lease occupied, so it abandons it and offers the next available IP.
This happens because the function "prvAllowIPPacketIPv4” will allow any unicast packet through when one endpoint is down.
The changes I propose affect the logic to now NOT let through …

do not let through unicast packets on inactive endpoints

---

source/portable/NetworkInterface/ATSAME5x/NetworkInterface.c

A fix for issue #1193. 
Note: although I have an ATSAME53 board, I have not compiled or executed the code in this pull-request. My own project uses a customized version of this code.
I also noticed that this same bug exists in the MSP432 driver. This pull-request does not fix that.

Bugfix in ATSAME5x network interface. Incorrect detection of ICMP

---

MISRA.md
source/FreeRTOS_ARP.c
source/FreeRTOS_DNS.c
source/FreeRTOS_IP.c
source/include/FreeRTOS_DNS.h
test/Coverity/coverity_misra.config

Description
-----------
This PR fixes MISRA2012 issues with Coverity version 2024.06
Test Steps
-----------
Run coverity.
Checklist:
----------
Related Issue
-----------

Fix MISRA2012 issues with Coverity version 2024.06

---

source/include/FreeRTOSIPConfigDefaults.h

Description
-----------
This PR removes IP task priority check as there is already an assert in the kernel and the priority is capped by the kernel as well.
Test Steps
-----------
NA.
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/freertos-plus-tcp-upgrade-from-3-1-0-to-4-2-2/21617

Remove IP task priority check

---

source/FreeRTOS_IP.c
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP_DiffConfig1/FreeRTOS_IP_DiffConfig1_utest.c

Description and Test Steps
-----------
Imagine that the DUT has it's network down.
User code calls `FreeRTOS_getaddrinfo_a()` and supplies a callback function. 
If a Network-UP event happens after the call to `FreeRTOS_getaddrinfo_a()` but before the query times out, the user's callback function never gets called.
A colleague of mine traced that to the fact that +TCP re-initializes `xCallbackList` every time there is a Network-UP event.
I believe this is incorrect behavior. I see no good reason to blindly clear `xCallbackList`. This list was properly initialized already and is being managed correctly by the DNS handler and the DNS timer.
I believe this is a very simple and safe fix, but as always, I may have missed something.
Let me know what you think.
By submitting this pull request, I …

Missing DNS callbacks

---

source/portable/NetworkInterface/libslirp/MBuffNetworkInterface.c

Description
-----------
This PR adds definition for `pxFillInterfaceDescriptor` to support `ipconfigIPv4_BACKWARD_COMPATIBLE` in libslirp network interface.
Test Steps
-----------
Changes are tested in the fork using simulated demos here: 
https://github.com/tony-josi-aws/FreeRTOS/actions/runs/12233018960
Checklist:
----------
Related Issue
-----------

Add pxFillInterfaceDescriptor definition to libslirp network interface for backward compatibility

---

source/portable/NetworkInterface/libslirp/MBuffNetifBackendLibslirp.c

Description
-----------
This causes failure because of this innocuous looking change - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1207.
Test Steps
-----------
Run MQTT Plain Text Demo and TCP Demo with libslirp.
Checklist:
----------
- [NA] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1207

Remove xHigherPriorityTaskWoken

---

source/FreeRTOS_Routing.c

Description
-----------
The function `xIPv6_GetIPType()` misidentifies all unknown addresses that start with 0x0000 as eIPv6_Loopback.
The problem is that on the last cycle of the for(;;) loop, the code is allowed to do the normal mask-type check even if the loopback test fails.
Test Steps
-----------
```
IP_Address_t xTestAddress;
// Set the test address to the "::" unspecified IPv6 address
memset( xTestAddress.xIP_IPv6.ucBytes, 0x00, ipSIZE_OF_IPv6_ADDRESS );
IPv6_Type_t xAddressType = xIPv6_GetIPType( &( xTestAddress.xIP_IPv6 ) );
if( xAddressType == eIPv6_Unknown )
{
FreeRTOS_printf("xTestAddress identified as eIPv6_Unknown" );
}
else
{
FreeRTOS_printf("xTestAddress misidentified as type %u", xAddressType );
}
```
Note:
This fix could have been done in a few other way. One alternative …

Fixes  IPv6 loopback address type check

---

.github/workflows/ci.yml
source/FreeRTOS_DNS.c
source/FreeRTOS_DNS_Cache.c
source/FreeRTOS_DNS_Callback.c
source/FreeRTOS_Sockets.c
test/build-combination/CMakeLists.txt
test/cbmc/proofs/DNS/CreateDNSMessage/Makefile.json
test/cbmc/proofs/DNS/DNSTreatNBNS/Makefile.json
test/unit-test/FreeRTOS_DNS_Callback/FreeRTOS_DNS_Callback_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_stubs.c
test/unit-test/FreeRTOS_Sockets/Sockets_list_macros.h
test/unit-test/FreeRTOS_Sockets_DiffConfig/Sockets_DiffConfig_list_macros.h
test/unit-test/FreeRTOS_Sockets_DiffConfig1/Sockets_DiffConfig1_list_macros.h
test/unit-test/FreeRTOS_Sockets_IPv6/Sockets_IPv6_list_macros.h
test/unit-test/FreeRTOS_TCP_IP/TCP_IP_list_macros.h

Description
-----------
This PR fixes compiler warnings that are generated when compiled with optimizations enabled in GCC and adds CI build checks with optimization settings on.
Thanks, @StefanBalt, for reporting this issue in #1217.
This PR also fixes the false positive warnings emitted by GCC version GNU 13.1.0:
``` sh
/home/ubuntu/Projects/FreeRTOS-Plus-TCP/source/FreeRTOS_DNS_Callback.c: In function ‘xDNSDoCallback’:
/home/ubuntu/Projects/FreeRTOS-Plus-TCP/build/_deps/freertos_kernel-src/include/./list.h:241:75: error: array subscript ‘ListItem_t {aka const struct xLIST_ITEM}[0]’ is partly outside array bounds of ‘List_t[1]’ {aka ‘struct xLIST[1]’} [-Werror=array-bounds=]
241 | #define listGET_NEXT( pxListItem )                        ( ( pxListItem )->pxNext )
| …
```

Fix compiler warnings with optimizations enabled

---

source/FreeRTOS_DHCP.c
source/FreeRTOS_IP_Timers.c
source/FreeRTOS_IPv4.c

Handle correctly types when printing.
Description
-----------
When compiling, I had some warnings regarding printf. I fixed them by using the correct types.
Test Steps
-----------
Compile using GCC or Clang with `-Wformat`.
Checklist:
----------
Related Issue
-----------

Fix printf warnings

---

source/FreeRTOS_ARP.c
source/FreeRTOS_DHCP.c
source/FreeRTOS_DNS.c
source/FreeRTOS_IPv4.c
source/include/FreeRTOS_IP_Private.h
source/include/FreeRTOS_IPv4.h
source/include/FreeRTOS_Sockets.h
source/portable/NetworkInterface/STM32/CMakeLists.txt
source/portable/NetworkInterface/STM32/Drivers/F4/stm32f4xx_hal_eth.c
source/portable/NetworkInterface/STM32/Drivers/F4/stm32f4xx_hal_eth.h
source/portable/NetworkInterface/STM32/Drivers/F7/stm32f7xx_hal_eth.c
source/portable/NetworkInterface/STM32/Drivers/F7/stm32f7xx_hal_eth.h
source/portable/NetworkInterface/STM32/Drivers/H5/stm32h5xx_hal_eth.c
source/portable/NetworkInterface/STM32/Drivers/H5/stm32h5xx_hal_eth.h
source/portable/NetworkInterface/STM32/Drivers/H5/stm32h5xx_hal_eth_ex.c
source/portable/NetworkInterface/STM32/Drivers/H5/stm32h5xx_hal_eth_ex.h
source/portable/NetworkInterface/STM32/Drivers/H7/stm32h7xx_hal_eth.c
source/portable/NetworkInterface/STM32/Drivers/H7/stm32h7xx_hal_eth.h
source/portable/NetworkInterface/STM32/Drivers/H7/stm32h7xx_hal_eth_ex.c
source/portable/NetworkInterface/STM32/Drivers/H7/stm32h7xx_hal_eth_ex.h
source/portable/NetworkInterface/STM32/NetworkInterface.c
test/cbmc/proofs/ARP/ARPGetCacheEntry/Configurations.json
test/cbmc/proofs/parsing/ProcessIPPacket/ProcessIPPacket_harness.c
test/unit-test/FreeRTOS_ARP/FreeRTOS_ARP_utest.c
test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_utest.c
test/unit-test/FreeRTOS_DNS/FreeRTOS_DNS_utest.c
test/unit-test/FreeRTOS_IPv4/FreeRTOS_IPv4_utest.c
test/unit-test/FreeRTOS_IPv4_DiffConfig/FreeRTOS_IPv4_DiffConfig_utest.c

Description
-----------
The current code incorrectly assumes that broadcast addresses only end in x.x.x.255
When a frame enters the stack, all broadcast tests must be made against the 255.255.255.255 address and against the **specific broadcast of the endpoint that the frame was assigned**
When an ARP lookup is attempted, we need to check if the user is attempting to send a packet that may be considered a broadcast on any of our IPv4 endpoints. Current code was only calling an outgoing packet a "broadcast" is said packet ended in 0xFF.
This PR attempts to correct both of the above.
Additionally, I've taken the liberty to substitute ipBROADCAST_IP_ADDRESS with FREERTOS_INADDR_BROADCAST and put the new definition in a public header file. Here's my reasoning:
- INADDR_BROADCAST is a …

Improves handling of IPv4 broadcast addresses.

---

source/portable/NetworkInterface/Zynq/x_emacpsif_dma.c
source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_dma.c

Description
-----------
Zynq network interface packet filtering, if enabled, could drop packets with fragment flags (don't fragment and may fragment bits) set incorrectly as `ipFRAGMENT_OFFSET_BIT_MASK` flag is already defined to be matching as per the endian requirement based on the `ipconfigBYTE_ORDER`, and doesn’t need `FreeRTOS_ntohs` again.
This PR fixes the issue. 
[User reported issue of pings not replied from Zynq when requested from specific hosts.](https://forums.freertos.org/t/ping-not-working-trouble-getting-started-w-freertos-tcp-on-zynq-zedboard/22117)
Test Steps
-----------
[Author of the issue confirmed the fix](https://forums.freertos.org/t/ping-not-working-trouble-getting-started-w-freertos-tcp-on-zynq-zedboard/22117/40?u=tony-josi-aws)
Checklist:
----------
- ~[ ] I …

Fix Zynq network interface incoming packet filtering by correcting endianness

---

source/FreeRTOS_DHCP.c
test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_stubs.c
test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_utest.c

Description
-----------
This PR fixes a race condition in DHCP - v4.
While the DHCP state machine is processing response from a DHCP server, causing it to change the DHCP state, if another DHCP server responds to the DUT, state mismatch will cause the `vDHCPProcess` function to result in an infinite loop.
Thanks [Raghav](https://forums.freertos.org/u/Raghav) for reporting this issue in the [forum post](https://forums.freertos.org/t/code-stuck-in-the-vdhcpprocess-function-mostly-when-dhcp-state-machine-is-ewaitingacknowledge/22484).
Test Steps
-----------
STM32F4 - DHCP v4 tests
Checklist:
----------
Related Issue
-----------

Fix DHCP race condition

---

test/unit-test/CMakeLists.txt
test/unit-test/FreeRTOS_BitConfig/FreeRTOS_BitConfig_utest.c
test/unit-test/FreeRTOS_DHCPv6/FreeRTOS_DHCPv6_utest.c
test/unit-test/FreeRTOS_DNS_Cache/FreeRTOS_DNS_Cache_utest.c
test/unit-test/FreeRTOS_DNS_Callback/FreeRTOS_DNS_Callback_utest.c
test/unit-test/FreeRTOS_DNS_Networking/FreeRTOS_DNS_Networking_utest.c
test/unit-test/FreeRTOS_DNS_Parser/FreeRTOS_DNS_Parser_utest.c
test/unit-test/FreeRTOS_ICMP/FreeRTOS_ICMP_utest.c
test/unit-test/FreeRTOS_IP/FreeRTOS_IP_utest.c
test/unit-test/FreeRTOS_IP_DiffConfig2/FreeRTOS_IP_DiffConfig2_utest.c
test/unit-test/FreeRTOS_IP_Utils/FreeRTOS_IP_Utils_utest.c
test/unit-test/FreeRTOS_IPv4_DiffConfig/FreeRTOS_IPv4_DiffConfig_utest.c
test/unit-test/FreeRTOS_ND/FreeRTOS_ND_utest.c
test/unit-test/FreeRTOS_RA/FreeRTOS_RA_utest.c
test/unit-test/FreeRTOS_Routing/FreeRTOS_Routing_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_TCP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_UDP_API_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c
test/unit-test/FreeRTOS_Sockets_DiffConfig/FreeRTOS_Sockets_DiffConfig_privates_utest.c
test/unit-test/FreeRTOS_Sockets_DiffConfig1/FreeRTOS_Sockets_DiffConfig1_GenericAPI_utest.c
test/unit-test/FreeRTOS_Sockets_DiffConfig1/FreeRTOS_Sockets_DiffConfig1_UDP_API_utest.c
test/unit-test/FreeRTOS_Sockets_DiffConfig1/FreeRTOS_Sockets_DiffConfig1_privates_utest.c
test/unit-test/FreeRTOS_UDP_IPv4/FreeRTOS_UDP_IPv4_utest.c
test/unit-test/FreeRTOS_UDP_IPv6/FreeRTOS_UDP_IPv6_utest.c

Let's build unittests with certain warnings enabled and turned into errors.
This will make them fail in CI and also make them look like errors in editors that use a language server.
In particular, `-Werror=uninitialized` (make compilation fail when all control paths use a variable uninitialized).
The first commit is devoted to fixing these.
Motivation: Most of the crashing tests I fixed in #1151 were caused by reading uninitialized memory. As I suggested there, the kinds of errors I had to fix could have been prevented by enabling certain warnings as errors.
Checklist:
----------
Related Issue
-----------
This is a continuation of #1151.

Unittest: Fix, enable and forbid specific warnings

---

source/FreeRTOS_TCP_IP.c
source/FreeRTOS_TCP_Transmission.c
source/include/FreeRTOS_TCP_Transmission.h
test/unit-test/FreeRTOS_TCP_Transmission/FreeRTOS_TCP_Transmission_utest.c

That avoids avoid endless ACK/RST retransmissions.
Description
-----------
See #1235
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
#1235

Use the expected sequence number for challenge ACK messages

---

.github/workflows/ci.yml
test/unit-test/README.md

Description
-----------
Update scripts to run unit tests with respect to Ubuntu 24.04
Test Steps
-----------
Tested on Ubuntu 24.04
Checklist:
----------
Related Issue
-----------

Update scripts to run unit tests with respect to Ubuntu 24.04

---

source/FreeRTOS_IPv4.c
test/unit-test/FreeRTOS_IPv4/FreeRTOS_IPv4_utest.c
test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_privates_utest.c

Description
-----------
This PR updates the `prvAllowIPPacketIPv4` to let valid broadcast packets in when endpoint is not yet up if the `ipconfigETHERNET_DRIVER_FILTERS_PACKETS` is disabled.
Test Steps
-----------
Platforms: QEMU, STM32, Winsim
Checklist:
----------
Related Issue
-----------
#1238 

Let valid broadcast packets in when endpoint is not yet up

---

.github/.cSpellWords.txt
.github/workflows/ci.yml
source/FreeRTOS_TCP_IP.c
test/build-combination/CMakeLists.txt

Remove warning message from "gcc -Wredundant-decls" in FreeRTOS_TCP_IP.c.
Checklist:
----------
Related Issue
-----------

remove redundant function declaration

---

.github/workflows/ci.yml
source/FreeRTOS_DNS_Parser.c
test/build-combination/CMakeLists.txt
test/build-combination/DisableDnsFeatures/FreeRTOSIPConfig.h

The code would fail to compile unless one of ipconfigUSE_DNS_CACHE,
ipconfigUSE_MDNS, ipconfigUSE_LLMNR, and ipconfigDNS_USE_CALLBACKS
were set.
Checklist:
----------

Fix compilation error if DNS features are disabled

---

source/FreeRTOS_Sockets.c

Description
-----------
FreeRTOS APIs shouldn't be called while the scheduler is suspended - [`vTaskSuspendAll`](https://www.freertos.org/Documentation/02-Kernel/04-API-references/04-RTOS-kernel-control/05-vTaskSuspendAll)
Depending on the user implementation of `FreeRTOS_printf` its highly likely that there will be blocking FreeRTOS API calls done from `FreeRTOS_printf`.
This PR removes the usage of  `FreeRTOS_printf` from the suspended scheduler region in `prvAcceptWaitClient`.
Thanks [TDB](https://forums.freertos.org/u/TDB) for reporting this issue in FreeRTOS forum: https://forums.freertos.org/t/prvacceptwaitclient-gets-interrupted-with-xsemaphoretake-while-tasks-are-suspended/23056
Test Steps
-----------
Tested with a sample echo server on STM32F4
Checklist:
----------
- ~[ ] I have …

Move FreeRTOS_printf from suspended scheduler region in prvAcceptWaitClient

---

source/include/NetworkInterface.h
source/portable/BufferManagement/BufferAllocation_1.c
source/portable/NetworkInterface/ATSAME5x/NetworkInterface.c
source/portable/NetworkInterface/DriverSAM/NetworkInterface.c
source/portable/NetworkInterface/LPC18xx/NetworkInterface.c
source/portable/NetworkInterface/LPC54018/NetworkInterface.c
source/portable/NetworkInterface/M487/NetworkInterface.c
source/portable/NetworkInterface/MPS2_AN385/NetworkInterface.c
source/portable/NetworkInterface/MPS3_AN552/NetworkInterface.c
source/portable/NetworkInterface/MPS4_CS315/NetworkInterface.c
source/portable/NetworkInterface/RX/NetworkInterface.c
source/portable/NetworkInterface/STM32/Legacy/STM32Fxx/NetworkInterface.c
source/portable/NetworkInterface/STM32/Legacy/STM32Hxx/NetworkInterface.c
source/portable/NetworkInterface/STM32/NetworkInterface.c
source/portable/NetworkInterface/TM4C/NetworkInterface.c
source/portable/NetworkInterface/ThirdParty/MSP432/NetworkInterface.c
source/portable/NetworkInterface/WinPCap/NetworkInterface.c
source/portable/NetworkInterface/Zynq/NetworkInterface.c
source/portable/NetworkInterface/Zynq/x_emacpsif_dma.c
source/portable/NetworkInterface/board_family/NetworkInterface.c
source/portable/NetworkInterface/libslirp/MBuffNetworkInterface.c
source/portable/NetworkInterface/linux/NetworkInterface.c
source/portable/NetworkInterface/mw300_rd/NetworkInterface.c
source/portable/NetworkInterface/xilinx_ultrascale/NetworkInterface.c
source/portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_dma.c
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/Configurations.json
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/OutputARPRequest_harness.c
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc1/README.md
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc2/Configurations.json
test/cbmc/proofs/ARP/ARP_OutputARPRequest_buffer_alloc2/README.md

Description
-----------
This PR improves the maximum network buffer allocation size check when Buffer Allocation scheme 1 is used by returning the number of bytes allocated per network buffer by the network interface when the statically allocated buffers are initialized.
Test Steps
-----------
Tested on STM32F4
Checklist:
----------
Related Issue
-----------

[V4.3.2] Improve maximum network buffer allocation size check when Buffer Allocation scheme 1 is used

---

source/portable/NetworkInterface/xilinx_ultrascale/NetworkInterface.c

Remove variable 'ulDMAReg' which is unused in the Ultrascale port
Description
-----------
Variable ulDMAReg declaration removed as not required
Test Steps
-----------
Compile and there is a warning of unused variable
Checklist:
----------
- [x ] I have tested my changes. No regression in existing tests.
- [x ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------
None

Remove unused variable in ultrascale port (ulDMAReg)

---

source/FreeRTOS_IP_Utils.c
source/include/FreeRTOSIPConfigDefaults.h

Description
-----------
Added ipconfigSUPPRESS_BUFFER_PADDING_CHECK to prevent configASSERT checks on ipBUFFER_PADDING in FreeRTOS_IP_Utils.c/vPreCheckConfigs( void )
* Defaults to ipconfigDISABLE to build with configASSERT checks in place.
* User settable to ipconfigENABLE to eliminate configASSERT checks.
Test Steps
-----------
Observe that when source built while ipconfigSUPPRESS_BUFFER_PADDING_CHECK either not defined in user configuration or defined as ipconfigDISABLE, the configASSERTs to validate optimal settings for ipBUFFER_PADDING are also built as in existing code base.  The configASSERTS are not built when the default setting is overridden in a user configuration by defining ipconfigSUPPRESS_BUFFER_PADDING_CHECK as ipconfigENABLE.
Checklist:
----------
Related Issue …

Add configuration option to prevent configASSERT checks on ipBUFFER_PADDING

---

source/portable/BufferManagement/BufferAllocation_1.c
source/portable/NetworkInterface/STM32/Legacy/STM32Hxx/NetworkInterface.c

STM32H legacy driver: change parameter to pucGetRXBuffer()
-----------
This issue was [reported](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/1276) on the FreeRTOS forum by user[https://github.com/kzorer](kzorer).
This is the essential change:
~~~diff
/* Subtracted 'ipBUFFER_PADDING', which is the size of the meta data. */
pucBuffer = pucGetRXBuffer( ETH_RX_BUF_SIZE - ipBUFFER_PADDING  );
configASSERT( pucBuffer != NULL );
~~~
This was a result of an earlier patch that repair a vulnerability.
Test Steps
-----------
Create an application that connects to the Ethernet and try anything, send it a an ICMP ping message and it will fail. It went wrong in this test:
~~~c
NetworkBufferDescriptor_t * pxGetNetworkBufferWithDescriptor( size_t xRequestedSizeBytes,
TickType_t xBlockTimeTicks ) …

STM32H legacy driver: change parameter to pucGetRXBuffer()

---

source/portable/NetworkInterface/Zynq/NetworkInterface.c
source/portable/NetworkInterface/Zynq/x_emacpsif.h
source/portable/NetworkInterface/Zynq/x_emacpsif_dma.c
source/portable/NetworkInterface/Zynq/x_emacpsif_hw.c

Description
-----------
A visitor on the FreeRTOS forum, [trantam](https://forums.freertos.org/u/trantam_cdt92) found that sometimes a TCP connection has non-active moments of 60 ms or longer. See this [long conversation](https://forums.freertos.org/t/freertos-tcp-long-delay-between-two-splitted-frames/23637/29).
I did an earlier attempt in [PR 1283](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/1283), but it didn't solve all.
Changes how to handle notification value: 
--
In the current driver, the EMAC task is woken up using a generic task notify:
`vTaskNotifyGiveFromISR( xEMACTaskHandles[ xEMACIndex ], &xTaskWoken );`
and the notification value is stored in a separate variable.
In the new version, the notification value is stored in the task:
`xTaskNotifyFromISR( xEMACTaskHandles[ …

Zynq driver: avoid race conditions

---

source/portable/NetworkInterface/loopback/loopbackNetworkInterface.c

Description
-----------
To resolve the issue #1289, #include "FreeRTOS_ARP.h" is added in loopbackNetworkInterface.c.
Test Steps
-----------
Just build FreeRTOS with Plus-TCP normally. IPv4 addressing is enabled, loopback interface is enabled. No compilation error.
Checklist:
----------
No. I have no environment in my current IDE to perform all designated tests.
Related Issue
-----------
#1289

Add missing FreeRTOS_ARP include to loopback NetworkInterface
