portable/NetworkInterface/LPC54018/NetworkInterface.c
Uncrustify
Description
-----------
Test Steps
-----------
added a network interface for the LPC54018 ethernet
Related Issue
-----------
=> added a network interface for the LPC54018 ethernet

manifest.yml, portable/NetworkInterface/STM32Hxx/NetworkInterface.c, portable/NetworkInterface/STM32Hxx/readme.md, portable/NetworkInterface/STM32Hxx/stm32h7xx_hal_eth.h, portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.c, portable/NetworkInterface/STM32Hxx/stm32hxx_hal_eth.h
Description
-----------
This is a copy of my earlier [PR #256](https://github.com/FreeRTOS/FreeRTOS/pull/256), which will be closed.
Recently, on the [FreeRTOS forum](https://forums.freertos.org) there were many requests for a network interface for STM32H7xx.
This driver has now been tested by using various protocols, and also a performance tool iperf3.
There is now also a readme.md with details and recommended configuration settings.
Thanks to all forum users who worked on earlier versions of this driver.
=> Adding a network interface for STM32H7xx(v2)

portable/NetworkInterface/LPC54018/NetworkInterface.c
Description
-----------
Hein made recommendations related to:
1) buffer management
2) packet reception
Also a number of memory alignment changes were made to make the code portable with IAR.
=> Cleanup as a result of Hein's code review

portable/NetworkInterface/LPC54018/NetworkInterface.c
removed extra print statements in the LPC54018 NetworkInterface
=> removed extra prints

portable/NetworkInterface/WinPCap/NetworkInterface.c
Description
-----------
This PR updates logging in the WinPCap Network Interface to reduce multiple repetitive logs and provide a more apt description of the situation.
Test Steps
-----------
Related Issue
-----------
=> Update the logging in WinPCap network interface.

.github/lexicon.txt, FreeRTOS_DHCPv6.c, include/FreeRTOS_DHCPv6.h
Description
-----------
The purpose of this commit is the go through reviewing. Please do not use these branches for any development.
The complete /multi /IPv6 release can be viewed [here](https://github.com/htibosch/FreeRTOS-Plus-TCP-multi).
This PR replaces the earlier #71 
=> TCP /multi /IPv6 FreeRTOS_DHCPv6 module

portable/NetworkInterface/MPS2_AN385/NetworkInterface.c, portable/NetworkInterface/MPS2_AN385/ether_lan9118/smsc9220_emac_config.h, portable/NetworkInterface/MPS2_AN385/ether_lan9118/smsc9220_eth_drv.c, portable/NetworkInterface/MPS2_AN385/ether_lan9118/smsc9220_eth_drv.h
Add networking support for MPS2 with cortex M3 - AN385
Description
-----------
Add networking support for MPS2
Test Steps
-----------
tested with the echo client demo
```
$ sudo nc -vl 7
Password:
TxRx message number 0FGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`ab …
```
=> Networking ARM MPS2 with CortexM3 - AN385

.github/lexicon.txt, .github/workflows/ci.yml, FreeRTOS_DHCP.c, include/FreeRTOS_DHCP.h
Description
-----------
Applied the same type of changes as in PR #107: when there is no new network buffer, wait for e.g. 250 ms, and try again.
Test Steps
-----------
This is described in #107 
=> Applied PR #107 to DHCP /multi

.github/workflows/ci.yml, FreeRTOS_DHCPv6.c
Description
-----------
Corrected two typos: `s/BitCOnfig_t/BitConfig_t/`
=> FreeRTOS_DHCPv6: Corrected two typos

.github/workflows/ci.yml, portable/NetworkInterface/WinPCap/NetworkInterface.c
Description
-----------
Changed the WinPCap network driver to become compatible with /multi and IPv6.
Test Steps
-----------
Testing demo is ready but not yet released.
=> Network interface /multi for Winsim (WinPCap)

.github/workflows/ci.yml, portable/NetworkInterface/STM32Fxx/NetworkInterface.c, portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.c
Description
-----------
This PR make the STM32Fxx driver compatible with /multi and IPv6
Test Steps
-----------
Demo projects are not yet ready for release.
Related Issue
-----------
=> Network interface /multi for STM32Fxx

portable/NetworkInterface/esp32/NetworkInterface.c
Description
-----------
This PR make the ESP32 driver compatible with /multi and IPv6.
All adapted drivers can still be used in backward compatible mode when `ipconfigCOMPATIBLE_WITH_SINGLE` is defined in FreeRTOSIPConfig.h.
This PR replaces #121 , which was apparently not based on the "feature/ipv6_multi_beta" when creating it.
Test Steps
-----------
Replace all /single sources with this branch, add FreeRTOS_Routing.c, define `ipconfigCOMPATIBLE_WITH_SINGLE` and run.
=> Network interface ESP32 adapted for /multi, v4

README.md, manifest.yml
Description
-----------
See the title.
Test Steps
-----------
Related Issue
-----------
=> Update Kernel Submodule pointer and the README for release

.github/lexicon.txt, FreeRTOS_DHCP.c, FreeRTOS_DHCPv6.c, FreeRTOS_IP.c, FreeRTOS_ND.c, FreeRTOS_Sockets.c, include/FreeRTOS_IP.h, portable/NetworkInterface/DriverSAM/NetworkInterface.c, portable/NetworkInterface/WinPCap/NetworkInterface.c
Description
-----------
It looks like PR #109 didn't get properly merged. My branch [updates_dhcp_multi](https://github.com/htibosch/FreeRTOS-Plus-TCP/tree/updates_dhcp_multi) did contain the correct code though.
This PR is based on the current contents of branch [ipv6_multi_beta](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/tree/feature/ipv6_multi_beta).
Test Steps
-----------
See earlier PR #107 .
=> Applied PR #107 to DHCP /multi version 2

FreeRTOS_TCP_IP.c
Description
-----------
See the title.
Test Steps
-----------
Related Issue
-----------
=> Fix compiler warnings when the TCP Window is not used

.github/workflows/ci.yml, .gitignore, FreeRTOS_ARP.c, FreeRTOS_IP.c, FreeRTOS_Sockets.c, demos/IPv6_Multi_WinSim_demo/main.c, include/FreeRTOS_DNS.h, test/build-combination/Common/main.c, test/unit-test/ConfigFiles/FreeRTOSConfig.h, test/unit-test/FreeRTOS_TCP_Unit_test.c, test/unit-test/TCPFilePaths.cmake, test/unit-test/cmock/project.yml, test/unit-test/stubs/FreeRTOS_ARP_stubs.c, tools/tcp_utilities/plus_tcp_demo_cli.c
Description
-----------
See the title
Test Steps
-----------
Related Issue
-----------
=> Fix CI checks for IPv6 branch

.github/workflows/ci.yml, docs/doxygen/config.doxyfile
Description
-----------
See the title.
Test Steps
-----------
Related Issue
-----------
=> Update doxygen version and the config file in use

FreeRTOS_Sockets.c
Description
-----------
Close all not yet accepted sockets when the listening socket is closed.
Otherwise these sockets become orphans and cannot be accepted any more.
Already accepted sockets must be closed by the application.
Test Steps
-----------
Close a listening socket when there are new connections which are not accepted.
See it is impossible to bind a new server socket on the same port again, since the
orphans occupy the port.
Related Issue
-----------
https://forums.freertos.org/t/issues-with-freertos-closesocket/12195
=> When a listening socket is closed, close also all orphans

portable/NetworkInterface/Zynq/NetworkInterface.c, portable/NetworkInterface/Zynq/README.txt, portable/NetworkInterface/Zynq/uncached_memory.c, portable/NetworkInterface/Zynq/uncached_memory.h, portable/NetworkInterface/Zynq/x_emacpsif.h, portable/NetworkInterface/Zynq/x_emacpsif_dma.c, portable/NetworkInterface/Zynq/x_emacpsif_hw.c, portable/NetworkInterface/Zynq/x_emacpsif_physpeed.c, portable/NetworkInterface/Zynq/x_topology.h
Description
-----------
This PR make the Zynq driver compatible with the IPv6/multi branch.
=> IPv6/multi : An adapted Zynq driver for multiple EMACs

.github/lexicon.txt, FreeRTOS_RA.c, include/FreeRTOS_Routing.h
Description
-----------
FreeRTOS_RA had two functions that were too complex. I made them simpler by separating some of the code in helper functions:
vReceiveRA()
- vReceiveRA_ReadReply()
vRAProcess()
- xRAProcess_HandleWaitStates()
- xRAProcess_HandleOtherStates()
I also merged the changes proposed in #271, which can now be closed.
Test Steps
-----------
I tested the sources by running the RA procedure.
Related Issue
-----------
=> IPv6/Multi: Reduced complexity FreeRTOS_RA.c

docs/doxygen/config.doxyfile
Description
-----------
This PR will update the configuration file for Doxygen. Earlier this week, the same file was upgraded for the [main branch](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/labs/ipv6_multi/docs/doxygen/config.doxyfile) by @archigup.
=> IPv6/multi: Update Doxygen version to 1.9.2

portable/NetworkInterface/STM32Hxx/NetworkInterface.c
Description
-----------
This PR makes the same type of change as PR #321, but now applied to the IPv6/multi branch.
Test Steps
-----------
I tested the driver on my STM32H747 board. See the [original PR](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/321) for more details.
=> IPv6/multi: STM32Hx driver: check Link Status before sending data

FreeRTOS_IP.c, portable/NetworkInterface/MPS2_AN385/ether_lan9118/SMM_MPS2.h
Description
----------
Remove non-ASCII characters
=> Remove non-ASCII characters

FreeRTOS_IP.c
Description
-----------
This PR adds a proper return value in case of an invalid input and removes an unnecessary check.
Test Steps
-----------
Related Issue
-----------
=> Remove unnecessary checks and add a proper return value in case of error

.github/lexicon.txt, DNS/DNS_Cache.c, DNS/DNS_Callback.c, DNS/DNS_Networking.c, DNS/DNS_Parser.c, FreeRTOS_DHCP.c, FreeRTOS_DNS.c, FreeRTOS_IP_Timers.c, FreeRTOS_UDP_IP.c, include/DNS/DNS_Globals.h, include/DNS/DNS_Networking.h, include/DNS/DNS_Parser.h, include/FreeRTOS_IP.h, include/FreeRTOS_IP_Private.h, include/FreeRTOS_IP_Timers.h, include/FreeRTOS_IP_Utils.h, test/cbmc/proofs/DNS/DNSgetHostByName/DNSgetHostByName_harness.c, test/unit-test/DNS_Cache/DNS_Cache_utest.c, test/unit-test/DNS_Callback/DNS_Callback_utest.c, test/unit-test/DNS_Callback/ut.cmake, test/unit-test/DNS_Networking/DNS_Networking_utest.c, test/unit-test/DNS_Parser/DNS_Parser_utest.c, test/unit-test/FreeRTOS_DNS/FreeRTOS_DNS_utest.c
Fix: compiler warnings and LLMNR fine tuning
Description
-----------
Fix some compilation warnings and fine tune LLMNR behavior
=> Fix:  compiler warnings and LLMNR fine tuning

.github/workflows/uncrustify.yml
Description
-----------
There is a folder in demo directory which should be ignored when running comment triggered uncrustify. This PR adds that to the script.
Test Steps
-----------
Related Issue
-----------
=> Update ignored folder in uncrustify script

include/FreeRTOS_IP.h
Description
-----------
Update version number macros
=> Update version number macros

portable/NetworkInterface/STM32Fxx/NetworkInterface.c, portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.c, portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.h
Description
-----------
This was reported here - https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/411
=> Fix the build issues for STM32Fxx

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation-issue.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/freertos-community_support_forum.yml, .github/lexicon.txt, FreeRTOS_IP.c, FreeRTOS_Sockets.c, FreeRTOS_TCP_State_Handling.c, include/FreeRTOSIPConfigDefaults.h, include/FreeRTOS_Sockets.h, portable/Compiler/CCS/pack_struct_end.h, portable/Compiler/CCS/pack_struct_start.h, portable/NetworkInterface/Common/phyHandling.c, portable/NetworkInterface/STM32Fxx/NetworkInterface.c, portable/NetworkInterface/STM32Fxx/readme.md, portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.c, portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.h, portable/NetworkInterface/TM4C/NetworkInterface.c, portable/NetworkInterface/TM4C/TM4C-README.md, portable/NetworkInterface/include/phyHandling.h, portable/NetworkInterface/xilinx_ultrascale/NetworkInterface.c, portable/NetworkInterface/xilinx_ultrascale/x_emacpsif_physpeed.c, test/unit-test/FreeRTOS_Sockets/FreeRTOS_Sockets_GenericAPI_utest.c
Description
-----------
This PR brings in changes from:
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/424, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/434, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/433
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/437, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/426, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/442
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/429, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/425, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/445
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/448, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/451, https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/458
https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/455
Test Steps …
=> Bring in changes from mainline

test/Coverity/CMakeLists.txt
Description
-----------
This PR updates the source folder location for coverity build.
Test Steps
-----------
Related Issue
-----------
=> Update source location for coverity build

.github/ISSUE_TEMPLATE/config.yml
Description
-----------
Update the config file name in issue templates and update the product name
Test Steps
-----------
Related Issue
-----------
=> Update and rename freertos-community_support_forum.yml to config.yml

source/FreeRTOS_ARP.c
Fix MISRA violations 8.9
Description
-----------
Fix MISRA violations 8.9
=> Fix MISRA violations 8.9

source/FreeRTOS_DNS_Parser.c, source/FreeRTOS_TCP_Transmission.c
Fix misra Rule 2.2 no dead code
Description
-----------
Remove variables declared but never used
=> Fix misra Rule 2.2 no dead code

test/Coverity/ConfigFiles/FreeRTOSIPConfig.h
Fix misra Rule 8.4
Description
-----------
Change the build system to add static a satisfy mira rule 8.4
Test Steps
-----------
Rule violation disappeared from the code checker
=> Fix misra Rule 8.4

source/FreeRTOS_IP_Utils.c, source/FreeRTOS_Sockets.c, source/include/FreeRTOSIPConfigDefaults.h, source/portable/NetworkInterface/STM32Fxx/NetworkInterface.c
This fixes various compiler warnings found when testing with stm32f7
=> Fix various compiler warnings

.github/workflows/ci.yml, source/FreeRTOS_DNS.c, source/FreeRTOS_DNS_Cache.c, source/FreeRTOS_DNS_Networking.c, source/FreeRTOS_DNS_Parser.c, source/FreeRTOS_IP.c, source/FreeRTOS_IP_Utils.c, source/include/FreeRTOS_DNS_Networking.h, test/unit-test/FreeRTOS_DNS/FreeRTOS_DNS_utest.c
Mirsa Rule 10.3 violations
Description
-----------
fix Mirsa Rule 10.3 violations
Test Steps
-----------
Violations disappeared from the report
=> Mirsa Rule 10.3 violations

source/FreeRTOS_DHCP.c, source/FreeRTOS_DNS.c, source/FreeRTOS_DNS_Cache.c, source/FreeRTOS_IP.c, source/FreeRTOS_IP_Utils.c, source/FreeRTOS_Sockets.c, source/FreeRTOS_UDP_IP.c, source/include/FreeRTOSIPConfigDefaults.h, test/Coverity/ConfigFiles/FreeRTOSConfig.h, test/Coverity/ConfigFiles/FreeRTOSIPConfig.h
Misra: Rule 10.4 violations
Description
-----------
Fix misra Rule 10.4 violations.
Test Steps
-----------
Violations disappear form the misra checker
=> Misra: Rule 10.4 violations

source/FreeRTOS_Sockets.c
MISRA: Fix rule 15.5
Description
-----------
MISRA: Fix rule 15.5: functions should have a single return
=> MISRA: Fix rule 15.5

test/Coverity/ConfigFiles/FreeRTOSIPConfig.h
Misra: fix rule 21.1 and 21.2
Description
-----------
Misra: fix rule 21.1 and 21.2
=> Misra: fix rule 21.1 and 21.2

source/FreeRTOS_DNS.c, source/FreeRTOS_IP_Utils.c
MISRA: rule 2.2 fix and suppression
Description
-----------
MISRA: rule 2.2 fix and suppression
=> Misra: rule 2.2 fix and suppression

source/FreeRTOS_ARP.c, source/FreeRTOS_DHCP.c, source/FreeRTOS_DNS.c, source/FreeRTOS_DNS_Cache.c, source/FreeRTOS_DNS_Networking.c, source/FreeRTOS_DNS_Parser.c, source/FreeRTOS_ICMP.c, source/FreeRTOS_IP.c, source/FreeRTOS_IP_Utils.c, source/FreeRTOS_Sockets.c, source/FreeRTOS_TCP_Reception.c, source/FreeRTOS_TCP_WIN.c, source/include/FreeRTOS_ARP.h, source/include/FreeRTOS_DHCP.h, source/include/FreeRTOS_DNS_Networking.h, source/include/FreeRTOS_DNS_Parser.h, source/include/FreeRTOS_ICMP.h, source/include/FreeRTOS_IP_Private.h, source/include/FreeRTOS_Sockets.h
Misra: Fix Rule 8.13 violations
Description
-----------
Fix MISRA Rule 8.13 violations
=> Misra: Fix Rule 8.13 violations

source/FreeRTOS_IP_Utils.c, source/FreeRTOS_Sockets.c, source/include/FreeRTOS_IP_Private.h
MISRA: fix rule 10.8
Description
-----------
MISRA: fix rule 10.8, casting to different integer sizes
=> MISRA: fix rule 10.8

source/FreeRTOS_DNS.c, source/FreeRTOS_IP.c, source/FreeRTOS_Sockets.c
MISRA: fix rule 14.4
Description
-----------
MISRA: fix rule 14.4
=> MISRA: fix rule 14.4

source/FreeRTOS_DNS.c, source/FreeRTOS_DNS_Cache.c, source/FreeRTOS_Sockets.c, source/portable/BufferManagement/BufferAllocation_2.c
Misra: fix rule 20.10, and some random fixes
Description
-----------
Misra: fix rule 20.10, and some random fixes such as adding U to some assignments and some variable name changes
=> Misra: fix rule 20.10, and some random fixes

manifest.yml
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> manifest.yml: add license tag to each dependency

source/FreeRTOS_IP_Utils.c, source/include/FreeRTOS_IP.h, test/unit-test/FreeRTOS_IP_Utils/FreeRTOS_IP_Utils_utest.c
Misra: supressing rule 18.3
Description
-----------
Supressing MISRA rule 18.3
=> Misra: supressing rule 18.3

.gitmodules, README.md, test/cbmc/proofs/run-cbmc-proofs.py
Description
-----------
Changes are related to CBMC CI.
Test Steps
-----------
Related Issue
-----------
=> Remove litani submodule and update README to include a section on CBMC

tools/coverity_misra.config
Misra: suppress directive 4.8 and 4.9
Description
-----------
Misra: suppress directive 4.8 and 4.9
=> Misra: suppress directive 4.8 and 4.9

tools/coverity_misra.config
MISRA: suppress rule 15.4
Description
-----------
MISRA: suppress rule 15.4
do {
} while ( 0 );
multiple breaks in the above statement to make the code cleaner
=> MISRA: suppress rule 15.4

.github/workflows/release.yml, manifest.yml
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Add SBOM Generation in release.yml

source/portable/NetworkInterface/STM32Fxx/stm32fxx_hal_eth.h
This was reported here - https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/issues/411
Signed-off-by: Gaurav Aggarwal <aggarg@amazon.com>
Co-authored-by: Aniruddha Kanhere <60444055+AniruddhaKanhere@users.noreply.github.com>
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Fix the build issues for STM32Fxx (#433)

source/FreeRTOS_ND.c, source/FreeRTOS_RA.c, source/include/FreeRTOS_ND.h
Merge FreeRTOS_ND.c FreeRTOS_RA.c to ipv6_integration  from ipv6_multi
Description
-----------
Files merged:
source/FreeRTOS_ND.c
source/FreeRTOS_RA.c
source/include/FreeRTOS_ND.h
Test Steps
-----------
Related Issue
-----------
=> Merge FreeRTOS_ND.c FreeRTOS_RA.c to ipv6_integration

source/FreeRTOS_Routing.c, source/include/FreeRTOS_ARP.h, source/include/FreeRTOS_IP.h, source/include/FreeRTOS_IP_Private.h, source/include/FreeRTOS_Routing.h
Base Endpoint Changes for IPv6
Description
-----------
Base Endpoint Changes for IPv6
Test Steps
-----------
Related Issue
-----------
=> Base Endpoint Changes for IPv6

source/FreeRTOS_BitConfig.c, source/FreeRTOS_DHCP.c, source/FreeRTOS_IP.c, source/FreeRTOS_IP_Timers.c, source/FreeRTOS_IP_Utils.c, source/FreeRTOS_ND.c, source/FreeRTOS_RA.c, source/FreeRTOS_Routing.c, source/include/FreeRTOSIPConfigDefaults.h, source/include/FreeRTOS_ARP.h, source/include/FreeRTOS_BitConfig.h, source/include/FreeRTOS_IP_Private.h, source/include/FreeRTOS_IP_Timers.h, source/include/FreeRTOS_IPv6_Private.h, source/include/FreeRTOS_ND.h, source/include/FreeRTOS_Routing.h, source/include/IPTraceMacroDefaults.h, test/Coverity/ConfigFiles/FreeRTOSIPConfig.h, test/Coverity/Portable.c
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Fix compilation errors and misra violations

source/FreeRTOS_ARP.c
ARP changes to support IPv6
Description
-----------
The change is to include endpoint related changes
in ARP to support IPv6.
Test Steps
-----------
Related Issue
-----------
=> ARP changes to support IPv6

source/FreeRTOS_DHCP.c, source/FreeRTOS_DHCPv6.c, source/FreeRTOS_IP.c, source/FreeRTOS_IP_Timers.c, source/FreeRTOS_IP_Utils.c, source/FreeRTOS_IPv4.c, source/FreeRTOS_IPv6.c, source/FreeRTOS_Sockets.c, source/include/FreeRTOSIPConfigDefaults.h, source/include/FreeRTOS_DHCPv6.h, source/include/FreeRTOS_IP.h, source/include/FreeRTOS_IPv6.h, source/include/FreeRTOS_IPv6_Private.h, test/Coverity/Portable.c, test/unit-test/ConfigFiles/FreeRTOSIPConfig.h
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Fixing MISRA violation for FreeRTOS_IP*, FreeRTOS_DHCP*

source/FreeRTOS_ARP.c, source/FreeRTOS_IP_Utils.c, source/include/FreeRTOS_ARP.h, source/include/FreeRTOS_DHCP.h, source/include/FreeRTOS_IPv4.h, source/include/FreeRTOS_IPv4_Private.h
Fix compilation errors after adding Endpoint changes in ARP file.
Run uncrustify.
=> Fix Compilation Errors after adding End Point changes

source/FreeRTOS_TCP_IP.c, source/FreeRTOS_TCP_IP_IPV4.c, source/FreeRTOS_TCP_IP_IPV6.c, source/FreeRTOS_TCP_State_Handling.c, source/FreeRTOS_TCP_State_Handling_IPV4.c, source/FreeRTOS_TCP_State_Handling_IPV6.c, source/FreeRTOS_TCP_Transmission.c, source/FreeRTOS_TCP_Transmission_IPV4.c, source/FreeRTOS_TCP_Transmission_IPV6.c, source/FreeRTOS_TCP_Utils.c, source/FreeRTOS_TCP_Utils_IPV4.c, source/FreeRTOS_TCP_Utils_IPV6.c, source/include/FreeRTOS_TCP_IP.h, source/include/FreeRTOS_TCP_State_Handling.h, source/include/FreeRTOS_TCP_Transmission.h
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Fix TCP compilation errors

source/FreeRTOS_ARP.c, source/FreeRTOS_IP.c, source/FreeRTOS_Sockets.c, source/FreeRTOS_TCP_IP_IPV4.c, source/FreeRTOS_TCP_IP_IPV6.c, source/FreeRTOS_TCP_Transmission.c, source/FreeRTOS_TCP_Transmission_IPV4.c, source/FreeRTOS_TCP_Transmission_IPV6.c, source/FreeRTOS_TCP_Utils_IPV4.c, source/FreeRTOS_UDP_IP.c, source/FreeRTOS_UDP_IPv4.c, source/FreeRTOS_UDP_IPv6.c, source/include/FreeRTOS_IP.h, source/include/FreeRTOS_IP_Private.h, source/include/FreeRTOS_IPv4.h, source/include/FreeRTOS_IPv4_Private.h, source/include/FreeRTOS_TCP_Transmission.h, test/build-combination/Common/main.c
Add changes to fix compilation with End point changes being added on TCP/UDP
Run Uncrusitfy
Test Steps
-----------
As of now compilation test is being done.
```
```
=> Fix compilation with end point changes

.github/lexicon.txt, source/FreeRTOS_IP.c, source/include/FreeRTOS_IP.h
Fixed spell check issues
Description
-----------
Updated the lexicon.txt with new words. Corrected issues.
Test Steps
-----------
Ran the spell check script
Related Issue
-----------
Spell check job on github failing
=> Fixing spell check issues

source/FreeRTOS_IP.c, test/unit-test/FreeRTOS_UDP_IP/FreeRTOS_UDP_IP_stubs.c, test/unit-test/FreeRTOS_UDP_IP/FreeRTOS_UDP_IP_utest.c, test/unit-test/FreeRTOS_UDP_IP/list_macros.h
Unit test build fix udp ip ipv4
Description
-----------
Fixed and updated the build failures for UDP unit tests
Test Steps
-----------
Tests building
Related Issue
-----------
Utests build failure
=> Ut build fix udp ip ipv4

source/FreeRTOS_ARP.c, source/include/FreeRTOSIPConfigDefaults.h, test/Coverity/Portable.c, test/build-combination/Common/main.c
Fix uncrusitfy whitespace errors.
Fix Build error in ARP related files.
Test Steps
-----------
As of now compilation test is being done.
```
```
=> Fix uncrustify and Build Errors.

test/unit-test/FreeRTOS_ARP_DataLenLessThanMinPacket/FreeRTOS_ARP_DataLenLessThanMinPacket_stubs.c
Description
-----------
Fixed build issues and updated branch to latest target branch changes
Test Steps
-----------
`
cmake -S test/unit-test -B test/unit-test/build/
make -C test/unit-test/build/ all -j6
`
=> Fixes build issue for the ARP unit tests for the case when data length less than min packet

test/unit-test/FreeRTOS_DNS_Networking/FreeRTOS_DNS_Networking_utest.c, test/unit-test/FreeRTOS_DNS_Networking/FreeRTOS_UDP_IP_stubs.c
Ut build fix DNS networking ipv4
Description
-----------
Fixing build issues for DNS networking unit tests build issues
Test Steps
-----------
Utests builds
Related Issue
-----------
=> Fix dns networking utests build issues

test/unit-test/FreeRTOS_DNS_Callback/FreeRTOS_DNS_Callback_utest.c, test/unit-test/FreeRTOS_DNS_Callback/FreeRTOS_UDP_IP_stubs.c
Ut build fix DNS callback ipv4
Description
-----------
Fixing build issues for DNS callback unit tests build issues
Test Steps
-----------
Utests builds
Related Issue
-----------
=> Fix build failures for dns callback utests

test/unit-test/FreeRTOS_DNS_Cache/FreeRTOS_DNS_Cache_utest.c, test/unit-test/FreeRTOS_DNS_Cache/FreeRTOS_UDP_IP_stubs.c
Ut build fix DNS cache ipv4
Description
-----------
Fixing build issues for DNS cache unit tests build issues
Test Steps
-----------
Utests builds
Related Issue
-----------
=> Fix build failure for dns cache utests

test/unit-test/FreeRTOS_DNS/FreeRTOS_DNS_utest.c, test/unit-test/FreeRTOS_DNS/FreeRTOS_UDP_IP_stubs.c
Ut build fix DNS ipv4
Description
-----------
Fixing build issues for DNS unit tests build issues
Test Steps
-----------
Utests builds
Related Issue
-----------
=> Fixing build issues for dns utests

test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_stubs.c, test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_utest.c
Description
-----------
This PR fixes the build issues related to recent changes in the dev6 branch.
Test Steps
-----------
```
```
Related Issue
-----------
=> Fixes build issue with DHCP unit tests

test/unit-test/FreeRTOS_IP_Utils_DiffConfig/FreeRTOS_IP_Utils_DiffConfig_utest.c
Update Unit Test for IP Utils Diff Config 
Description
-----------
Changed test for prvProcessNetworkDownEvent to accomodate End Point changes 
Test Steps
-----------
Related Issue
-----------
=> Update Unit Test for IP Utils Diff Config 

source/FreeRTOS_ARP.c
Description
-----------
- Added change if Senders address is a multicast OR broadcast address which is not allowed for an ARP packet. Drop the packet. According to RFC 1812 section  * 3.3.2. 
- The local loopback addresses must never appear outside a host. See RFC 1122 * section 3.2.1.3. 
Test Steps
-----------
Compilation
Validated FreeRTOS_Plus_TCP_Minimal_Windows_Simulator
=> Add ARP packet drop cases.

.github/pull_request_template.md
Description
-----------
This PR updates the PR template to include a checkbox which users should go through to verify that they have made unit-test modifications to cover the code changes as outlined in the corresponding PR.
Test Steps
-----------
Related Issue
-----------
=> Update PR template to include checkbox for Unit Test related changes

.github/lexicon.txt, source/FreeRTOS_TCP_Transmission_IPV4.c, source/FreeRTOS_TCP_Transmission_IPV6.c, tools/tcp_utilities/NTPDemo.c
Description
-----------
This PR fixes spelling errors and adds new words to `.github/lexicon.txt`
Test Steps
-----------
Verified in Github CI checks.
Checklist:
----------
=> Fix spell check issues in dev/IPv6_Integration

source/FreeRTOS_ARP.c, source/FreeRTOS_DHCP.c, source/FreeRTOS_IPv6_Sockets.c, source/FreeRTOS_UDP_IPv6.c, test/cbmc/proofs/DHCP/DHCPProcess/DHCPProcess_harness.c, test/unit-test/FreeRTOS_DHCP/FreeRTOS_DHCP_utest.c
Description
-----------
This PR fixes few documentation issues and does refactoring changes to the DHCP CBMC proofs.
Test Steps
-----------
Run CBMC proofs and unit tests.
Checklist:
----------
Related Issue
-----------
Documentation fixes and refactoring.
=> Minor documentation fix and refactoring changes for DHCP CBMC proofs

tools/tcp_utilities/tcp_netstat.c
As ulRemoteIP has been replaced by xRemoteIP, updating the same in tcp_utilities.
Checklist:
----------
Related Issue
-----------
=> Update ulRemoteIP to xRemoteIP

source/include/FreeRTOS_Sockets.h
Description
-----------
The include are causing unnecessary files to be included which is resulting in build failure of MQTT_Mutual_Auth_wolfSSL demo
Checklist:
----------
=> Fix Demo Compilation error

source/FreeRTOS_DNS.c, source/FreeRTOS_IP.c, source/FreeRTOS_IP_Utils.c
Add changes to fix MISRA: Fix 8.9 and 10.4 violation.
Test Steps
-----------
Coverity Run.
Checklist:
----------
=> MISRA: Fix 8.9 and 10.4 violation

.github/workflows/release-candidate.yml
Description
-----------
Cherry-pick main changes:
-----------------------------
PR#761:
This is a minimal subset of release automation which only creates a tag and verifies it.
=> Add release candidate automation (#761)

source/FreeRTOS_DNS_Cache.c, source/FreeRTOS_Sockets.c
Description
-----------
Add changes to fix compilation warning with new code.
Test Steps
-----------
```
```
Checklist:
----------
-----------
=> Fix compilation warning with new code

GettingStarted_4.0.0-rc1.md
Getting started Guide for 4.0.0-rc1
Description
-----------
Getting started Guide for 4.0.0-rc1
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Getting Started Guide for 4.0.0-rc1 Release

History.txt, README.md
Readme and History Changes for V4.0.0-rc1 Release
-----------
Readme and History Changes for V4.0.0-rc1 Release
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Readme and History Changes for V4.0.0-rc1 Release

GettingStarted_4.0.0-rc1.md
Getting Started Guide Updates
Description
-----------
Changes in Getting started guide to make it more user friendly
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Getting Started Guide Doc Updates

docs/doxygen/config.doxyfile, manifest.yml
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Updated version number in doxygen and manifest

.github/pull_request_template.md, source/portable/NetworkInterface/NXP1060/NetworkInterface.c
Description
-----------
Add a FreeRTOS+TCP compatible network interface for this board: https://github.com/FreeRTOS/iot-reference-nxp-rt1060
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Log
------
[DHCP_Check_With_Cable_Disconnects](https://user-images.githubusercontent.com/60444055/225434073-61802d0d-d93b-411f-a638-8844216327e6.jpeg)
=> Add Nxp1060 network interface

source/FreeRTOS_IP.c
Adding Update_MACAddress function to support Network Interface
Description
-----------
ESP32/MW300_rd/M487 Network Interfaces call function **FreeRTOS_UpdateMACAddress** during initialization, 
Adding definitions of these declarations in this commit, with backward compatibility
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> WIP : Adding Update_MACAddr function to support Network Interface

.github/workflows/uncrustify.yml, source/FreeRTOS_ARP.c
Description
-----------
Install git in docker, prevent the apt-get install prompt from discontinuing the install.
=> Fix uncrustify bot command - disable install prompt

source/FreeRTOS_DNS.c, source/portable/Compiler/Keil/pack_struct_start.h
Description
-----------
This PR fixes the build errors and compilation warnings for the Keil compiler. 
Test Steps
-----------
Build succeeds without errors or warnings.
Checklist:
----------
Related Issue
-----------
Build issues and warnings in Keil build.
=> Fix warnings on Keil

.github/lexicon.txt, source/FreeRTOS_UDP_IPv6.c
Description
-----------
This PR updates the endpoint selection for IPv6 UDP when a UDP connection is initiated and the NS packets are sent.
Test Steps
-----------
Tested with IPv6 UDP echo client / server demo with both public and link local IPv6 addresses.
Checklist:
----------
Related Issue
-----------
=> Update IPv6 UDP endpoint selection

docs/doxygen/config.doxyfile, manifest.yml
Description
-----------
* Update release version number in doxygen.
* Update release version number in manifest.
Checklist:
----------
Related Issue
-----------
=> Update Version number in doxygen and manifest

History.txt, README.md
Description
-----------
* Update README.md
* Update History.txt
Checklist:
----------
Related Issue
-----------
=> Readme and History Changes for V4.0.0-rc2 Release

test/unit-test/FreeRTOS_DNS_Callback/FreeRTOS_DNS_Callback_utest.c, test/unit-test/FreeRTOS_DNS_Networking/FreeRTOS_DNS_Networking_utest.c
Fix DNS Callback - DNS Networking UT for coverage
Description
-----------
Add UT for IPv6 branch for 100% coverage 
Test Steps
-----------
Normal Unit Tests compilation method
Checklist:
----------
Related Issue
-----------
=> Fix DNS Callback - DNS Networking UT for coverage

.github/lexicon.txt, source/FreeRTOS_IPv6_Sockets.c, test/unit-test/CMakeLists.txt, test/unit-test/FreeRTOS_Sockets_IPv6/FreeRTOS_Sockets_IPv6_stubs.c, test/unit-test/FreeRTOS_Sockets_IPv6/FreeRTOS_Sockets_IPv6_utest.c, test/unit-test/FreeRTOS_Sockets_IPv6/Sockets_IPv6_list_macros.h, test/unit-test/FreeRTOS_Sockets_IPv6/ut.cmake
Description
-----------
Implement unit tests for sockets IPv6 and 100% code coverage for unit tests.
Test Steps
-----------
Unit tests build and executed. LCOV coverage tested.
Checklist:
----------
Related Issue
-----------
=> Add unit tests for IPv6 Sockets and Code coverage

test/unit-test/FreeRTOS_Routing/FreeRTOSIPConfig.h
[IPv6] Fix Routing UT coverage to 100%
Description
-----------
Enable print function in FreeRTOS_Routing_utest to toggle print in unit test.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> [IPv6] Fix Routing UT coverage to 100%

source/FreeRTOS_DHCP.c
Description
-----------
Add logs to print random number generation failure for better debugging of issue.
Test Steps
-----------
Build Check
Checklist:
----------
Related Issue
-----------
=> Add logs to print random number generation failure

source/portable/NetworkInterface/libslirp/MBuffNetifBackendLibslirp.c
Modified libslirp backend file to cover different libslirp library versions
Description
-----------
Different operating systems have different versions of libslirp installed as system library. Additional conditions are added to ensure the backend source code covers all libslirp versions. 
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Modified libslirp backend file to cover different libslirp library versions

docs/doxygen/config.doxyfile, manifest.yml
Description
-----------
- Update release version number in doxygen.
- Update release version number in manifest.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update Version number in doxygen and manifest for RC3

History.txt, README.md
Description
-----------
- Update README.md
- Update History.txt
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Readme and History Changes for V4.0.0-rc3 Release

GettingStarted_4.0.0-rc3.md
Description
-----------
Getting Started Guide Updates
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update Getting Started Guide Doc

GettingStarted_4.0.0-rc3.md
Description
-----------
Getting Started Guide Updates
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update Getting started guide for RC3

source/portable/NetworkInterface/RX/NetworkInterface.c
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Fix RX network interface to create task only once

.github/workflows/uncrustify.yml
Uncrustify Bot Update
Description
-----------
Fixing the uncrustify bot
Test Steps
-----------
Opened a [PR into my own fork](https://github.com/Skptak/FreeRTOS-Plus-TCP/pull/1) and ran the bot to ensure it would find a formatting issue and then fix it, after the fix made sure the formatting check passed.
Checklist:
----------
Related Issue
-----------
=> Uncrustify Bot Check

tools/tcp_utilities/plus_tcp_demo_cli.c
Description
-----------
Fix use of uninitialized variable warning.
Test Steps
-----------
Demo builds clean locally.
Checklist:
----------
=> Fix use of uninitialized variable warning

docs/doxygen/config.doxyfile, manifest.yml
Description
-----------
- Update release version number in doxygen.
- Update release version number in manifest.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update Version number in doxygen and manifest for GA

History.txt
Update the history section for V4.0.0 release.
Description
-----------
This captures the various changes  and documentation updates and felicitations to the various contributors.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update the History.txt section for V4.0.0 Release

source/FreeRTOS_ARP.c
Description
-----------
This PR fixes the MISRA violations in the FreeRTOS_ARP.c.
Rule:
Rule 21.15
Test Steps
-----------
Ran coverity.
Checklist:
----------
Related Issue
-----------
=> Fix MISRA 2012 violations

CMakeLists.txt
Description
-----------
I see no reason why this wouldn't be here.
Checklist:
----------
=> Add LIBSLIRP to Network Interface selection in CMakeLists

.github/workflows/ci.yml
Speed up unit tests
Description
-----------
I'm not aware of any reason not to do this, but otherwise unit tests can take forever.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Speed up unit tests

docs/doxygen/config.doxyfile, manifest.yml
Description
-----------
This PR updates version number in doxygen and manifest for v4.1.0 release. Also, updates the FreeRTOS-Kernel used for unit tests to the latest (v11.0.1).
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update Version number in doxygen and manifest for v4.1.0

History.txt
Description
-----------
This PR updates the history file with updates/fixes/changes from V4.0.0 to V4.1.0.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update history with changes between V4.1.0 and V4.0.0

.github/workflows/ci.yml
Description
-----------
Update the ci.yml workflow to use echo groups with colour. Use consistent spacing as well.
Test Steps
-----------
View github action page
Checklist:
----------
Related Issue
-----------
=> CI Workflow Update

History.txt
Description
-----------
This PR updates the history file for V4.2.1 release.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update history for V4.2.1 release

manifest.yml
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update manifest to V4.3.1

.github/workflows/ci.yml
Description
-----------
Update CI script to use latest lcov
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update CI script to use latest lcov
